/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.mtc.schema.Server.java
 * 日 期：Thu Oct 09 15:06:53 CST 2014
 */
package jetsennet.mtc.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * MTC_SERVER
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "MTC_SERVER", keyGenerator = "java.util.UUID")
public class Server implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_FIELD_2 = "FIELD_2";
	public static String PROP_HOST_IP = "HOST_IP";
	public static String PROP_HOST_NAME = "HOST_NAME";
	public static String PROP_HOST_PORT = "HOST_PORT";
	public static String PROP_SERVER_ID = "SERVER_ID";
	public static String PROP_SERVER_NAME = "SERVER_NAME";
	public static String PROP_SERVER_TYPE = "SERVER_TYPE";
	public static String PROP_SET_MODE = "SET_MODE";
	public static String PROP_STATE_DESC = "STATE_DESC";
	public static String PROP_SUB_TYPE = "SUB_TYPE";
	public static String PROP_UPDATE_TIME = "UPDATE_TIME";
	public static String PROP_WORK_MODE = "WORK_MODE";
	public static String PROP_WORK_STATE = "WORK_STATE";
	
	/**
	 * primary key field of serverId
	 */
	@FieldMapping(columnName = "SERVER_ID", columnType = 12, primary = true)
	private String serverId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	@FieldMapping(columnName = "HOST_IP", columnType = 12)
	private String hostIp;
	@FieldMapping(columnName = "HOST_NAME", columnType = 12)
	private String hostName;
	@FieldMapping(columnName = "HOST_PORT", columnType = 4)
	private Integer hostPort;
	@FieldMapping(columnName = "SERVER_NAME", columnType = 12)
	private String serverName;
	@FieldMapping(columnName = "SERVER_TYPE", columnType = 4)
	private Integer serverType;
	@FieldMapping(columnName = "SET_MODE", columnType = 4)
	private Integer setMode;
	@FieldMapping(columnName = "STATE_DESC", columnType = 12)
	private String stateDesc;
	@FieldMapping(columnName = "SUB_TYPE", columnType = 4)
	private Integer subType;
	@FieldMapping(columnName = "UPDATE_TIME", columnType = 93)
	private Date updateTime;
	@FieldMapping(columnName = "WORK_MODE", columnType = 4)
	private Integer workMode;
	@FieldMapping(columnName = "WORK_STATE", columnType = 4)
	private Integer workState;
	
	public Server() {
		super();
	}

	public Server(String serverId) {
		this.serverId = serverId;
	}

	public Server(Date createTime, Date updateTime) {
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return this.field2;
	}
	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String field2) {
		this.field2 = field2;
	}

	/**
	 * @return the hostIp
	 */
	public String getHostIp() {
		return this.hostIp;
	}
	
	/**
	 * @param hostIp the hostIp to set
	 */
	public void setHostIp(String hostIp) {
		this.hostIp = hostIp;
	}

	/**
	 * @return the hostName
	 */
	public String getHostName() {
		return this.hostName;
	}
	
	/**
	 * @param hostName the hostName to set
	 */
	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	/**
	 * @return the hostPort
	 */
	public Integer getHostPort() {
		return this.hostPort;
	}
	
	/**
	 * @param hostPort the hostPort to set
	 */
	public void setHostPort(Integer hostPort) {
		this.hostPort = hostPort;
	}

	/**
	 * @return the serverId
	 */
	public String getServerId() {
		return this.serverId;
	}
	
	/**
	 * @param serverId the serverId to set
	 */
	public void setServerId(String serverId) {
		this.serverId = serverId;
	}

	/**
	 * @return the serverName
	 */
	public String getServerName() {
		return this.serverName;
	}
	
	/**
	 * @param serverName the serverName to set
	 */
	public void setServerName(String serverName) {
		this.serverName = serverName;
	}

	/**
	 * @return the serverType
	 */
	public Integer getServerType() {
		return this.serverType;
	}
	
	/**
	 * @param serverType the serverType to set
	 */
	public void setServerType(Integer serverType) {
		this.serverType = serverType;
	}

	/**
	 * @return the setMode
	 */
	public Integer getSetMode() {
		return this.setMode;
	}
	
	/**
	 * @param setMode the setMode to set
	 */
	public void setSetMode(Integer setMode) {
		this.setMode = setMode;
	}

	/**
	 * @return the stateDesc
	 */
	public String getStateDesc() {
		return this.stateDesc;
	}
	
	/**
	 * @param stateDesc the stateDesc to set
	 */
	public void setStateDesc(String stateDesc) {
		this.stateDesc = stateDesc;
	}

	/**
	 * @return the subType
	 */
	public Integer getSubType() {
		return this.subType;
	}
	
	/**
	 * @param subType the subType to set
	 */
	public void setSubType(Integer subType) {
		this.subType = subType;
	}

	/**
	 * @return the updateTime
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}
	
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * @return the workMode
	 */
	public Integer getWorkMode() {
		return this.workMode;
	}
	
	/**
	 * @param workMode the workMode to set
	 */
	public void setWorkMode(Integer workMode) {
		this.workMode = workMode;
	}

	/**
	 * @return the workState
	 */
	public Integer getWorkState() {
		return this.workState;
	}
	
	/**
	 * @param workState the workState to set
	 */
	public void setWorkState(Integer workState) {
		this.workState = workState;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Server)) {
			return false;
		}
		Server other = (Server)o;
		if (null == this.serverId) {
			if (other.serverId != null)
				return false;
		} else if (!this.serverId.equals(other.serverId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((serverId == null) ? 0 : serverId.hashCode());
		return result;
	}
	
}