/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.mtc.schema.Serverlog.java
 * 日 期：Thu Oct 09 15:06:53 CST 2014
 */
package jetsennet.mtc.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * MTC_SERVERLOG
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "MTC_SERVERLOG", keyGenerator = "java.util.UUID")
public class ServerLog implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_END_TIME = "END_TIME";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_FIELD_2 = "FIELD_2";
	public static String PROP_LOG_DESC = "LOG_DESC";
	public static String PROP_LOG_ID = "LOG_ID";
	public static String PROP_LOG_TYPE = "LOG_TYPE";
	public static String PROP_SERVER_ID = "SERVER_ID";
	public static String PROP_START_TIME = "START_TIME";
	
	/**
	 * primary key field of logId
	 */
	@FieldMapping(columnName = "LOG_ID", columnType = 12, primary = true)
	private String logId;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "END_TIME", columnType = 93)
	private Date endTime;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	@FieldMapping(columnName = "LOG_DESC", columnType = 12)
	private String logDesc;
	@FieldMapping(columnName = "LOG_TYPE", columnType = 4)
	private Integer logType;
	@FieldMapping(columnName = "SERVER_ID", columnType = 12)
	private String serverId;
	@FieldMapping(columnName = "START_TIME", columnType = 93)
	private Date startTime;
	
	public ServerLog() {
		super();
	}

	public ServerLog(String logId) {
		this.logId = logId;
	}

	public ServerLog(String serverId, Date startTime) {
		this.serverId = serverId;
		this.startTime = startTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the endTime
	 */
	public Date getEndTime() {
		return this.endTime;
	}
	
	/**
	 * @param endTime the endTime to set
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return this.field2;
	}
	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String field2) {
		this.field2 = field2;
	}

	/**
	 * @return the logDesc
	 */
	public String getLogDesc() {
		return this.logDesc;
	}
	
	/**
	 * @param logDesc the logDesc to set
	 */
	public void setLogDesc(String logDesc) {
		this.logDesc = logDesc;
	}

	/**
	 * @return the logId
	 */
	public String getLogId() {
		return this.logId;
	}
	
	/**
	 * @param logId the logId to set
	 */
	public void setLogId(String logId) {
		this.logId = logId;
	}

	/**
	 * @return the logType
	 */
	public Integer getLogType() {
		return this.logType;
	}
	
	/**
	 * @param logType the logType to set
	 */
	public void setLogType(Integer logType) {
		this.logType = logType;
	}

	/**
	 * @return the serverId
	 */
	public String getServerId() {
		return this.serverId;
	}
	
	/**
	 * @param serverId the serverId to set
	 */
	public void setServerId(String serverId) {
		this.serverId = serverId;
	}

	/**
	 * @return the startTime
	 */
	public Date getStartTime() {
		return this.startTime;
	}
	
	/**
	 * @param startTime the startTime to set
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof ServerLog)) {
			return false;
		}
		ServerLog other = (ServerLog)o;
		if (null == this.logId) {
			if (other.logId != null)
				return false;
		} else if (!this.logId.equals(other.logId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((logId == null) ? 0 : logId.hashCode());
		return result;
	}
	
}