/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.mtc.schema.Tasklog.java
 * 日 期：Thu Oct 09 15:06:53 CST 2014
 */
package jetsennet.mtc.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * MTC_TASKLOG
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "MTC_TASKLOG", keyGenerator = "java.util.UUID")
public class TaskLog implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_APP_OBJID = "APP_OBJID";
	public static String PROP_APP_OBJSOURCE = "APP_OBJSOURCE";
	public static String PROP_APP_OBJTYPE = "APP_OBJTYPE";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_END_TIME = "END_TIME";
	public static String PROP_EXEC_MODE = "EXEC_MODE";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_FIELD_2 = "FIELD_2";
	public static String PROP_FIELD_3 = "FIELD_3";
	public static String PROP_FIELD_4 = "FIELD_4";
	public static String PROP_FIELD_5 = "FIELD_5";
	public static String PROP_MESSAGE_ID = "MESSAGE_ID";
	public static String PROP_NOTIFY_TYPE = "NOTIFY_TYPE";
	public static String PROP_NOTIFY_URL = "NOTIFY_URL";
	public static String PROP_PARENT_ID = "PARENT_ID";
	public static String PROP_PREV_TASKID = "PREV_TASKID";
	public static String PROP_START_TIME = "START_TIME";
	public static String PROP_STATE_DESC = "STATE_DESC";
	public static String PROP_SUB_TYPE = "SUB_TYPE";
	public static String PROP_TASK_ACTOR = "TASK_ACTOR";
	public static String PROP_TASK_GROUP = "TASK_GROUP";
	public static String PROP_TASK_ID = "TASK_ID";
	public static String PROP_TASK_LEVEL = "TASK_LEVEL";
	public static String PROP_TASK_NAME = "TASK_NAME";
	public static String PROP_TASK_PERCENT = "TASK_PERCENT";
	public static String PROP_TASK_STATE = "TASK_STATE";
	public static String PROP_TASK_TYPE = "TASK_TYPE";
	public static String PROP_TASK_WORKER = "TASK_WORKER";
	public static String PROP_TASK_XML = "TASK_XML";
	
	/**
	 * primary key field of taskId
	 */
	@FieldMapping(columnName = "TASK_ID", columnType = 12, primary = true)
	private String taskId;
	@FieldMapping(columnName = "APP_OBJID", columnType = 12)
	private String appObjid;
	@FieldMapping(columnName = "APP_OBJSOURCE", columnType = 12)
	private String appObjsource;
	@FieldMapping(columnName = "APP_OBJTYPE", columnType = 4)
	private Integer appObjtype;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "END_TIME", columnType = 93)
	private Date endTime;
	@FieldMapping(columnName = "EXEC_MODE", columnType = 4)
	private Integer execMode;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	@FieldMapping(columnName = "FIELD_3", columnType = 12)
	private String field3;
	@FieldMapping(columnName = "FIELD_4", columnType = 12)
	private String field4;
	@FieldMapping(columnName = "FIELD_5", columnType = 12)
	private String field5;
	@FieldMapping(columnName = "MESSAGE_ID", columnType = 12)
	private String messageId;
	@FieldMapping(columnName = "NOTIFY_TYPE", columnType = 4)
	private Integer notifyType;
	@FieldMapping(columnName = "NOTIFY_URL", columnType = 12)
	private String notifyUrl;
	@FieldMapping(columnName = "PARENT_ID", columnType = 12)
	private String parentId;
	@FieldMapping(columnName = "PREV_TASKID", columnType = 12)
	private String prevTaskid;
	@FieldMapping(columnName = "START_TIME", columnType = 93)
	private Date startTime;
	@FieldMapping(columnName = "STATE_DESC", columnType = 12)
	private String stateDesc;
	@FieldMapping(columnName = "SUB_TYPE", columnType = 12)
	private String subType;
	@FieldMapping(columnName = "TASK_ACTOR", columnType = 12)
	private String taskActor;
	@FieldMapping(columnName = "TASK_GROUP", columnType = 4)
	private Integer taskGroup;
	@FieldMapping(columnName = "TASK_LEVEL", columnType = 4)
	private Integer taskLevel;
	@FieldMapping(columnName = "TASK_NAME", columnType = 12)
	private String taskName;
	@FieldMapping(columnName = "TASK_PERCENT", columnType = 4)
	private Integer taskPercent;
	@FieldMapping(columnName = "TASK_STATE", columnType = 4)
	private Integer taskState;
	@FieldMapping(columnName = "TASK_TYPE", columnType = 4)
	private Integer taskType;
	@FieldMapping(columnName = "TASK_WORKER", columnType = 12)
	private String taskWorker;
	@FieldMapping(columnName = "TASK_XML", columnType = 2005)
	private String taskXml;
	
	public TaskLog() {
		super();
	}

	public TaskLog(String taskId) {
		this.taskId = taskId;
	}

	public TaskLog(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the appObjid
	 */
	public String getAppObjid() {
		return this.appObjid;
	}
	
	/**
	 * @param appObjid the appObjid to set
	 */
	public void setAppObjid(String appObjid) {
		this.appObjid = appObjid;
	}

	/**
	 * @return the appObjsource
	 */
	public String getAppObjsource() {
		return this.appObjsource;
	}
	
	/**
	 * @param appObjsource the appObjsource to set
	 */
	public void setAppObjsource(String appObjsource) {
		this.appObjsource = appObjsource;
	}

	/**
	 * @return the appObjtype
	 */
	public Integer getAppObjtype() {
		return this.appObjtype;
	}
	
	/**
	 * @param appObjtype the appObjtype to set
	 */
	public void setAppObjtype(Integer appObjtype) {
		this.appObjtype = appObjtype;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the endTime
	 */
	public Date getEndTime() {
		return this.endTime;
	}
	
	/**
	 * @param endTime the endTime to set
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * @return the execMode
	 */
	public Integer getExecMode() {
		return this.execMode;
	}
	
	/**
	 * @param execMode the execMode to set
	 */
	public void setExecMode(Integer execMode) {
		this.execMode = execMode;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return this.field2;
	}
	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String field2) {
		this.field2 = field2;
	}

	/**
	 * @return the field3
	 */
	public String getField3() {
		return this.field3;
	}
	
	/**
	 * @param field3 the field3 to set
	 */
	public void setField3(String field3) {
		this.field3 = field3;
	}

	/**
	 * @return the field4
	 */
	public String getField4() {
		return this.field4;
	}
	
	/**
	 * @param field4 the field4 to set
	 */
	public void setField4(String field4) {
		this.field4 = field4;
	}

	/**
	 * @return the field5
	 */
	public String getField5() {
		return this.field5;
	}
	
	/**
	 * @param field5 the field5 to set
	 */
	public void setField5(String field5) {
		this.field5 = field5;
	}

	/**
	 * @return the messageId
	 */
	public String getMessageId() {
		return this.messageId;
	}
	
	/**
	 * @param messageId the messageId to set
	 */
	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	/**
	 * @return the notifyType
	 */
	public Integer getNotifyType() {
		return this.notifyType;
	}
	
	/**
	 * @param notifyType the notifyType to set
	 */
	public void setNotifyType(Integer notifyType) {
		this.notifyType = notifyType;
	}

	/**
	 * @return the notifyUrl
	 */
	public String getNotifyUrl() {
		return this.notifyUrl;
	}
	
	/**
	 * @param notifyUrl the notifyUrl to set
	 */
	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl;
	}

	/**
	 * @return the parentId
	 */
	public String getParentId() {
		return this.parentId;
	}
	
	/**
	 * @param parentId the parentId to set
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * @return the prevTaskid
	 */
	public String getPrevTaskid() {
		return this.prevTaskid;
	}
	
	/**
	 * @param prevTaskid the prevTaskid to set
	 */
	public void setPrevTaskid(String prevTaskid) {
		this.prevTaskid = prevTaskid;
	}

	/**
	 * @return the startTime
	 */
	public Date getStartTime() {
		return this.startTime;
	}
	
	/**
	 * @param startTime the startTime to set
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * @return the stateDesc
	 */
	public String getStateDesc() {
		return this.stateDesc;
	}
	
	/**
	 * @param stateDesc the stateDesc to set
	 */
	public void setStateDesc(String stateDesc) {
		this.stateDesc = stateDesc;
	}

	/**
	 * @return the subType
	 */
	public String getSubType() {
		return this.subType;
	}
	
	/**
	 * @param subType the subType to set
	 */
	public void setSubType(String subType) {
		this.subType = subType;
	}

	/**
	 * @return the taskActor
	 */
	public String getTaskActor() {
		return this.taskActor;
	}
	
	/**
	 * @param taskActor the taskActor to set
	 */
	public void setTaskActor(String taskActor) {
		this.taskActor = taskActor;
	}

	/**
	 * @return the taskGroup
	 */
	public Integer getTaskGroup() {
		return this.taskGroup;
	}
	
	/**
	 * @param taskGroup the taskGroup to set
	 */
	public void setTaskGroup(Integer taskGroup) {
		this.taskGroup = taskGroup;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	/**
	 * @return the taskLevel
	 */
	public Integer getTaskLevel() {
		return this.taskLevel;
	}
	
	/**
	 * @param taskLevel the taskLevel to set
	 */
	public void setTaskLevel(Integer taskLevel) {
		this.taskLevel = taskLevel;
	}

	/**
	 * @return the taskName
	 */
	public String getTaskName() {
		return this.taskName;
	}
	
	/**
	 * @param taskName the taskName to set
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	/**
	 * @return the taskPercent
	 */
	public Integer getTaskPercent() {
		return this.taskPercent;
	}
	
	/**
	 * @param taskPercent the taskPercent to set
	 */
	public void setTaskPercent(Integer taskPercent) {
		this.taskPercent = taskPercent;
	}

	/**
	 * @return the taskState
	 */
	public Integer getTaskState() {
		return this.taskState;
	}
	
	/**
	 * @param taskState the taskState to set
	 */
	public void setTaskState(Integer taskState) {
		this.taskState = taskState;
	}

	/**
	 * @return the taskType
	 */
	public Integer getTaskType() {
		return this.taskType;
	}
	
	/**
	 * @param taskType the taskType to set
	 */
	public void setTaskType(Integer taskType) {
		this.taskType = taskType;
	}

	/**
	 * @return the taskWorker
	 */
	public String getTaskWorker() {
		return this.taskWorker;
	}
	
	/**
	 * @param taskWorker the taskWorker to set
	 */
	public void setTaskWorker(String taskWorker) {
		this.taskWorker = taskWorker;
	}

	/**
	 * @return the taskXml
	 */
	public String getTaskXml() {
		return this.taskXml;
	}
	
	/**
	 * @param taskXml the taskXml to set
	 */
	public void setTaskXml(String taskXml) {
		this.taskXml = taskXml;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof TaskLog)) {
			return false;
		}
		TaskLog other = (TaskLog)o;
		if (null == this.taskId) {
			if (other.taskId != null)
				return false;
		} else if (!this.taskId.equals(other.taskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}
	
}