/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.Cm802Object.java
 * 日 期：Sat Nov 15 14:42:32 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * CM802_OBJECT
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "CM802_OBJECT", keyGenerator = "uuid")
public class Cm802Object implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_BEGINTIME = "BEGINTIME";
	public static String PROP_CMOBJ_ID = "CMOBJ_ID";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_CVALID = "CVALID";
	public static String PROP_DATAFROMSYS = "DATAFROMSYS";
	public static String PROP_DATASERVERIP = "DATASERVERIP";
	public static String PROP_DEST_PORT = "DEST_PORT";
	public static String PROP_DOWNLOADFILENAME = "DOWNLOADFILENAME";
	public static String PROP_DS_ID = "DS_ID";
	public static String PROP_FILEID = "FILEID";
	public static String PROP_FILELEN = "FILELEN";
	public static String PROP_FROM_IP = "FROM_IP";
	public static String PROP_FROMUSER = "FROMUSER";
	public static String PROP_FTPIP = "FTPIP";
	public static String PROP_GRADE0 = "GRADE0";
	public static String PROP_GRADE1 = "GRADE1";
	public static String PROP_IISCRACTED = "IISCRACTED";
	public static String PROP_LINENO1 = "LINENO1";
	public static String PROP_LINENO2 = "LINENO2";
	public static String PROP_LINENO3 = "LINENO3";
	public static String PROP_LINENO4 = "LINENO4";
	public static String PROP_NAME = "NAME";
	public static String PROP_PARTNO = "PARTNO";
	public static String PROP_PASSWORD = "PASSWORD";
	public static String PROP_PUNIT = "PUNIT";
	public static String PROP_SFROMIP = "SFROMIP";
	public static String PROP_SOURE_PORT = "SOURE_PORT";
	public static String PROP_STATE = "STATE";
	public static String PROP_STOIP = "STOIP";
	public static String PROP_STR_1 = "STR_1";
	public static String PROP_STR_2 = "STR_2";
	public static String PROP_STYPE = "STYPE";
	public static String PROP_TO_IP = "TO_IP";
	public static String PROP_USERNAME = "USERNAME";
	public static String PROP_XTYPE = "XTYPE";
	
	/**
	 * primary key field of cmobjId
	 */
	@FieldMapping(columnName = "CMOBJ_ID", columnType = 12, primary = true)
	private String cmobjId;
	@FieldMapping(columnName = "BEGINTIME", columnType = 93)
	private Date begintime;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "CVALID", columnType = 4)
	private Integer cvalid;
	@FieldMapping(columnName = "DATAFROMSYS", columnType = 12)
	private String datafromsys;
	@FieldMapping(columnName = "DATASERVERIP", columnType = 12)
	private String dataserverip;
	@FieldMapping(columnName = "DEST_PORT", columnType = 12)
	private String destPort;
	@FieldMapping(columnName = "DOWNLOADFILENAME", columnType = 12)
	private String downloadfilename;
	@FieldMapping(columnName = "DS_ID", columnType = 12)
	private String dsId;
	@FieldMapping(columnName = "FILEID", columnType = -9)
	private String fileid;
	@FieldMapping(columnName = "FILELEN", columnType = -9)
	private String filelen;
	@FieldMapping(columnName = "FROM_IP", columnType = -9)
	private String fromIp;
	@FieldMapping(columnName = "FROMUSER", columnType = 12)
	private String fromuser;
	@FieldMapping(columnName = "FTPIP", columnType = -9)
	private String ftpip;
	@FieldMapping(columnName = "GRADE0", columnType = 12)
	private String grade0;
	@FieldMapping(columnName = "GRADE1", columnType = 12)
	private String grade1;
	@FieldMapping(columnName = "IISCRACTED", columnType = 4)
	private Integer iiscracted;
	@FieldMapping(columnName = "LINENO1", columnType = -9)
	private String lineno1;
	@FieldMapping(columnName = "LINENO2", columnType = -9)
	private String lineno2;
	@FieldMapping(columnName = "LINENO3", columnType = 12)
	private String lineno3;
	@FieldMapping(columnName = "LINENO4", columnType = 12)
	private String lineno4;
	@FieldMapping(columnName = "NAME", columnType = 12)
	private String name;
	@FieldMapping(columnName = "PARTNO", columnType = 12)
	private String partno;
	@FieldMapping(columnName = "PASSWORD", columnType = -9)
	private String password;
	@FieldMapping(columnName = "PUNIT", columnType = 12)
	private String punit;
	@FieldMapping(columnName = "SFROMIP", columnType = -9)
	private String sfromip;
	@FieldMapping(columnName = "SOURE_PORT", columnType = 12)
	private String sourePort;
	@FieldMapping(columnName = "STATE", columnType = 4)
	private Integer state;
	@FieldMapping(columnName = "STOIP", columnType = -9)
	private String stoip;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	@FieldMapping(columnName = "STR_2", columnType = 12)
	private String str2;
	@FieldMapping(columnName = "STYPE", columnType = -9)
	private String stype;
	@FieldMapping(columnName = "TO_IP", columnType = -9)
	private String toIp;
	@FieldMapping(columnName = "USERNAME", columnType = -9)
	private String username;
	@FieldMapping(columnName = "XTYPE", columnType = 12)
	private String xtype;
	
	public Cm802Object() {
		super();
	}

	public Cm802Object(String cmobjId) {
		this.cmobjId = cmobjId;
	}

	public Cm802Object(Date createTime, Integer createUserid) {
		this.createTime = createTime;
		this.createUserid = createUserid;
	}

	/**
	 * @return the begintime
	 */
	public Date getBegintime() {
		return this.begintime;
	}
	
	/**
	 * @param begintime the begintime to set
	 */
	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	/**
	 * @return the cmobjId
	 */
	public String getCmobjId() {
		return this.cmobjId;
	}
	
	/**
	 * @param cmobjId the cmobjId to set
	 */
	public void setCmobjId(String cmobjId) {
		this.cmobjId = cmobjId;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the cvalid
	 */
	public Integer getCvalid() {
		return this.cvalid;
	}
	
	/**
	 * @param cvalid the cvalid to set
	 */
	public void setCvalid(Integer cvalid) {
		this.cvalid = cvalid;
	}

	/**
	 * @return the datafromsys
	 */
	public String getDatafromsys() {
		return this.datafromsys;
	}
	
	/**
	 * @param datafromsys the datafromsys to set
	 */
	public void setDatafromsys(String datafromsys) {
		this.datafromsys = datafromsys;
	}

	/**
	 * @return the dataserverip
	 */
	public String getDataserverip() {
		return this.dataserverip;
	}
	
	/**
	 * @param dataserverip the dataserverip to set
	 */
	public void setDataserverip(String dataserverip) {
		this.dataserverip = dataserverip;
	}

	/**
	 * @return the destPort
	 */
	public String getDestPort() {
		return this.destPort;
	}
	
	/**
	 * @param destPort the destPort to set
	 */
	public void setDestPort(String destPort) {
		this.destPort = destPort;
	}

	/**
	 * @return the downloadfilename
	 */
	public String getDownloadfilename() {
		return this.downloadfilename;
	}
	
	/**
	 * @param downloadfilename the downloadfilename to set
	 */
	public void setDownloadfilename(String downloadfilename) {
		this.downloadfilename = downloadfilename;
	}

	/**
	 * @return the dsId
	 */
	public String getDsId() {
		return this.dsId;
	}
	
	/**
	 * @param dsId the dsId to set
	 */
	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	/**
	 * @return the fileid
	 */
	public String getFileid() {
		return this.fileid;
	}
	
	/**
	 * @param fileid the fileid to set
	 */
	public void setFileid(String fileid) {
		this.fileid = fileid;
	}

	/**
	 * @return the filelen
	 */
	public String getFilelen() {
		return this.filelen;
	}
	
	/**
	 * @param filelen the filelen to set
	 */
	public void setFilelen(String filelen) {
		this.filelen = filelen;
	}

	/**
	 * @return the fromIp
	 */
	public String getFromIp() {
		return this.fromIp;
	}
	
	/**
	 * @param fromIp the fromIp to set
	 */
	public void setFromIp(String fromIp) {
		this.fromIp = fromIp;
	}

	/**
	 * @return the fromuser
	 */
	public String getFromuser() {
		return this.fromuser;
	}
	
	/**
	 * @param fromuser the fromuser to set
	 */
	public void setFromuser(String fromuser) {
		this.fromuser = fromuser;
	}

	/**
	 * @return the ftpip
	 */
	public String getFtpip() {
		return this.ftpip;
	}
	
	/**
	 * @param ftpip the ftpip to set
	 */
	public void setFtpip(String ftpip) {
		this.ftpip = ftpip;
	}

	/**
	 * @return the grade0
	 */
	public String getGrade0() {
		return this.grade0;
	}
	
	/**
	 * @param grade0 the grade0 to set
	 */
	public void setGrade0(String grade0) {
		this.grade0 = grade0;
	}

	/**
	 * @return the grade1
	 */
	public String getGrade1() {
		return this.grade1;
	}
	
	/**
	 * @param grade1 the grade1 to set
	 */
	public void setGrade1(String grade1) {
		this.grade1 = grade1;
	}

	/**
	 * @return the iiscracted
	 */
	public Integer getIiscracted() {
		return this.iiscracted;
	}
	
	/**
	 * @param iiscracted the iiscracted to set
	 */
	public void setIiscracted(Integer iiscracted) {
		this.iiscracted = iiscracted;
	}

	/**
	 * @return the lineno1
	 */
	public String getLineno1() {
		return this.lineno1;
	}
	
	/**
	 * @param lineno1 the lineno1 to set
	 */
	public void setLineno1(String lineno1) {
		this.lineno1 = lineno1;
	}

	/**
	 * @return the lineno2
	 */
	public String getLineno2() {
		return this.lineno2;
	}
	
	/**
	 * @param lineno2 the lineno2 to set
	 */
	public void setLineno2(String lineno2) {
		this.lineno2 = lineno2;
	}

	/**
	 * @return the lineno3
	 */
	public String getLineno3() {
		return this.lineno3;
	}
	
	/**
	 * @param lineno3 the lineno3 to set
	 */
	public void setLineno3(String lineno3) {
		this.lineno3 = lineno3;
	}

	/**
	 * @return the lineno4
	 */
	public String getLineno4() {
		return this.lineno4;
	}
	
	/**
	 * @param lineno4 the lineno4 to set
	 */
	public void setLineno4(String lineno4) {
		this.lineno4 = lineno4;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the partno
	 */
	public String getPartno() {
		return this.partno;
	}
	
	/**
	 * @param partno the partno to set
	 */
	public void setPartno(String partno) {
		this.partno = partno;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return this.password;
	}
	
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the punit
	 */
	public String getPunit() {
		return this.punit;
	}
	
	/**
	 * @param punit the punit to set
	 */
	public void setPunit(String punit) {
		this.punit = punit;
	}

	/**
	 * @return the sfromip
	 */
	public String getSfromip() {
		return this.sfromip;
	}
	
	/**
	 * @param sfromip the sfromip to set
	 */
	public void setSfromip(String sfromip) {
		this.sfromip = sfromip;
	}

	/**
	 * @return the sourePort
	 */
	public String getSourePort() {
		return this.sourePort;
	}
	
	/**
	 * @param sourePort the sourePort to set
	 */
	public void setSourePort(String sourePort) {
		this.sourePort = sourePort;
	}

	/**
	 * @return the state
	 */
	public Integer getState() {
		return this.state;
	}
	
	/**
	 * @param state the state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * @return the stoip
	 */
	public String getStoip() {
		return this.stoip;
	}
	
	/**
	 * @param stoip the stoip to set
	 */
	public void setStoip(String stoip) {
		this.stoip = stoip;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/**
	 * @return the str2
	 */
	public String getStr2() {
		return this.str2;
	}
	
	/**
	 * @param str2 the str2 to set
	 */
	public void setStr2(String str2) {
		this.str2 = str2;
	}

	/**
	 * @return the stype
	 */
	public String getStype() {
		return this.stype;
	}
	
	/**
	 * @param stype the stype to set
	 */
	public void setStype(String stype) {
		this.stype = stype;
	}

	/**
	 * @return the toIp
	 */
	public String getToIp() {
		return this.toIp;
	}
	
	/**
	 * @param toIp the toIp to set
	 */
	public void setToIp(String toIp) {
		this.toIp = toIp;
	}

	/**
	 * @return the username
	 */
	public String getUsername() {
		return this.username;
	}
	
	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * @return the xtype
	 */
	public String getXtype() {
		return this.xtype;
	}
	
	/**
	 * @param xtype the xtype to set
	 */
	public void setXtype(String xtype) {
		this.xtype = xtype;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Cm802Object)) {
			return false;
		}
		Cm802Object other = (Cm802Object)o;
		if (null == this.cmobjId) {
			if (other.cmobjId != null)
				return false;
		} else if (!this.cmobjId.equals(other.cmobjId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cmobjId == null) ? 0 : cmobjId.hashCode());
		return result;
	}
	
}