/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.Cm803Object.java
 * 日 期：Sat Nov 15 14:42:41 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * CM803_OBJECT
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "CM803_OBJECT", keyGenerator = "uuid")
public class Cm803Object implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CMOBJ_ID = "CMOBJ_ID";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_DS_ID = "DS_ID";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_FIELD_10 = "FIELD_10";
	public static String PROP_FIELD_11 = "FIELD_11";
	public static String PROP_FIELD_12 = "FIELD_12";
	public static String PROP_FIELD_13 = "FIELD_13";
	public static String PROP_FIELD_14 = "FIELD_14";
	public static String PROP_FIELD_15 = "FIELD_15";
	public static String PROP_FIELD_16 = "FIELD_16";
	public static String PROP_FIELD_17 = "FIELD_17";
	public static String PROP_FIELD_18 = "FIELD_18";
	public static String PROP_FIELD_19 = "FIELD_19";
	public static String PROP_FIELD_2 = "FIELD_2";
	public static String PROP_FIELD_20 = "FIELD_20";
	public static String PROP_FIELD_21 = "FIELD_21";
	public static String PROP_FIELD_22 = "FIELD_22";
	public static String PROP_FIELD_23 = "FIELD_23";
	public static String PROP_FIELD_24 = "FIELD_24";
	public static String PROP_FIELD_25 = "FIELD_25";
	public static String PROP_FIELD_26 = "FIELD_26";
	public static String PROP_FIELD_27 = "FIELD_27";
	public static String PROP_FIELD_28 = "FIELD_28";
	public static String PROP_FIELD_29 = "FIELD_29";
	public static String PROP_FIELD_3 = "FIELD_3";
	public static String PROP_FIELD_30 = "FIELD_30";
	public static String PROP_FIELD_31 = "FIELD_31";
	public static String PROP_FIELD_32 = "FIELD_32";
	public static String PROP_FIELD_4 = "FIELD_4";
	public static String PROP_FIELD_5 = "FIELD_5";
	public static String PROP_FIELD_6 = "FIELD_6";
	public static String PROP_FIELD_7 = "FIELD_7";
	public static String PROP_FIELD_8 = "FIELD_8";
	public static String PROP_FIELD_9 = "FIELD_9";
	public static String PROP_INT_1 = "INT_1";
	public static String PROP_INT_2 = "INT_2";
	public static String PROP_INT_3 = "INT_3";
	public static String PROP_NAME = "NAME";
	public static String PROP_STATE = "STATE";
	public static String PROP_STR_1 = "STR_1";
	public static String PROP_STR_2 = "STR_2";
	public static String PROP_STR_3 = "STR_3";
	public static String PROP_STR_4 = "STR_4";
	public static String PROP_STR_5 = "STR_5";
	public static String PROP_TIME_1 = "TIME_1";
	
	/**
	 * primary key field of cmobjId
	 */
	@FieldMapping(columnName = "CMOBJ_ID", columnType = 12, primary = true)
	private String cmobjId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "DS_ID", columnType = 12)
	private String dsId;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_10", columnType = 12)
	private String field10;
	@FieldMapping(columnName = "FIELD_11", columnType = 12)
	private String field11;
	@FieldMapping(columnName = "FIELD_12", columnType = 12)
	private String field12;
	@FieldMapping(columnName = "FIELD_13", columnType = 12)
	private String field13;
	@FieldMapping(columnName = "FIELD_14", columnType = 4)
	private Integer field14;
	@FieldMapping(columnName = "FIELD_15", columnType = 4)
	private Integer field15;
	@FieldMapping(columnName = "FIELD_16", columnType = 4)
	private Integer field16;
	@FieldMapping(columnName = "FIELD_17", columnType = 4)
	private Integer field17;
	@FieldMapping(columnName = "FIELD_18", columnType = 4)
	private Integer field18;
	@FieldMapping(columnName = "FIELD_19", columnType = 4)
	private Integer field19;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	@FieldMapping(columnName = "FIELD_20", columnType = 4)
	private Integer field20;
	@FieldMapping(columnName = "FIELD_21", columnType = 4)
	private Integer field21;
	@FieldMapping(columnName = "FIELD_22", columnType = 4)
	private Integer field22;
	@FieldMapping(columnName = "FIELD_23", columnType = 4)
	private Integer field23;
	@FieldMapping(columnName = "FIELD_24", columnType = 4)
	private Integer field24;
	@FieldMapping(columnName = "FIELD_25", columnType = 4)
	private Integer field25;
	@FieldMapping(columnName = "FIELD_26", columnType = 4)
	private Integer field26;
	@FieldMapping(columnName = "FIELD_27", columnType = 4)
	private Integer field27;
	@FieldMapping(columnName = "FIELD_28", columnType = 4)
	private Integer field28;
	@FieldMapping(columnName = "FIELD_29", columnType = 4)
	private Integer field29;
	@FieldMapping(columnName = "FIELD_3", columnType = 12)
	private String field3;
	@FieldMapping(columnName = "FIELD_30", columnType = 4)
	private Integer field30;
	@FieldMapping(columnName = "FIELD_31", columnType = 4)
	private Integer field31;
	@FieldMapping(columnName = "FIELD_32", columnType = 12)
	private String field32;
	@FieldMapping(columnName = "FIELD_4", columnType = 12)
	private String field4;
	@FieldMapping(columnName = "FIELD_5", columnType = 12)
	private String field5;
	@FieldMapping(columnName = "FIELD_6", columnType = 12)
	private String field6;
	@FieldMapping(columnName = "FIELD_7", columnType = 12)
	private String field7;
	@FieldMapping(columnName = "FIELD_8", columnType = 4)
	private Integer field8;
	@FieldMapping(columnName = "FIELD_9", columnType = 12)
	private String field9;
	@FieldMapping(columnName = "INT_1", columnType = 4)
	private Integer int1;
	@FieldMapping(columnName = "INT_2", columnType = 4)
	private Integer int2;
	@FieldMapping(columnName = "INT_3", columnType = 4)
	private Integer int3;
	@FieldMapping(columnName = "NAME", columnType = 12)
	private String name;
	@FieldMapping(columnName = "STATE", columnType = 4)
	private Integer state;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	@FieldMapping(columnName = "STR_2", columnType = 12)
	private String str2;
	@FieldMapping(columnName = "STR_3", columnType = -1)
	private String str3;
	@FieldMapping(columnName = "STR_4", columnType = -9)
	private String str4;
	@FieldMapping(columnName = "STR_5", columnType = -9)
	private String str5;
	@FieldMapping(columnName = "TIME_1", columnType = 93)
	private Date time1;
	
	public Cm803Object() {
		super();
	}

	public Cm803Object(String cmobjId) {
		this.cmobjId = cmobjId;
	}

	public Cm803Object(Date createTime, Integer createUserid) {
		this.createTime = createTime;
		this.createUserid = createUserid;
	}

	/**
	 * @return the cmobjId
	 */
	public String getCmobjId() {
		return this.cmobjId;
	}
	
	/**
	 * @param cmobjId the cmobjId to set
	 */
	public void setCmobjId(String cmobjId) {
		this.cmobjId = cmobjId;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the dsId
	 */
	public String getDsId() {
		return this.dsId;
	}
	
	/**
	 * @param dsId the dsId to set
	 */
	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the field10
	 */
	public String getField10() {
		return this.field10;
	}
	
	/**
	 * @param field10 the field10 to set
	 */
	public void setField10(String field10) {
		this.field10 = field10;
	}

	/**
	 * @return the field11
	 */
	public String getField11() {
		return this.field11;
	}
	
	/**
	 * @param field11 the field11 to set
	 */
	public void setField11(String field11) {
		this.field11 = field11;
	}

	/**
	 * @return the field12
	 */
	public String getField12() {
		return this.field12;
	}
	
	/**
	 * @param field12 the field12 to set
	 */
	public void setField12(String field12) {
		this.field12 = field12;
	}

	/**
	 * @return the field13
	 */
	public String getField13() {
		return this.field13;
	}
	
	/**
	 * @param field13 the field13 to set
	 */
	public void setField13(String field13) {
		this.field13 = field13;
	}

	/**
	 * @return the field14
	 */
	public Integer getField14() {
		return this.field14;
	}
	
	/**
	 * @param field14 the field14 to set
	 */
	public void setField14(Integer field14) {
		this.field14 = field14;
	}

	/**
	 * @return the field15
	 */
	public Integer getField15() {
		return this.field15;
	}
	
	/**
	 * @param field15 the field15 to set
	 */
	public void setField15(Integer field15) {
		this.field15 = field15;
	}

	/**
	 * @return the field16
	 */
	public Integer getField16() {
		return this.field16;
	}
	
	/**
	 * @param field16 the field16 to set
	 */
	public void setField16(Integer field16) {
		this.field16 = field16;
	}

	/**
	 * @return the field17
	 */
	public Integer getField17() {
		return this.field17;
	}
	
	/**
	 * @param field17 the field17 to set
	 */
	public void setField17(Integer field17) {
		this.field17 = field17;
	}

	/**
	 * @return the field18
	 */
	public Integer getField18() {
		return this.field18;
	}
	
	/**
	 * @param field18 the field18 to set
	 */
	public void setField18(Integer field18) {
		this.field18 = field18;
	}

	/**
	 * @return the field19
	 */
	public Integer getField19() {
		return this.field19;
	}
	
	/**
	 * @param field19 the field19 to set
	 */
	public void setField19(Integer field19) {
		this.field19 = field19;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return this.field2;
	}
	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String field2) {
		this.field2 = field2;
	}

	/**
	 * @return the field20
	 */
	public Integer getField20() {
		return this.field20;
	}
	
	/**
	 * @param field20 the field20 to set
	 */
	public void setField20(Integer field20) {
		this.field20 = field20;
	}

	/**
	 * @return the field21
	 */
	public Integer getField21() {
		return this.field21;
	}
	
	/**
	 * @param field21 the field21 to set
	 */
	public void setField21(Integer field21) {
		this.field21 = field21;
	}

	/**
	 * @return the field22
	 */
	public Integer getField22() {
		return this.field22;
	}
	
	/**
	 * @param field22 the field22 to set
	 */
	public void setField22(Integer field22) {
		this.field22 = field22;
	}

	/**
	 * @return the field23
	 */
	public Integer getField23() {
		return this.field23;
	}
	
	/**
	 * @param field23 the field23 to set
	 */
	public void setField23(Integer field23) {
		this.field23 = field23;
	}

	/**
	 * @return the field24
	 */
	public Integer getField24() {
		return this.field24;
	}
	
	/**
	 * @param field24 the field24 to set
	 */
	public void setField24(Integer field24) {
		this.field24 = field24;
	}

	/**
	 * @return the field25
	 */
	public Integer getField25() {
		return this.field25;
	}
	
	/**
	 * @param field25 the field25 to set
	 */
	public void setField25(Integer field25) {
		this.field25 = field25;
	}

	/**
	 * @return the field26
	 */
	public Integer getField26() {
		return this.field26;
	}
	
	/**
	 * @param field26 the field26 to set
	 */
	public void setField26(Integer field26) {
		this.field26 = field26;
	}

	/**
	 * @return the field27
	 */
	public Integer getField27() {
		return this.field27;
	}
	
	/**
	 * @param field27 the field27 to set
	 */
	public void setField27(Integer field27) {
		this.field27 = field27;
	}

	/**
	 * @return the field28
	 */
	public Integer getField28() {
		return this.field28;
	}
	
	/**
	 * @param field28 the field28 to set
	 */
	public void setField28(Integer field28) {
		this.field28 = field28;
	}

	/**
	 * @return the field29
	 */
	public Integer getField29() {
		return this.field29;
	}
	
	/**
	 * @param field29 the field29 to set
	 */
	public void setField29(Integer field29) {
		this.field29 = field29;
	}

	/**
	 * @return the field3
	 */
	public String getField3() {
		return this.field3;
	}
	
	/**
	 * @param field3 the field3 to set
	 */
	public void setField3(String field3) {
		this.field3 = field3;
	}

	/**
	 * @return the field30
	 */
	public Integer getField30() {
		return this.field30;
	}
	
	/**
	 * @param field30 the field30 to set
	 */
	public void setField30(Integer field30) {
		this.field30 = field30;
	}

	/**
	 * @return the field31
	 */
	public Integer getField31() {
		return this.field31;
	}
	
	/**
	 * @param field31 the field31 to set
	 */
	public void setField31(Integer field31) {
		this.field31 = field31;
	}

	/**
	 * @return the field32
	 */
	public String getField32() {
		return this.field32;
	}
	
	/**
	 * @param field32 the field32 to set
	 */
	public void setField32(String field32) {
		this.field32 = field32;
	}

	/**
	 * @return the field4
	 */
	public String getField4() {
		return this.field4;
	}
	
	/**
	 * @param field4 the field4 to set
	 */
	public void setField4(String field4) {
		this.field4 = field4;
	}

	/**
	 * @return the field5
	 */
	public String getField5() {
		return this.field5;
	}
	
	/**
	 * @param field5 the field5 to set
	 */
	public void setField5(String field5) {
		this.field5 = field5;
	}

	/**
	 * @return the field6
	 */
	public String getField6() {
		return this.field6;
	}
	
	/**
	 * @param field6 the field6 to set
	 */
	public void setField6(String field6) {
		this.field6 = field6;
	}

	/**
	 * @return the field7
	 */
	public String getField7() {
		return this.field7;
	}
	
	/**
	 * @param field7 the field7 to set
	 */
	public void setField7(String field7) {
		this.field7 = field7;
	}

	/**
	 * @return the field8
	 */
	public Integer getField8() {
		return this.field8;
	}
	
	/**
	 * @param field8 the field8 to set
	 */
	public void setField8(Integer field8) {
		this.field8 = field8;
	}

	/**
	 * @return the field9
	 */
	public String getField9() {
		return this.field9;
	}
	
	/**
	 * @param field9 the field9 to set
	 */
	public void setField9(String field9) {
		this.field9 = field9;
	}

	/**
	 * @return the int1
	 */
	public Integer getInt1() {
		return this.int1;
	}
	
	/**
	 * @param int1 the int1 to set
	 */
	public void setInt1(Integer int1) {
		this.int1 = int1;
	}

	/**
	 * @return the int2
	 */
	public Integer getInt2() {
		return this.int2;
	}
	
	/**
	 * @param int2 the int2 to set
	 */
	public void setInt2(Integer int2) {
		this.int2 = int2;
	}

	/**
	 * @return the int3
	 */
	public Integer getInt3() {
		return this.int3;
	}
	
	/**
	 * @param int3 the int3 to set
	 */
	public void setInt3(Integer int3) {
		this.int3 = int3;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the state
	 */
	public Integer getState() {
		return this.state;
	}
	
	/**
	 * @param state the state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/**
	 * @return the str2
	 */
	public String getStr2() {
		return this.str2;
	}
	
	/**
	 * @param str2 the str2 to set
	 */
	public void setStr2(String str2) {
		this.str2 = str2;
	}

	/**
	 * @return the str3
	 */
	public String getStr3() {
		return this.str3;
	}
	
	/**
	 * @param str3 the str3 to set
	 */
	public void setStr3(String str3) {
		this.str3 = str3;
	}

	/**
	 * @return the str4
	 */
	public String getStr4() {
		return this.str4;
	}
	
	/**
	 * @param str4 the str4 to set
	 */
	public void setStr4(String str4) {
		this.str4 = str4;
	}

	/**
	 * @return the str5
	 */
	public String getStr5() {
		return this.str5;
	}
	
	/**
	 * @param str5 the str5 to set
	 */
	public void setStr5(String str5) {
		this.str5 = str5;
	}

	/**
	 * @return the time1
	 */
	public Date getTime1() {
		return this.time1;
	}
	
	/**
	 * @param time1 the time1 to set
	 */
	public void setTime1(Date time1) {
		this.time1 = time1;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Cm803Object)) {
			return false;
		}
		Cm803Object other = (Cm803Object)o;
		if (null == this.cmobjId) {
			if (other.cmobjId != null)
				return false;
		} else if (!this.cmobjId.equals(other.cmobjId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cmobjId == null) ? 0 : cmobjId.hashCode());
		return result;
	}
	
}