package jetsennet.ips.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_ALARMCONTACTS
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_ALARMCONTACTS", keyGenerator = "guid")
public class IpsAlarmcontacts implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_ALARMOBJ_ID = "ALARMOBJ_ID";
	public static String PROP_ALARM_TYPE = "ALARM_TYPE";
	public static String PROP_EMAIL = "EMAIL";
	public static String PROP_IP = "IP";
	public static String PROP_NAME = "NAME";
	public static String PROP_PHONE = "PHONE";
	public static String PROP_STR_1 = "STR_1";
	public static String PROP_STR_2 = "STR_2";
	public static String PROP_STR_3 = "STR_3";
	public static String PROP_STR_4 = "STR_4";
	
	/**
	 * primary key field of alarmobjId
	 */
	@FieldMapping(columnName = "ALARMOBJ_ID", columnType = 12, primary = true)
	private String alarmobjId;
	@FieldMapping(columnName = "ALARM_TYPE", columnType = 4)
	private Integer alarmType;
	@FieldMapping(columnName = "EMAIL", columnType = 12)
	private String email;
	@FieldMapping(columnName = "IP", columnType = 12)
	private String ip;
	@FieldMapping(columnName = "NAME", columnType = 12)
	private String name;
	@FieldMapping(columnName = "PHONE", columnType = 12)
	private String phone;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	@FieldMapping(columnName = "STR_2", columnType = 12)
	private String str2;
	@FieldMapping(columnName = "STR_3", columnType = 12)
	private String str3;
	@FieldMapping(columnName = "STR_4", columnType = 12)
	private String str4;
	
	public IpsAlarmcontacts() {
		super();
	}

	public IpsAlarmcontacts(String alarmobjId) {
		this.alarmobjId = alarmobjId;
	}

	/**
	 * @return the alarmobjId
	 */
	public String getAlarmobjId() {
		return this.alarmobjId;
	}
	
	/**
	 * @param alarmobjId the alarmobjId to set
	 */
	public void setAlarmobjId(String alarmobjId) {
		this.alarmobjId = alarmobjId;
	}

	/**
	 * @return the alarmType
	 */
	public Integer getAlarmType() {
		return this.alarmType;
	}
	
	/**
	 * @param alarmType the alarmType to set
	 */
	public void setAlarmType(Integer alarmType) {
		this.alarmType = alarmType;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return this.email;
	}
	
	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the ip
	 */
	public String getIp() {
		return this.ip;
	}
	
	/**
	 * @param ip the ip to set
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the phone
	 */
	public String getPhone() {
		return this.phone;
	}
	
	/**
	 * @param phone the phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/**
	 * @return the str2
	 */
	public String getStr2() {
		return this.str2;
	}
	
	/**
	 * @param str2 the str2 to set
	 */
	public void setStr2(String str2) {
		this.str2 = str2;
	}

	/**
	 * @return the str3
	 */
	public String getStr3() {
		return this.str3;
	}
	
	/**
	 * @param str3 the str3 to set
	 */
	public void setStr3(String str3) {
		this.str3 = str3;
	}

	/**
	 * @return the str4
	 */
	public String getStr4() {
		return this.str4;
	}
	
	/**
	 * @param str4 the str4 to set
	 */
	public void setStr4(String str4) {
		this.str4 = str4;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsAlarmcontacts)) {
			return false;
		}
		IpsAlarmcontacts other = (IpsAlarmcontacts)o;
		if (null == this.alarmobjId) {
			if (other.alarmobjId != null)
				return false;
		} else if (!this.alarmobjId.equals(other.alarmobjId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((alarmobjId == null) ? 0 : alarmobjId.hashCode());
		return result;
	}
	
}