/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsCtrlword.java
 * 日 期：Mon Nov 17 14:01:05 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_CTRLWORD
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_CTRLWORD", keyGenerator = "uuid")
public class IpsCtrlword implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_CW_CODE = "CW_CODE";
	public static String PROP_CW_DESC = "CW_DESC";
	public static String PROP_CW_ID = "CW_ID";
	public static String PROP_CW_NAME = "CW_NAME";
	public static String PROP_CW_TYPE = "CW_TYPE";
	public static String PROP_STR_1 = "STR_1";
	
	/**
	 * primary key field of cwId
	 */
	@FieldMapping(columnName = "CW_ID", columnType = 12, primary = true)
	private String cwId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "CW_CODE", columnType = 12)
	private String cwCode;
	@FieldMapping(columnName = "CW_DESC", columnType = 12)
	private String cwDesc;
	@FieldMapping(columnName = "CW_NAME", columnType = 12)
	private String cwName;
	@FieldMapping(columnName = "CW_TYPE", columnType = 4)
	private Integer cwType;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	
	public IpsCtrlword() {
		super();
	}

	public IpsCtrlword(String cwId) {
		this.cwId = cwId;
	}

	public IpsCtrlword(Date createTime, Integer createUserid, String cwName, Integer cwType) {
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.cwName = cwName;
		this.cwType = cwType;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the cwCode
	 */
	public String getCwCode() {
		return this.cwCode;
	}
	
	/**
	 * @param cwCode the cwCode to set
	 */
	public void setCwCode(String cwCode) {
		this.cwCode = cwCode;
	}

	/**
	 * @return the cwDesc
	 */
	public String getCwDesc() {
		return this.cwDesc;
	}
	
	/**
	 * @param cwDesc the cwDesc to set
	 */
	public void setCwDesc(String cwDesc) {
		this.cwDesc = cwDesc;
	}

	/**
	 * @return the cwId
	 */
	public String getCwId() {
		return this.cwId;
	}
	
	/**
	 * @param cwId the cwId to set
	 */
	public void setCwId(String cwId) {
		this.cwId = cwId;
	}

	/**
	 * @return the cwName
	 */
	public String getCwName() {
		return this.cwName;
	}
	
	/**
	 * @param cwName the cwName to set
	 */
	public void setCwName(String cwName) {
		this.cwName = cwName;
	}

	/**
	 * @return the cwType
	 */
	public Integer getCwType() {
		return this.cwType;
	}
	
	/**
	 * @param cwType the cwType to set
	 */
	public void setCwType(Integer cwType) {
		this.cwType = cwType;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsCtrlword)) {
			return false;
		}
		IpsCtrlword other = (IpsCtrlword)o;
		if (null == this.cwId) {
			if (other.cwId != null)
				return false;
		} else if (!this.cwId.equals(other.cwId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cwId == null) ? 0 : cwId.hashCode());
		return result;
	}
	
}