/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsDslabeltousergroup.java
 * 日 期：Thu Oct 15 16:51:11 CST 2015
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_DSLABELTOUSERGROUP
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_DSLABELTOUSERGROUP", keyOrder = "dsLabelid,groupId", keyGenerator = "guid")
public class IpsDslabeltousergroup implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_DS_LABELID = "DS_LABELID";
	public static String PROP_GROUP_ID = "GROUP_ID";
	
	/**
	 * primary key field of dsLabelid
	 */
	@FieldMapping(columnName = "DS_LABELID", columnType = 12, primary = true)
	private String dsLabelid;
	/**
	 * primary key field of groupId
	 */
	@FieldMapping(columnName = "GROUP_ID", columnType = 2, primary = true)
	private Long groupId;
	
	public IpsDslabeltousergroup() {
		super();
	}

	public IpsDslabeltousergroup(String dsLabelid, Long groupId) {
		this.dsLabelid = dsLabelid;
		this.groupId = groupId;
	}

	/**
	 * @return the dsLabelid
	 */
	public String getDsLabelid() {
		return this.dsLabelid;
	}
	
	/**
	 * @param dsLabelid the dsLabelid to set
	 */
	public void setDsLabelid(String dsLabelid) {
		this.dsLabelid = dsLabelid;
	}

	/**
	 * @return the groupId
	 */
	public Long getGroupId() {
		return this.groupId;
	}
	
	/**
	 * @param groupId the groupId to set
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsDslabeltousergroup)) {
			return false;
		}
		IpsDslabeltousergroup other = (IpsDslabeltousergroup)o;
		if (null == this.dsLabelid) {
			if (other.dsLabelid != null)
				return false;
		} else if (!this.dsLabelid.equals(other.dsLabelid))
			return false;
		if (null == this.groupId) {
			if (other.groupId != null)
				return false;
		} else if (!this.groupId.equals(other.groupId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dsLabelid == null) ? 0 : dsLabelid.hashCode());
		result = prime * result + ((groupId == null) ? 0 : groupId.hashCode());
		return result;
	}
	
}