/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsDatasource.java
 * 日 期：Fri Apr 03 10:37:19 CST 2015
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_DATASOURCE
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_DATASOURCE", keyGenerator = "guid")
public class IpsDatasource implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_DB_TYPE = "DB_TYPE";
	public static String PROP_DS_CLASS = "DS_CLASS";
	public static String PROP_DS_DESC = "DS_DESC";
	public static String PROP_DS_ID = "DS_ID";
	public static String PROP_DS_NAME = "DS_NAME";
	public static String PROP_DS_PARAM = "DS_PARAM";
	public static String PROP_DS_TYPE = "DS_TYPE";
	public static String PROP_DS_UID = "DS_UID";
	public static String PROP_PARENT_ID = "PARENT_ID";
	public static String PROP_STATE = "STATE";
	public static String PROP_STR_1 = "STR_1";
	public static String PROP_STR_2 = "STR_2";
	public static String PROP_STR_3 = "STR_3";
	public static String PROP_UPDATE_TIME = "UPDATE_TIME";
	public static String PROP_UPDATE_USER = "UPDATE_USER";
	public static String PROP_UPDATE_USERID = "UPDATE_USERID";
	
	/**
	 * primary key field of dsId
	 */
	@FieldMapping(columnName = "DS_ID", columnType = 12, primary = true)
	private String dsId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "DB_TYPE", columnType = 12)
	private String dbType;
	@FieldMapping(columnName = "DS_CLASS", columnType = 4)
	private Integer dsClass;
	@FieldMapping(columnName = "DS_DESC", columnType = 12)
	private String dsDesc;
	@FieldMapping(columnName = "DS_NAME", columnType = 12)
	private String dsName;
	@FieldMapping(columnName = "DS_PARAM", columnType = 12)
	private String dsParam;
	@FieldMapping(columnName = "DS_TYPE", columnType = 4)
	private Integer dsType;
	@FieldMapping(columnName = "DS_UID", columnType = 12)
	private String dsUid;
	@FieldMapping(columnName = "PARENT_ID", columnType = 12)
	private String parentId;
	@FieldMapping(columnName = "STATE", columnType = 4)
	private Integer state;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	@FieldMapping(columnName = "STR_2", columnType = 12)
	private String str2;
	@FieldMapping(columnName = "STR_3", columnType = 12)
	private String str3;
	@FieldMapping(columnName = "UPDATE_TIME", columnType = 93)
	private Date updateTime;
	@FieldMapping(columnName = "UPDATE_USER", columnType = 12)
	private String updateUser;
	@FieldMapping(columnName = "UPDATE_USERID", columnType = 4)
	private Integer updateUserid;
	
	public IpsDatasource() {
		super();
	}

	public IpsDatasource(String dsId) {
		this.dsId = dsId;
	}

	public IpsDatasource(Date createTime, Integer createUserid, Integer dsClass, String dsName, String dsParam, Integer dsType, Integer state) {
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.dsClass = dsClass;
		this.dsName = dsName;
		this.dsParam = dsParam;
		this.dsType = dsType;
		this.state = state;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the dbType
	 */
	public String getDbType() {
		return this.dbType;
	}
	
	/**
	 * @param dbType the dbType to set
	 */
	public void setDbType(String dbType) {
		this.dbType = dbType;
	}

	/**
	 * @return the dsClass
	 */
	public Integer getDsClass() {
		return this.dsClass;
	}
	
	/**
	 * @param dsClass the dsClass to set
	 */
	public void setDsClass(Integer dsClass) {
		this.dsClass = dsClass;
	}

	/**
	 * @return the dsDesc
	 */
	public String getDsDesc() {
		return this.dsDesc;
	}
	
	/**
	 * @param dsDesc the dsDesc to set
	 */
	public void setDsDesc(String dsDesc) {
		this.dsDesc = dsDesc;
	}

	/**
	 * @return the dsId
	 */
	public String getDsId() {
		return this.dsId;
	}
	
	/**
	 * @param dsId the dsId to set
	 */
	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	/**
	 * @return the dsName
	 */
	public String getDsName() {
		return this.dsName;
	}
	
	/**
	 * @param dsName the dsName to set
	 */
	public void setDsName(String dsName) {
		this.dsName = dsName;
	}

	/**
	 * @return the dsParam
	 */
	public String getDsParam() {
		return this.dsParam;
	}
	
	/**
	 * @param dsParam the dsParam to set
	 */
	public void setDsParam(String dsParam) {
		this.dsParam = dsParam;
	}

	/**
	 * @return the dsType
	 */
	public Integer getDsType() {
		return this.dsType;
	}
	
	/**
	 * @param dsType the dsType to set
	 */
	public void setDsType(Integer dsType) {
		this.dsType = dsType;
	}

	/**
	 * @return the dsUid
	 */
	public String getDsUid() {
		return this.dsUid;
	}
	
	/**
	 * @param dsUid the dsUid to set
	 */
	public void setDsUid(String dsUid) {
		this.dsUid = dsUid;
	}

	/**
	 * @return the parentId
	 */
	public String getParentId() {
		return this.parentId;
	}
	
	/**
	 * @param parentId the parentId to set
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * @return the state
	 */
	public Integer getState() {
		return this.state;
	}
	
	/**
	 * @param state the state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/**
	 * @return the str2
	 */
	public String getStr2() {
		return this.str2;
	}
	
	/**
	 * @param str2 the str2 to set
	 */
	public void setStr2(String str2) {
		this.str2 = str2;
	}

	/**
	 * @return the str3
	 */
	public String getStr3() {
		return this.str3;
	}
	
	/**
	 * @param str3 the str3 to set
	 */
	public void setStr3(String str3) {
		this.str3 = str3;
	}

	/**
	 * @return the updateTime
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}
	
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * @return the updateUser
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}
	
	/**
	 * @param updateUser the updateUser to set
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * @return the updateUserid
	 */
	public Integer getUpdateUserid() {
		return this.updateUserid;
	}
	
	/**
	 * @param updateUserid the updateUserid to set
	 */
	public void setUpdateUserid(Integer updateUserid) {
		this.updateUserid = updateUserid;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsDatasource)) {
			return false;
		}
		IpsDatasource other = (IpsDatasource)o;
		if (null == this.dsId) {
			if (other.dsId != null)
				return false;
		} else if (!this.dsId.equals(other.dsId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dsId == null) ? 0 : dsId.hashCode());
		return result;
	}
	
}