/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsDevice.java
 * 日 期：Mon Nov 24 14:26:06 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_DEVICE
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_DEVICE", keyGenerator = "guid")
public class IpsDevice implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_ACT_ID = "ACT_ID";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_DEV_CODE = "DEV_CODE";
	public static String PROP_DEV_DESC = "DEV_DESC";
	public static String PROP_DEV_ID = "DEV_ID";
	public static String PROP_DEV_NAME = "DEV_NAME";
	public static String PROP_DEV_TYPE = "DEV_TYPE";
	public static String PROP_SERVICE_URL = "SERVICE_URL";
	public static String PROP_STATE = "STATE";
	public static String PROP_STR_1 = "STR_1";
	public static String PROP_STR_2 = "STR_2";
	public static String PROP_SYS_ID = "SYS_ID";
	public static String PROP_TASK_PARAM = "TASK_PARAM";
	public static String PROP_UPDATE_TIME = "UPDATE_TIME";
	public static String PROP_UPDATE_USER = "UPDATE_USER";
	public static String PROP_UPDATE_USERID = "UPDATE_USERID";
	
	/**
	 * primary key field of devId
	 */
	@FieldMapping(columnName = "DEV_ID", columnType = 12, primary = true)
	private String devId;
	@FieldMapping(columnName = "ACT_ID", columnType = 4)
	private Integer actId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "DEV_CODE", columnType = 12)
	private String devCode;
	@FieldMapping(columnName = "DEV_DESC", columnType = 12)
	private String devDesc;
	@FieldMapping(columnName = "DEV_NAME", columnType = 12)
	private String devName;
	@FieldMapping(columnName = "DEV_TYPE", columnType = 4)
	private Integer devType;
	@FieldMapping(columnName = "SERVICE_URL", columnType = 12)
	private String serviceUrl;
	@FieldMapping(columnName = "STATE", columnType = 4)
	private Integer state;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	@FieldMapping(columnName = "STR_2", columnType = 12)
	private String str2;
	@FieldMapping(columnName = "SYS_ID", columnType = 12)
	private String sysId;
	@FieldMapping(columnName = "TASK_PARAM", columnType = 12)
	private String taskParam;
	@FieldMapping(columnName = "UPDATE_TIME", columnType = 93)
	private Date updateTime;
	@FieldMapping(columnName = "UPDATE_USER", columnType = 12)
	private String updateUser;
	@FieldMapping(columnName = "UPDATE_USERID", columnType = 4)
	private Integer updateUserid;
	
	public IpsDevice() {
		super();
	}

	public IpsDevice(String devId) {
		this.devId = devId;
	}

	public IpsDevice(Date createTime, Integer createUserid, String devName, Integer devType, Integer state, String sysId) {
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.devName = devName;
		this.devType = devType;
		this.state = state;
		this.sysId = sysId;
	}

	/**
	 * @return the actId
	 */
	public Integer getActId() {
		return this.actId;
	}
	
	/**
	 * @param actId the actId to set
	 */
	public void setActId(Integer actId) {
		this.actId = actId;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the devCode
	 */
	public String getDevCode() {
		return this.devCode;
	}
	
	/**
	 * @param devCode the devCode to set
	 */
	public void setDevCode(String devCode) {
		this.devCode = devCode;
	}

	/**
	 * @return the devDesc
	 */
	public String getDevDesc() {
		return this.devDesc;
	}
	
	/**
	 * @param devDesc the devDesc to set
	 */
	public void setDevDesc(String devDesc) {
		this.devDesc = devDesc;
	}

	/**
	 * @return the devId
	 */
	public String getDevId() {
		return this.devId;
	}
	
	/**
	 * @param devId the devId to set
	 */
	public void setDevId(String devId) {
		this.devId = devId;
	}

	/**
	 * @return the devName
	 */
	public String getDevName() {
		return this.devName;
	}
	
	/**
	 * @param devName the devName to set
	 */
	public void setDevName(String devName) {
		this.devName = devName;
	}

	/**
	 * @return the devType
	 */
	public Integer getDevType() {
		return this.devType;
	}
	
	/**
	 * @param devType the devType to set
	 */
	public void setDevType(Integer devType) {
		this.devType = devType;
	}

	/**
	 * @return the serviceUrl
	 */
	public String getServiceUrl() {
		return this.serviceUrl;
	}
	
	/**
	 * @param serviceUrl the serviceUrl to set
	 */
	public void setServiceUrl(String serviceUrl) {
		this.serviceUrl = serviceUrl;
	}

	/**
	 * @return the state
	 */
	public Integer getState() {
		return this.state;
	}
	
	/**
	 * @param state the state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/**
	 * @return the str2
	 */
	public String getStr2() {
		return this.str2;
	}
	
	/**
	 * @param str2 the str2 to set
	 */
	public void setStr2(String str2) {
		this.str2 = str2;
	}

	/**
	 * @return the sysId
	 */
	public String getSysId() {
		return this.sysId;
	}
	
	/**
	 * @param sysId the sysId to set
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	/**
	 * @return the taskParam
	 */
	public String getTaskParam() {
		return this.taskParam;
	}
	
	/**
	 * @param taskParam the taskParam to set
	 */
	public void setTaskParam(String taskParam) {
		this.taskParam = taskParam;
	}

	/**
	 * @return the updateTime
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}
	
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * @return the updateUser
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}
	
	/**
	 * @param updateUser the updateUser to set
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * @return the updateUserid
	 */
	public Integer getUpdateUserid() {
		return this.updateUserid;
	}
	
	/**
	 * @param updateUserid the updateUserid to set
	 */
	public void setUpdateUserid(Integer updateUserid) {
		this.updateUserid = updateUserid;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsDevice)) {
			return false;
		}
		IpsDevice other = (IpsDevice)o;
		if (null == this.devId) {
			if (other.devId != null)
				return false;
		} else if (!this.devId.equals(other.devId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((devId == null) ? 0 : devId.hashCode());
		return result;
	}
	
}