/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsDatatouser.java
 * 日 期：Wed Nov 12 16:08:39 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_DATATOUSER
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_DATATOUSER", keyOrder = "dsId,userId", keyGenerator = "uuid")
public class IpsDatatouser implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_DS_ID = "DS_ID";
	public static String PROP_USER_ID = "USER_ID";
	
	/**
	 * primary key field of dsId
	 */
	@FieldMapping(columnName = "DS_ID", columnType = 12, primary = true)
	private String dsId;
	/**
	 * primary key field of userId
	 */
	@FieldMapping(columnName = "USER_ID", columnType = 2, primary = true)
	private Long userId;
	
	public IpsDatatouser() {
		super();
	}

	public IpsDatatouser(String dsId, Long userId) {
		this.dsId = dsId;
		this.userId = userId;
	}

	/**
	 * @return the dsId
	 */
	public String getDsId() {
		return this.dsId;
	}
	
	/**
	 * @param dsId the dsId to set
	 */
	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	/**
	 * @return the userId
	 */
	public Long getUserId() {
		return this.userId;
	}
	
	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsDatatouser)) {
			return false;
		}
		IpsDatatouser other = (IpsDatatouser)o;
		if (null == this.dsId) {
			if (other.dsId != null)
				return false;
		} else if (!this.dsId.equals(other.dsId))
			return false;
		if (null == this.userId) {
			if (other.userId != null)
				return false;
		} else if (!this.userId.equals(other.userId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dsId == null) ? 0 : dsId.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}
	
}