/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsDatatsourcelabel.java
 * 日 期：Thu May 21 09:58:27 CST 2015
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_DATATSOURCELABEL
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_DATATSOURCELABEL", keyGenerator = "guid")
public class IpsDatatsourcelabel implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CW_IDS = "CW_IDS";
	public static String PROP_DS_ID = "DS_ID";
	public static String PROP_ID = "ID";
	public static String PROP_LAYER = "LAYER";
	public static String PROP_TYPE = "TYPE";
	
	/**
	 * primary key field of id
	 */
	@FieldMapping(columnName = "ID", columnType = 12, primary = true)
	private String id;
	@FieldMapping(columnName = "CW_IDS", columnType = 12)
	private String cwIds;
	@FieldMapping(columnName = "DS_ID", columnType = 12)
	private String dsId;
	@FieldMapping(columnName = "LAYER", columnType = 2)
	private Integer layer;
	@FieldMapping(columnName = "TYPE", columnType = 2)
	private Integer type;
	
	public IpsDatatsourcelabel() {
		super();
	}

	public IpsDatatsourcelabel(String id) {
		this.id = id;
	}

	/**
	 * @return the cwIds
	 */
	public String getCwIds() {
		return this.cwIds;
	}
	
	/**
	 * @param cwIds the cwIds to set
	 */
	public void setCwIds(String cwIds) {
		this.cwIds = cwIds;
	}

	/**
	 * @return the dsId
	 */
	public String getDsId() {
		return this.dsId;
	}
	
	/**
	 * @param dsId the dsId to set
	 */
	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	/**
	 * @return the id
	 */
	public String getId() {
		return this.id;
	}
	
	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the layer
	 */
	public Integer getLayer() {
		return this.layer;
	}
	
	/**
	 * @param layer the layer to set
	 */
	public void setLayer(Integer layer) {
		this.layer = layer;
	}

	/**
	 * @return the type
	 */
	public Integer getType() {
		return this.type;
	}
	
	/**
	 * @param type the type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsDatatsourcelabel)) {
			return false;
		}
		IpsDatatsourcelabel other = (IpsDatatsourcelabel)o;
		if (null == this.id) {
			if (other.id != null)
				return false;
		} else if (!this.id.equals(other.id))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	
}