/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsGathterstat.java
 * 日 期：Thu Apr 16 18:50:51 CST 2015
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.sql.Timestamp;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_GATHTERSTAT
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_GATHTERSTAT", keyGenerator = "guid")
public class IpsGathterstat implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_AMOUNT = "AMOUNT";
	public static String PROP_PATH = "PATH";
	public static String PROP_STAT_ID = "STAT_ID";
	public static String PROP_STAT_TIME = "STAT_TIME";
	public static String PROP_TASK_ID = "TASK_ID";
	
	/**
	 * primary key field of statId
	 */
	@FieldMapping(columnName = "STAT_ID", columnType = 12, primary = true)
	private String statId;
	@FieldMapping(columnName = "AMOUNT", columnType = 2)
	private Double amount;
	@FieldMapping(columnName = "PATH", columnType = 12)
	private String path;
	@FieldMapping(columnName = "STAT_TIME", columnType = 93)
	private  Date statTime;
	@FieldMapping(columnName = "TASK_ID", columnType = 12)
	private String taskId;
	
	public IpsGathterstat() {
		super();
	}

	public IpsGathterstat(String statId) {
		this.statId = statId;
	}

	/**
	 * @return the amount
	 */
	public Double getAmount() {
		return this.amount;
	}
	
	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * @return the path
	 */
	public String getPath() {
		return this.path;
	}
	
	/**
	 * @param path the path to set
	 */
	public void setPath(String path) {
		this.path = path;
	}

	/**
	 * @return the statId
	 */
	public String getStatId() {
		return this.statId;
	}
	
	/**
	 * @param statId the statId to set
	 */
	public void setStatId(String statId) {
		this.statId = statId;
	}

	/**
	 * @return the statTime
	 */
	public  Date getStatTime() {
		return this.statTime;
	}
	
	/**
	 * @param statTime the statTime to set
	 */
	public void setStatTime( Date statTime) {
		this.statTime = statTime;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsGathterstat)) {
			return false;
		}
		IpsGathterstat other = (IpsGathterstat)o;
		if (null == this.statId) {
			if (other.statId != null)
				return false;
		} else if (!this.statId.equals(other.statId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((statId == null) ? 0 : statId.hashCode());
		return result;
	}
	
}