/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jcms.schema.IpsJob.java
 * 日 期：Sat Nov 08 11:50:57 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_JOB
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_JOB", keyGenerator = "guid")
public class IpsJob implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_JOB_DESC = "JOB_DESC";
	public static String PROP_JOB_ID = "JOB_ID";
	public static String PROP_JOB_NAME = "JOB_NAME";
	public static String PROP_UPDATE_TIME = "UPDATE_TIME";
	public static String PROP_UPDATE_USER = "UPDATE_USER";
	public static String PROP_UPDATE_USERID = "UPDATE_USERID";
	
	/**
	 * primary key field of jobId
	 */
	@FieldMapping(columnName = "JOB_ID", columnType = 12, primary = true)
	private String jobId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "JOB_DESC", columnType = 12)
	private String jobDesc;
	@FieldMapping(columnName = "JOB_NAME", columnType = 12)
	private String jobName;
	@FieldMapping(columnName = "UPDATE_TIME", columnType = 93)
	private Date updateTime;
	@FieldMapping(columnName = "UPDATE_USER", columnType = 12)
	private String updateUser;
	@FieldMapping(columnName = "UPDATE_USERID", columnType = 4)
	private Integer updateUserid;
	
	public IpsJob() {
		super();
	}

	public IpsJob(String jobId) {
		this.jobId = jobId;
	}

	public IpsJob(Date createTime, Integer createUserid, String jobName) {
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.jobName = jobName;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the jobDesc
	 */
	public String getJobDesc() {
		return this.jobDesc;
	}
	
	/**
	 * @param jobDesc the jobDesc to set
	 */
	public void setJobDesc(String jobDesc) {
		this.jobDesc = jobDesc;
	}

	/**
	 * @return the jobId
	 */
	public String getJobId() {
		return this.jobId;
	}
	
	/**
	 * @param jobId the jobId to set
	 */
	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	/**
	 * @return the jobName
	 */
	public String getJobName() {
		return this.jobName;
	}
	
	/**
	 * @param jobName the jobName to set
	 */
	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	/**
	 * @return the updateTime
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}
	
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * @return the updateUser
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}
	
	/**
	 * @param updateUser the updateUser to set
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * @return the updateUserid
	 */
	public Integer getUpdateUserid() {
		return this.updateUserid;
	}
	
	/**
	 * @param updateUserid the updateUserid to set
	 */
	public void setUpdateUserid(Integer updateUserid) {
		this.updateUserid = updateUserid;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsJob)) {
			return false;
		}
		IpsJob other = (IpsJob)o;
		if (null == this.jobId) {
			if (other.jobId != null)
				return false;
		} else if (!this.jobId.equals(other.jobId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((jobId == null) ? 0 : jobId.hashCode());
		return result;
	}
	
}