/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsOrder.java
 * 日 期：Thu Apr 02 20:23:21 CST 2015
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_ORDER
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_ORDER", keyGenerator = "guid")
public class IpsOrder implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_DS_ID = "DS_ID";
	public static String PROP_INT_1 = "INT_1";
	public static String PROP_NOTIFY_URL = "NOTIFY_URL";
	public static String PROP_ORDER_ID = "ORDER_ID";
	public static String PROP_ORDER_INFO = "ORDER_INFO";
	public static String PROP_ORDER_NAME = "ORDER_NAME";
	public static String PROP_ORDER_TYPE = "ORDER_TYPE";
	public static String PROP_ORDERUSER_ID = "ORDERUSER_ID";
	public static String PROP_STR_1 = "STR_1";
	public static String PROP_STR_2 = "STR_2";
	public static String PROP_EXEC_TIME = "EXEC_TIME";
	
	/**
	 * primary key field of orderId
	 */
	@FieldMapping(columnName = "ORDER_ID", columnType = 12, primary = true)
	private String orderId;
	@FieldMapping(columnName = "DS_ID", columnType = 12)
	private String dsId;
	@FieldMapping(columnName = "INT_1", columnType = 4)
	private Integer int1;
	@FieldMapping(columnName = "NOTIFY_URL", columnType = 12)
	private String notifyUrl;
	@FieldMapping(columnName = "ORDER_INFO", columnType = 12)
	private String orderInfo;
	@FieldMapping(columnName = "ORDER_NAME", columnType = 12)
	private String orderName;
	@FieldMapping(columnName = "ORDER_TYPE", columnType = 4)
	private Integer orderType;
	@FieldMapping(columnName = "ORDERUSER_ID", columnType = 4)
	private Integer orderuserId;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	@FieldMapping(columnName = "STR_2", columnType = 12)
	private String str2;
	@FieldMapping(columnName = "EXEC_TIME", columnType = 93)
	private Date execTime;
	
	public IpsOrder() {
		super();
	}

	public IpsOrder(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * @return the dsId
	 */
	public String getDsId() {
		return this.dsId;
	}
	
	/**
	 * @param dsId the dsId to set
	 */
	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	/**
	 * @return the int1
	 */
	public Integer getInt1() {
		return this.int1;
	}
	
	/**
	 * @param int1 the int1 to set
	 */
	public void setInt1(Integer int1) {
		this.int1 = int1;
	}

	/**
	 * @return the notifyUrl
	 */
	public String getNotifyUrl() {
		return this.notifyUrl;
	}
	
	/**
	 * @param notifyUrl the notifyUrl to set
	 */
	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl;
	}

	/**
	 * @return the orderId
	 */
	public String getOrderId() {
		return this.orderId;
	}
	
	/**
	 * @param orderId the orderId to set
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * @return the orderInfo
	 */
	public String getOrderInfo() {
		return this.orderInfo;
	}
	
	/**
	 * @param orderInfo the orderInfo to set
	 */
	public void setOrderInfo(String orderInfo) {
		this.orderInfo = orderInfo;
	}

	/**
	 * @return the orderName
	 */
	public String getOrderName() {
		return this.orderName;
	}
	
	/**
	 * @param orderName the orderName to set
	 */
	public void setOrderName(String orderName) {
		this.orderName = orderName;
	}

	/**
	 * @return the orderType
	 */
	public Integer getOrderType() {
		return this.orderType;
	}
	
	/**
	 * @param orderType the orderType to set
	 */
	public void setOrderType(Integer orderType) {
		this.orderType = orderType;
	}

	/**
	 * @return the orderuserId
	 */
	public Integer getOrderuserId() {
		return this.orderuserId;
	}
	
	/**
	 * @param orderuserId the orderuserId to set
	 */
	public void setOrderuserId(Integer orderuserId) {
		this.orderuserId = orderuserId;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/**
	 * @return the str2
	 */
	public String getStr2() {
		return this.str2;
	}
	
	/**
	 * @param str2 the str2 to set
	 */
	public void setStr2(String str2) {
		this.str2 = str2;
	}

	/**
	 * @return the execTime
	 */
	public Date getExecTime() {
		return execTime;
	}

	/**
	 * @param execTime the execTime to set
	 */
	public void setExecTime(Date execTime) {
		this.execTime = execTime;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsOrder)) {
			return false;
		}
		IpsOrder other = (IpsOrder)o;
		if (null == this.orderId) {
			if (other.orderId != null)
				return false;
		} else if (!this.orderId.equals(other.orderId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
		return result;
	}
	
}