/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsSystem.java
 * 日 期：Mon Nov 24 23:30:04 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_SYSTEM
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_SYSTEM", keyGenerator = "guid")
public class IpsSystem implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_BUS_TYPE = "BUS_TYPE";
	public static String PROP_CLASS_ID = "CLASS_ID";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_LOCATION = "LOCATION";
	public static String PROP_STATE = "STATE";
	public static String PROP_SYS_CODE = "SYS_CODE";
	public static String PROP_SYS_DESC = "SYS_DESC";
	public static String PROP_SYS_ID = "SYS_ID";
	public static String PROP_SYS_NAME = "SYS_NAME";
	public static String PROP_SYS_TYPE = "SYS_TYPE";
	public static String PROP_UNIT = "UNIT";
	public static String PROP_UPDATE_TIME = "UPDATE_TIME";
	public static String PROP_UPDATE_USER = "UPDATE_USER";
	public static String PROP_UPDATE_USERID = "UPDATE_USERID";
	
	/**
	 * primary key field of sysId
	 */
	@FieldMapping(columnName = "SYS_ID", columnType = 12, primary = true)
	private String sysId;
	@FieldMapping(columnName = "BUS_TYPE", columnType = 12)
	private String busType;
	@FieldMapping(columnName = "CLASS_ID", columnType = 12)
	private String classId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "LOCATION", columnType = 12)
	private String location;
	@FieldMapping(columnName = "STATE", columnType = 4)
	private Integer state;
	@FieldMapping(columnName = "SYS_CODE", columnType = 12)
	private String sysCode;
	@FieldMapping(columnName = "SYS_DESC", columnType = 12)
	private String sysDesc;
	@FieldMapping(columnName = "SYS_NAME", columnType = 12)
	private String sysName;
	@FieldMapping(columnName = "SYS_TYPE", columnType = 4)
	private Integer sysType;
	@FieldMapping(columnName = "UNIT", columnType = 12)
	private String unit;
	@FieldMapping(columnName = "UPDATE_TIME", columnType = 93)
	private Date updateTime;
	@FieldMapping(columnName = "UPDATE_USER", columnType = 12)
	private String updateUser;
	@FieldMapping(columnName = "UPDATE_USERID", columnType = 4)
	private Integer updateUserid;
	
	public IpsSystem() {
		super();
	}

	public IpsSystem(String sysId) {
		this.sysId = sysId;
	}

	public IpsSystem(Date createTime, Integer createUserid, Integer state, String sysName) {
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.state = state;
		this.sysName = sysName;
	}

	/**
	 * @return the busType
	 */
	public String getBusType() {
		return this.busType;
	}
	
	/**
	 * @param busType the busType to set
	 */
	public void setBusType(String busType) {
		this.busType = busType;
	}

	/**
	 * @return the classId
	 */
	public String getClassId() {
		return this.classId;
	}
	
	/**
	 * @param classId the classId to set
	 */
	public void setClassId(String classId) {
		this.classId = classId;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the location
	 */
	public String getLocation() {
		return this.location;
	}
	
	/**
	 * @param location the location to set
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * @return the state
	 */
	public Integer getState() {
		return this.state;
	}
	
	/**
	 * @param state the state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * @return the sysCode
	 */
	public String getSysCode() {
		return this.sysCode;
	}
	
	/**
	 * @param sysCode the sysCode to set
	 */
	public void setSysCode(String sysCode) {
		this.sysCode = sysCode;
	}

	/**
	 * @return the sysDesc
	 */
	public String getSysDesc() {
		return this.sysDesc;
	}
	
	/**
	 * @param sysDesc the sysDesc to set
	 */
	public void setSysDesc(String sysDesc) {
		this.sysDesc = sysDesc;
	}

	/**
	 * @return the sysId
	 */
	public String getSysId() {
		return this.sysId;
	}
	
	/**
	 * @param sysId the sysId to set
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	/**
	 * @return the sysName
	 */
	public String getSysName() {
		return this.sysName;
	}
	
	/**
	 * @param sysName the sysName to set
	 */
	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	/**
	 * @return the sysType
	 */
	public Integer getSysType() {
		return this.sysType;
	}
	
	/**
	 * @param sysType the sysType to set
	 */
	public void setSysType(Integer sysType) {
		this.sysType = sysType;
	}

	/**
	 * @return the unit
	 */
	public String getUnit() {
		return this.unit;
	}
	
	/**
	 * @param unit the unit to set
	 */
	public void setUnit(String unit) {
		this.unit = unit;
	}

	/**
	 * @return the updateTime
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}
	
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * @return the updateUser
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}
	
	/**
	 * @param updateUser the updateUser to set
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * @return the updateUserid
	 */
	public Integer getUpdateUserid() {
		return this.updateUserid;
	}
	
	/**
	 * @param updateUserid the updateUserid to set
	 */
	public void setUpdateUserid(Integer updateUserid) {
		this.updateUserid = updateUserid;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsSystem)) {
			return false;
		}
		IpsSystem other = (IpsSystem)o;
		if (null == this.sysId) {
			if (other.sysId != null)
				return false;
		} else if (!this.sysId.equals(other.sysId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((sysId == null) ? 0 : sysId.hashCode());
		return result;
	}
	
}