/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsTeminaloperationstat.java
 * 日 期：Mon Apr 20 10:54:24 CST 2015
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_TEMINALOPERATIONSTAT
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_TEMINALOPERATIONSTAT", keyGenerator = "guid")
public class IpsTeminaloperationstat implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_DATATYPE = "DATATYPE";
	public static String PROP_GROUP_CODE = "GROUP_CODE";
	public static String PROP_GROUP_ID = "GROUP_ID";
	public static String PROP_GROUP_NAME = "GROUP_NAME";
	public static String PROP_IP = "IP";
	public static String PROP_LOGIN_NAME = "LOGIN_NAME";
	public static String PROP_OPERATION = "OPERATION";
	public static String PROP_OPERATIONTIME = "OPERATIONTIME";
	public static String PROP_RECORDID = "RECORDID";
	public static String PROP_REPORTSID = "REPORTSID";
	public static String PROP_REPORTTIME = "REPORTTIME";
	public static String PROP_REPORTTITLE = "REPORTTITLE";
	public static String PROP_STAT_ID = "STAT_ID";
	public static String PROP_TABLENAME = "TABLENAME";
	public static String PROP_USER_ID = "USER_ID";
	public static String PROP_USER_NAME = "USER_NAME";
	
	/**
	 * primary key field of statId
	 */
	@FieldMapping(columnName = "STAT_ID", columnType = 12, primary = true)
	private String statId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "DATATYPE", columnType = 12)
	private String datatype;
	@FieldMapping(columnName = "GROUP_CODE", columnType = 12)
	private String groupCode;
	@FieldMapping(columnName = "GROUP_ID", columnType = 4)
	private Long groupId;
	@FieldMapping(columnName = "GROUP_NAME", columnType = 12)
	private String groupName;
	@FieldMapping(columnName = "IP", columnType = 12)
	private String ip;
	@FieldMapping(columnName = "LOGIN_NAME", columnType = 12)
	private String loginName;
	@FieldMapping(columnName = "OPERATION", columnType = 12)
	private String operation;
	@FieldMapping(columnName = "OPERATIONTIME", columnType = 93)
	private Date operationtime;
	@FieldMapping(columnName = "RECORDID", columnType = 12)
	private String recordid;
	@FieldMapping(columnName = "REPORTSID", columnType = 12)
	private String reportsid;
	@FieldMapping(columnName = "REPORTTIME", columnType = 93)
	private Date reporttime;
	@FieldMapping(columnName = "REPORTTITLE", columnType = 2005)
	private String reporttitle;
	@FieldMapping(columnName = "TABLENAME", columnType = 12)
	private String tablename;
	@FieldMapping(columnName = "USER_ID", columnType = 4)
	private Long userId;
	@FieldMapping(columnName = "USER_NAME", columnType = 12)
	private String userName;
	
	public IpsTeminaloperationstat() {
		super();
	}

	public IpsTeminaloperationstat(String statId) {
		this.statId = statId;
	}

	public IpsTeminaloperationstat(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the datatype
	 */
	public String getDatatype() {
		return this.datatype;
	}
	
	/**
	 * @param datatype the datatype to set
	 */
	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	/**
	 * @return the groupCode
	 */
	public String getGroupCode() {
		return this.groupCode;
	}
	
	/**
	 * @param groupCode the groupCode to set
	 */
	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode;
	}

	/**
	 * @return the groupId
	 */
	public Long getGroupId() {
		return this.groupId;
	}
	
	/**
	 * @param groupId the groupId to set
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * @return the groupName
	 */
	public String getGroupName() {
		return this.groupName;
	}
	
	/**
	 * @param groupName the groupName to set
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * @return the ip
	 */
	public String getIp() {
		return this.ip;
	}
	
	/**
	 * @param ip the ip to set
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * @return the loginName
	 */
	public String getLoginName() {
		return this.loginName;
	}
	
	/**
	 * @param loginName the loginName to set
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	/**
	 * @return the operation
	 */
	public String getOperation() {
		return this.operation;
	}
	
	/**
	 * @param operation the operation to set
	 */
	public void setOperation(String operation) {
		this.operation = operation;
	}

	/**
	 * @return the operationtime
	 */
	public Date getOperationtime() {
		return this.operationtime;
	}
	
	/**
	 * @param operationtime the operationtime to set
	 */
	public void setOperationtime(Date operationtime) {
		this.operationtime = operationtime;
	}

	/**
	 * @return the recordid
	 */
	public String getRecordid() {
		return this.recordid;
	}
	
	/**
	 * @param recordid the recordid to set
	 */
	public void setRecordid(String recordid) {
		this.recordid = recordid;
	}

	/**
	 * @return the reportsid
	 */
	public String getReportsid() {
		return this.reportsid;
	}
	
	/**
	 * @param reportsid the reportsid to set
	 */
	public void setReportsid(String reportsid) {
		this.reportsid = reportsid;
	}

	/**
	 * @return the reporttime
	 */
	public Date getReporttime() {
		return this.reporttime;
	}
	
	/**
	 * @param reporttime the reporttime to set
	 */
	public void setReporttime(Date reporttime) {
		this.reporttime = reporttime;
	}

	/**
	 * @return the reporttitle
	 */
	public String getReporttitle() {
		return this.reporttitle;
	}
	
	/**
	 * @param reporttitle the reporttitle to set
	 */
	public void setReporttitle(String reporttitle) {
		this.reporttitle = reporttitle;
	}

	/**
	 * @return the statId
	 */
	public String getStatId() {
		return this.statId;
	}
	
	/**
	 * @param statId the statId to set
	 */
	public void setStatId(String statId) {
		this.statId = statId;
	}

	/**
	 * @return the tablename
	 */
	public String getTablename() {
		return this.tablename;
	}
	
	/**
	 * @param tablename the tablename to set
	 */
	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	/**
	 * @return the userId
	 */
	public Long getUserId() {
		return this.userId;
	}
	
	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return this.userName;
	}
	
	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsTeminaloperationstat)) {
			return false;
		}
		IpsTeminaloperationstat other = (IpsTeminaloperationstat)o;
		if (null == this.statId) {
			if (other.statId != null)
				return false;
		} else if (!this.statId.equals(other.statId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((statId == null) ? 0 : statId.hashCode());
		return result;
	}
	
}