/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.ips.schema.IpsTask.java
 * 日 期：Thu Dec 18 10:38:54 CST 2014
 */
package jetsennet.ips.schema;

import java.io.Serializable;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * IPS_TASK
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "IPS_TASK", keyGenerator = "guid")
public class IpsTask implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CLASS_ID = "CLASS_ID";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_CREATE_USERID = "CREATE_USERID";
	public static String PROP_DS_ID = "DS_ID";
	public static String PROP_JOB_ID = "JOB_ID";
	public static String PROP_PROC_ID = "PROC_ID";
	public static String PROP_PROCTEMPLATE_ID = "PROCTEMPLATE_ID";
	public static String PROP_STR_1 = "STR_1";
	public static String PROP_STR_2 = "STR_2";
	public static String PROP_TASK_CODE = "TASK_CODE";
	public static String PROP_TASK_DESC = "TASK_DESC";
	public static String PROP_TASK_ID = "TASK_ID";
	public static String PROP_TASK_NAME = "TASK_NAME";
	public static String PROP_TASK_PARAM = "TASK_PARAM";
	public static String PROP_TASK_STATE = "TASK_STATE";
	public static String PROP_TASK_TYPE = "TASK_TYPE";
	public static String PROP_UPDATE_TIME = "UPDATE_TIME";
	public static String PROP_UPDATE_USER = "UPDATE_USER";
	public static String PROP_UPDATE_USERID = "UPDATE_USERID";
	
	/**
	 * primary key field of taskId
	 */
	@FieldMapping(columnName = "TASK_ID", columnType = 12, primary = true)
	private String taskId;
	@FieldMapping(columnName = "CLASS_ID", columnType = 12)
	private String classId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "CREATE_USERID", columnType = 4)
	private Integer createUserid;
	@FieldMapping(columnName = "DS_ID", columnType = 12)
	private String dsId;
	@FieldMapping(columnName = "JOB_ID", columnType = 12)
	private String jobId;
	@FieldMapping(columnName = "PROC_ID", columnType = 4)
	private Integer procId;
	@FieldMapping(columnName = "PROCTEMPLATE_ID", columnType = 12)
	private String proctemplateId;
	@FieldMapping(columnName = "STR_1", columnType = 12)
	private String str1;
	@FieldMapping(columnName = "STR_2", columnType = 12)
	private String str2;
	@FieldMapping(columnName = "TASK_CODE", columnType = 12)
	private String taskCode;
	@FieldMapping(columnName = "TASK_DESC", columnType = 12)
	private String taskDesc;
	@FieldMapping(columnName = "TASK_NAME", columnType = 12)
	private String taskName;
	@FieldMapping(columnName = "TASK_PARAM", columnType = 12)
	private String taskParam;
	@FieldMapping(columnName = "TASK_STATE", columnType = 4)
	private Integer taskState;
	@FieldMapping(columnName = "TASK_TYPE", columnType = 4)
	private Integer taskType;
	@FieldMapping(columnName = "UPDATE_TIME", columnType = 93)
	private Date updateTime;
	@FieldMapping(columnName = "UPDATE_USER", columnType = 12)
	private String updateUser;
	@FieldMapping(columnName = "UPDATE_USERID", columnType = 4)
	private Integer updateUserid;
	
	public IpsTask() {
		super();
	}

	public IpsTask(String taskId) {
		this.taskId = taskId;
	}

	public IpsTask(String classId, Date createTime, Integer createUserid, String taskName, Integer taskType) {
		this.classId = classId;
		this.createTime = createTime;
		this.createUserid = createUserid;
		this.taskName = taskName;
		this.taskType = taskType;
	}

	/**
	 * @return the classId
	 */
	public String getClassId() {
		return this.classId;
	}
	
	/**
	 * @param classId the classId to set
	 */
	public void setClassId(String classId) {
		this.classId = classId;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createUserid
	 */
	public Integer getCreateUserid() {
		return this.createUserid;
	}
	
	/**
	 * @param createUserid the createUserid to set
	 */
	public void setCreateUserid(Integer createUserid) {
		this.createUserid = createUserid;
	}

	/**
	 * @return the dsId
	 */
	public String getDsId() {
		return this.dsId;
	}
	
	/**
	 * @param dsId the dsId to set
	 */
	public void setDsId(String dsId) {
		this.dsId = dsId;
	}

	/**
	 * @return the jobId
	 */
	public String getJobId() {
		return this.jobId;
	}
	
	/**
	 * @param jobId the jobId to set
	 */
	public void setJobId(String jobId) {
		this.jobId = jobId;
	}

	/**
	 * @return the procId
	 */
	public Integer getProcId() {
		return this.procId;
	}
	
	/**
	 * @param procId the procId to set
	 */
	public void setProcId(Integer procId) {
		this.procId = procId;
	}

	/**
	 * @return the proctemplateId
	 */
	public String getProctemplateId() {
		return this.proctemplateId;
	}
	
	/**
	 * @param proctemplateId the proctemplateId to set
	 */
	public void setProctemplateId(String proctemplateId) {
		this.proctemplateId = proctemplateId;
	}

	/**
	 * @return the str1
	 */
	public String getStr1() {
		return this.str1;
	}
	
	/**
	 * @param str1 the str1 to set
	 */
	public void setStr1(String str1) {
		this.str1 = str1;
	}

	/**
	 * @return the str2
	 */
	public String getStr2() {
		return this.str2;
	}
	
	/**
	 * @param str2 the str2 to set
	 */
	public void setStr2(String str2) {
		this.str2 = str2;
	}

	/**
	 * @return the taskCode
	 */
	public String getTaskCode() {
		return this.taskCode;
	}
	
	/**
	 * @param taskCode the taskCode to set
	 */
	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	/**
	 * @return the taskDesc
	 */
	public String getTaskDesc() {
		return this.taskDesc;
	}
	
	/**
	 * @param taskDesc the taskDesc to set
	 */
	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	/**
	 * @return the taskName
	 */
	public String getTaskName() {
		return this.taskName;
	}
	
	/**
	 * @param taskName the taskName to set
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	/**
	 * @return the taskParam
	 */
	public String getTaskParam() {
		return this.taskParam;
	}
	
	/**
	 * @param taskParam the taskParam to set
	 */
	public void setTaskParam(String taskParam) {
		this.taskParam = taskParam;
	}

	/**
	 * @return the taskState
	 */
	public Integer getTaskState() {
		return this.taskState;
	}
	
	/**
	 * @param taskState the taskState to set
	 */
	public void setTaskState(Integer taskState) {
		this.taskState = taskState;
	}

	/**
	 * @return the taskType
	 */
	public Integer getTaskType() {
		return this.taskType;
	}
	
	/**
	 * @param taskType the taskType to set
	 */
	public void setTaskType(Integer taskType) {
		this.taskType = taskType;
	}

	/**
	 * @return the updateTime
	 */
	public Date getUpdateTime() {
		return this.updateTime;
	}
	
	/**
	 * @param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * @return the updateUser
	 */
	public String getUpdateUser() {
		return this.updateUser;
	}
	
	/**
	 * @param updateUser the updateUser to set
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * @return the updateUserid
	 */
	public Integer getUpdateUserid() {
		return this.updateUserid;
	}
	
	/**
	 * @param updateUserid the updateUserid to set
	 */
	public void setUpdateUserid(Integer updateUserid) {
		this.updateUserid = updateUserid;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof IpsTask)) {
			return false;
		}
		IpsTask other = (IpsTask)o;
		if (null == this.taskId) {
			if (other.taskId != null)
				return false;
		} else if (!this.taskId.equals(other.taskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}
	
}