
package tvnetwork.ips.ipssystemservice._1_0;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2015-03-30T15:12:23.098+08:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
 
public class IPSSystemServicePort_IPSSystemServiceSoap_Server{

    protected IPSSystemServicePort_IPSSystemServiceSoap_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new IPSSystemServiceSoapImpl();
        String address = "http://localhost:8080/test/services";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new IPSSystemServicePort_IPSSystemServiceSoap_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
