--======================================================================
--CMP_OBJTYPE
--======================================================================
CREATE TABLE CMP_OBJTYPE
(
	CMOBJ_TYPE	INT NOT NULL,
	TYPE_NAME	VARCHAR(50) NOT NULL,
	TYPE_DESC	VARCHAR(100),
	SCHEMA_NAME	VARCHAR(10) NOT NULL,
	HAS_FILE	INT NOT NULL,
	BASE_TABLE  VARCHAR(30) NOT NULL,
	CREATE_USER	VARCHAR(50),
	CREATE_USERID	INT,
	CREATE_TIME	DATE DEFAULT SYSDATE,
	CONSTRAINT P_CMP_OBJTYPE PRIMARY KEY (CMOBJ_TYPE) 
);


CREATE TABLE CMP_DATATABLE
(
	TABLE_NAME	VARCHAR(30) NOT NULL,
	VIEW_NAME	VARCHAR(30) NOT NULL,
	CMOBJ_TYPE  INT NOT NULL,
	TABLE_DESC  VARCHAR(100),
	POSITION    INT NOT NULL,
	TABLE_TYPE  INT NOT NULL,
	CONSTRAINT P_CMP_DATATABLE PRIMARY KEY (TABLE_NAME) 
);

CREATE TABLE CMP_DATAFIELD
(
	FIELD_NAME	VARCHAR(30) NOT NULL,
	VIEW_NAME	VARCHAR(30) NOT NULL,
	TABLE_NAME	VARCHAR(30) NOT NULL,
	DATA_TYPE	VARCHAR(30) NOT NULL,
	DATA_LENGTH	INT NOT NULL,
	IS_KEY	INT NOT NULL,
	NULLABLE 	INT NOT NULL,
	IS_INDEX   INT NOT NULL,
	CMOBJ_TYPE  INT NOT NULL,
	FIELD_DESC  VARCHAR(30),
	POSITION   INT NOT NULL,
	FIELD_TYPE INT NOT NULL,
	CONSTRAINT P_CMP_DATAFIELD PRIMARY KEY (TABLE_NAME, FIELD_NAME) 
);

CREATE TABLE CMP_DATAMAP
(
	TABLE_NAME	VARCHAR(30) NOT NULL,	
	FIELD_NAME	VARCHAR(30) NOT NULL,
	CMOBJ_TYPE  INT NOT NULL,
	MAP_TYPE INT,
	MAP_TABLE	VARCHAR(30) NOT NULL,	
	MAP_FIELD	VARCHAR(30) NOT NULL,
	CONSTRAINT P_CMP_DATAMAP PRIMARY KEY (TABLE_NAME, MAP_TABLE)	
);

CREATE TABLE CMP_UIVIEW
(
	VIEW_NAME VARCHAR(20) NOT NULL,
	VIEW_TYPE INT NOT NULL,		
	CMOBJ_TYPE  INT NOT NULL,
	VIEW_DESC	VARCHAR(100) ,
	VIEW_CONTENT 	Clob,
	CONSTRAINT P_CMP_UIVIEW PRIMARY KEY (VIEW_NAME) 
);


--======================================================================
--CMP_CTRLWORD
--======================================================================
CREATE TABLE CMP_CTRLWORD
(
	ID	VARCHAR(36) NOT NULL,
	CMOBJ_TYPE	INT,
	CW_LEVEL INT,
	CW_TYPE	INT NOT NULL,
	CW_NAME	VARCHAR(100),
	CW_CODE VARCHAR(30),
	CW_DESC	VARCHAR(200),
	CW_POS INT,	
	CREATE_USER VARCHAR(50),
	CREATE_USERID	INT,
	CREATE_TIME DATE DEFAULT SYSDATE,
	CONSTRAINT P_CMP_CTRLWORD PRIMARY KEY (ID) 
);
--======================================================================
--CMP_CTRLCLASS
--======================================================================
CREATE TABLE CMP_CTRLCLASS
(
	ID	VARCHAR(36) NOT NULL,	
	PARENT_ID	VARCHAR(36),
	CMOBJ_TYPE	INT NOT NULL,
	CLASS_TYPE	INT NOT NULL,
	CLASS_NAME	VARCHAR(100) NOT NULL,		
	CLASS_LAYER VARCHAR(30),
	CLASS_DESC	VARCHAR(100),
	VIEW_NAME	VARCHAR(300),		
	SUB_CLASSID	VARCHAR(36),
	CREATE_USER VARCHAR(50),
	CREATE_USERID	INT,
	CREATE_TIME DATE DEFAULT SYSDATE,	
	CONSTRAINT P_CMP_CTRLCLASS PRIMARY KEY (ID) 
);

--======================================================================
--CMP_SUBCLASS
--======================================================================
CREATE TABLE CMP_SUBCLASS
(
	ID	VARCHAR(36) NOT NULL,	
	TYPE	INT NOT NULL,
	PARENT_ID	VARCHAR(36),	
	LAYER INT NOT NULL,
	NAME	VARCHAR(100) NOT NULL,	
	DESCRIPTION	VARCHAR(200),
	VIEW_NAME	VARCHAR(200),			
	CONSTRAINT P_SUBCLASS PRIMARY KEY (ID) 
);
