--======================================================================
--MTC_SERVER
--======================================================================
CREATE TABLE MTC_SERVER
(
	SERVER_ID	Varchar(50) not null,
	SERVER_NAME	Varchar(50),
	HOST_IP		Varchar(50),
    HOST_PORT       int,
	HOST_NAME	Varchar(50),
	SERVER_TYPE	Int,
	SUB_TYPE	Int,
	SET_MODE	Int default 0,
	WORK_MODE	Int default 0,
	WORK_STATE	Int,
	STATE_DESC	Varchar(200),
	UPDATE_TIME	DATE DEFAULT SYSDATE,	
	CREATE_USER	Varchar(50),
	CREATE_TIME	DATE DEFAULT SYSDATE,	
	FIELD_1		Varchar(200),
	FIELD_2		Varchar(200),
    CONSTRAINT P_MTC_SERVER PRIMARY KEY (SERVER_ID)
);
--======================================================================
--MTC_SERVERLOG
--======================================================================
CREATE TABLE MTC_SERVERLOG
(
	LOG_ID		Varchar(50) not null,
	SERVER_ID	Varchar(50) not null,
	LOG_TYPE	Int,
	LOG_DESC	Varchar(500),
	START_TIME	DATE DEFAULT SYSDATE,	
	END_TIME	DATE,
	CREATE_USER	Varchar(50),
	FIELD_1		Varchar(100),
	FIELD_2		Varchar(100),
    CONSTRAINT P_MTC_SERVERLOG PRIMARY KEY (LOG_ID)
);
--======================================================================
--MTC_TASKEXEC
--======================================================================
CREATE TABLE MTC_TASKEXEC
(
	TASK_ID 	Varchar(40) not null,
	PARENT_ID	Varchar(50),
	PREV_TASKID	Varchar(50),
	MESSAGE_ID	Varchar(50),
	APP_OBJSOURCE	Varchar(20),
	APP_OBJTYPE	Int,
	APP_OBJID	Varchar(50),	
	TASK_NAME 	VarChar(300),
	TASK_TYPE 	Int,
	TASK_GROUP  Int,
	SUB_TYPE	Varchar(100),
	TASK_LEVEL	Int default 10,
	EXEC_MODE	Int default 0,
	TASK_XML	Varchar2(4000),
	TASK_STATE	Int default 0,
	TASK_PERCENT	Int default 0,
	STATE_DESC	Varchar(300),
	TASK_ACTOR	Varchar(50),
	TASK_WORKER	Varchar(50),
	NOTIFY_URL	Varchar(200),
	NOTIFY_TYPE	Int,
	CREATE_USER Varchar(50),
	CREATE_TIME DATE DEFAULT SYSDATE,	
	START_TIME	DATE,
	END_TIME	DATE,
	FIELD_1		Varchar(200),
	FIELD_2		Varchar(200),
	FIELD_3		Varchar(200),
	FIELD_4		Varchar(200),
	FIELD_5		Varchar(200),
    CONSTRAINT P_MTC_TASKEXEC PRIMARY KEY (TASK_ID)
);
CREATE INDEX IX_MTC_TASK_PRIORITY ON MTC_TASKEXEC (
   TASK_LEVEL  asc,CREATE_TIME asc
);
CREATE INDEX IX_MTC_TASK_PREV_TASK ON MTC_TASKEXEC (
   PREV_TASKID asc
);
--======================================================================
--MTC_TASKLOG
--======================================================================
CREATE TABLE MTC_TASKLOG
(
	TASK_ID 	Varchar(40) not null,
	PARENT_ID	Varchar(50),
	PREV_TASKID	Varchar(50),
	MESSAGE_ID	Varchar(50),
	APP_OBJSOURCE	Varchar(20),
	APP_OBJTYPE	Int,
	APP_OBJID	Varchar(50),	
	TASK_NAME 	VarChar(300),
	TASK_TYPE 	Int,
	TASK_GROUP  Int,
	SUB_TYPE	Varchar(100),
	TASK_LEVEL	Int default 10,
	EXEC_MODE	Int default 0,
	TASK_XML	Varchar2(4000),
	TASK_STATE	Int default 0,
	TASK_PERCENT	Int default 0,
	STATE_DESC	Varchar(300),
	TASK_ACTOR	Varchar(50),
	TASK_WORKER	Varchar(50),
	NOTIFY_URL	Varchar(200),
	NOTIFY_TYPE	Int,
	CREATE_USER Varchar(50),
	CREATE_TIME DATE DEFAULT SYSDATE,	
	START_TIME	DATE,
	END_TIME	DATE,
	FIELD_1		Varchar(200),
	FIELD_2		Varchar(200),
	FIELD_3		Varchar(200),
	FIELD_4		Varchar(200),
	FIELD_5		Varchar(200),
    CONSTRAINT P_MTC_TASKLOG PRIMARY KEY (TASK_ID)
);
CREATE INDEX IX_MTC_TASK_PARENT_ID ON MTC_TASKLOG (
   PARENT_ID         asc
);
CREATE INDEX IX_MTC_TASK_CREATE_TIME ON MTC_TASKLOG (
   CREATE_TIME         asc
);
--======================================================================
--MTC_TASKRESULT
--======================================================================
CREATE TABLE MTC_TASKRESULT
(
	RESULT_ID	Varchar(50) not null,
	TASK_ID		Varchar(50) not null,
	TASK_TYPE	Int,
	RESULT_XML	Varchar2(4000),
	CREATE_TIME DATE DEFAULT SYSDATE,	
	FIELD_1		Varchar(200),
	FIELD_2		Varchar(200),	
    CONSTRAINT P_MTC_TASKRESULT PRIMARY KEY (RESULT_ID)
);
CREATE INDEX IX_MTC_TASKRESULT_TASKID ON MTC_TASKRESULT (
   TASK_ID         asc
);

--======================================================================
--MTC_TASKNOTIFY
--======================================================================
CREATE TABLE MTC_TASKNOTIFY
(
	NOTIFY_ID	Varchar(50) not null,
	TASK_ID		Varchar(50) not null,
	NOTIFY_URL	varchar(300),
	NOTIFY_CONTENT	Varchar2(4000),
	CREATE_TIME DATE DEFAULT SYSDATE,	
    CONSTRAINT P_MTC_TASKNOTIFY PRIMARY KEY (NOTIFY_ID)
);
CREATE INDEX IX_MTC_TASKNOTIFY_TASKID ON MTC_TASKNOTIFY (
   TASK_ID         asc
);

--======================================================================
--MTC_FORMATTEMPLATE
--======================================================================
CREATE TABLE MTC_FORMATTEMPLATE
(
	FORMAT_ID	varchar(50) not null,
	FORMAT_NAME	varchar(50),
	FORMAT_VER	varchar(50),
	FORMAT_DATA	Varchar2(4000),
	FORMAT_TYPE	varchar(50),
	MODIFY_TIME Date,
	FIELD_1		varchar(100),
	FIELD_2		varchar(100),
	CONSTRAINT	P_MTC_FORMATTEMPLATE PRIMARY KEY (FORMAT_ID)
);


INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301, 23, -1, '任务类型', '2301', '媒体任务');

INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301001, 23, 2301, '未知任务', '0', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301002, 23, 2301, '磁盘迁移', '1', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301003, 23, 2301, 'MD5生成、验证', '20', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301004, 23, 2301, '磁盘文件删除', '30', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301005, 23, 2301, '磁盘文件剪切', '40', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301005, 23, 2301, '数据流磁带迁移', '100', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301006, 23, 2301,'磁带上载','101','媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301007, 23, 2301,'磁带下载','102','媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301008, 23, 2301, '转码任务', '200', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301009, 23, 2301, '打包任务', '201', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301010, 23, 2301, '素材剪辑', '210', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301011, 23, 2301, '码流剪辑', '211', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301012, 23, 2301, 'SDI信号收录', '300', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301013, 23, 2301, 'SDI信号播出', '301', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301014, 23, 2301, 'SDI信号实时预监', '302', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301015, 23, 2301, 'ts流ASI信号收录', '310', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301016, 23, 2301, 'ts流UDP信号收录', '320', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301017, 23, 2301, 'ts流UDP信号播出', '321', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301018, 23, 2301, 'ts流UDP信号实时预监', '322', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301019, 23, 2301, '技术审核', '400', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301020, 23, 2301, '关键帧提取', '401', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301021, 23, 2301, '视频水印添加', '450', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301022, 23, 2301, '视频水印检测', '451', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301023, 23, 2301, '音频水印添加', '460', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301024, 23, 2301, '音频水印检测', '461', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301025, 23, 2301, '特征提取', '500', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301026, 23, 2301, '特征检索', '501', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301027, 23, 2301, '图像特征提取', '510', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301028, 23, 2301, '台标检测', '520', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301029, 23, 2301, '挂角广告检测', '521', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301030, 23, 2301, '游动字幕检测', '522', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301031, 23, 2301, '错播检测', '523', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301032, 23, 2301, '字幕识别', '530', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301033, 23, 2301, '语音识别', '531', '媒体任务');
--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301034, 23, 2301, '图像特征检索', '52301', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301035, 23, 2301, '媒体信息提取', '212', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301036, 23, 2301, '媒体索引生成', '213', '媒体任务');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2301037, 23, 2301, '媒体文件比较', '220', '媒体任务');
