--======================================================================
--CM1_OBJECT
--======================================================================
CREATE TABLE CM1_OBJECT
(
	CMOBJ_ID varchar(50) NOT NULL,	
	PARENT_ID varchar(50),	
	ROOT_ID varchar(50),
	NAME VARCHAR(300) NOT NULL,
	CMOBJ_TYPE INT,
	KEY_WORDS VARCHAR(500),
	CONTENT VARCHAR(2000),
	DURATION INT,
	IN_POINT INT,
	ICON_PATH VARCHAR(500),
	STATE INT NOT NULL,		
	CREATE_USER VARCHAR(50) NOT NULL, 
	CREATE_USERID VARCHAR(50),
	CREATE_TIME DATE DEFAULT SYSDATE,
	UPDATE_USER VARCHAR(50) NOT NULL, 
	UPDATE_USERID VARCHAR(50),
	UPDATE_TIME DATE DEFAULT SYSDATE,
	STR_1		VARCHAR(500),
	STR_2		VARCHAR(500),
	STR_3		VARCHAR(500),
	STR_4		VARCHAR(500),
	STR_5		VARCHAR(500),
	INT_1		INT,
	INT_2		INT,	
	NUM_1		NUMERIC,
	NUM_2		NUMERIC,
	TIME_1		DATE,
	TIME_2		DATE,
	TIME_3		DATE,
	STR_6		VARCHAR(500),
	STR_7		VARCHAR(500),
	STR_8		VARCHAR(500),
	STR_9		VARCHAR(500),
	STR_10		VARCHAR(500),
	STR_11		VARCHAR(1000),
	STR_12		VARCHAR(1000),
	STR_13		VARCHAR(1000),
	STR_14		VARCHAR(1000),
	STR_15		VARCHAR(1000),
	INT_3		INT,
	INT_4		INT,	
	INT_5		INT,
	NUM_3		NUMERIC,
	NUM_4		NUMERIC,	
	NUM_5		NUMERIC,
	TIME_4		DATE,
	TIME_5		DATE
);


--======================================================================
--CM1_FILEGROUP
--======================================================================
CREATE TABLE CM1_FILEGROUP
(
	GROUP_ID	varchar(50) NOT NULL,
	CMOBJ_ID	varchar(50),
	GROUP_TYPE	INT,	
	IS_ONLINE	INT,
	IS_ARCHIVE  INT,
	CREATE_TIME DATE,
	CREATE_USER VARCHAR(50),
	CREATE_USERID  INT,
	STR_1		VARCHAR(500),
	STR_2		VARCHAR(500),
	STR_3		VARCHAR(500),
	STR_4		VARCHAR(500),
	STR_5		VARCHAR(500),
	INT_1		INT,
	INT_2		INT,	
	NUM_1		NUMERIC,
	NUM_2		NUMERIC,	
	STR_6		VARCHAR(500),
	STR_7		VARCHAR(500),
	STR_8		VARCHAR(500),
	STR_9		VARCHAR(500),
	STR_10		VARCHAR(500),
	STR_11		VARCHAR(1000),
	STR_12		VARCHAR(1000),
	STR_13		VARCHAR(1000),
	STR_14		VARCHAR(1000),
	STR_15		VARCHAR(1000),	
	INT_3		INT,
	INT_4		INT,	
	INT_5		INT,
	NUM_3		NUMERIC,
	NUM_4		NUMERIC,	
	NUM_5		NUMERIC,
	STR_16		VARCHAR(1000),
	STR_17		VARCHAR(1000),
	STR_18		VARCHAR(1000),
	STR_19		VARCHAR(1000),
	STR_20		VARCHAR(1000),
	CONSTRAINT P_CM1_FILEGROUP PRIMARY KEY (GROUP_ID) 
);
--======================================================================
--CM1_FILEITEM
--======================================================================
CREATE TABLE CM1_FILEITEM
(
	FILE_ID		varchar(50) NOT NULL,
	GROUP_ID	varchar(50),
	CMOBJ_ID	varchar(50),
	FILE_TYPE INT,
	SOURCE_PATH VARCHAR(500),
	SOURCE_FILENAME VARCHAR(500),
	DEST_PATH VARCHAR(500),
	DEST_FILENAME VARCHAR(500),
	FILE_SIZE VARCHAR(50),
	FILE_MD5 VARCHAR(200),	
	STR_1 VARCHAR(500),
	STR_2 VARCHAR(500),
	CONSTRAINT P_CM1_FILEITEM PRIMARY KEY (FILE_ID)
);

--======================================================================
--CM1_QCSEQUENCE
--======================================================================
CREATE TABLE CM1_QCSEQUENCE
(
	ID varchar(50) NOT NULL,
	CMOBJ_ID varchar(50) NOT NULL,
	GROUP_TYPE	INT,	
	IN_POINT INT,
	OUT_POINT INT,
	QC_TYPE VARCHAR(50),
	CHANNEL INT,
	DESCRIPTION VARCHAR(200),
	TYPE INT,
	STR_1 VARCHAR(500),
	STR_2 VARCHAR(500),
	CONSTRAINT P_CM1_QCSEQUENCE PRIMARY KEY (ID)
);

CREATE INDEX INDEX_CM1_QCSEQUENCE ON CM1_QCSEQUENCE (CMOBJ_ID ASC);

--INSERT INTO CMP_OBJTYPE(CMOBJ_TYPE,TYPE_NAME,TYPE_DESC,SCHEMA_NAME,HAS_FILE,BASE_TABLE,CREATE_USER,CREATE_USERID) VALUES ( 1 , '��Ƶ' , '��Ƶ��Ŀ' , 'CM1' , 0 , 'CM1_OBJECT' , '����Ա' , 1 );

commit;