 --受控词
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2001, 20, -1, '首页模板', '2001', '首页模板');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2002, 20, -1, '皮肤样式', '2002', '皮肤样式');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2001001, 20, 2001, '默认模板', 'default', '默认模板，不得删除！');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2002001, 20, 2002, '默认样式', 'blue', '默认样式，不得删除！');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2002002, 20, 2002, '老版样式', 'jsnet', '老版jsnet样式');
--15.10.21--uum.15.07.08
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2003, 20, -1, '分组类型', '2003', '分组类型');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2003001, 20, 2003, '部分', '0', '部分');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2003002, 20, 2003, '栏目', '1', '栏目');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2003003, 20, 2003, '分组', '2', '分组');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (2003004, 20, 2003, '频道', '3', '频道');

-- NET_SEQUENCE[uum]; 
--INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('NET_CTRLWORD',6.0);
INSERT INTO NET_SEQUENCE (TABLE_NAME, SERIAL_NUMBER) VALUES ('NET_CTRLWORD', 10000000);
INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('UUM_PERSON',2.0);
INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('UUM_ROLE',3.0);
INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('UUM_USER',3.0);
INSERT INTO NET_SEQUENCE(TABLE_NAME,SERIAL_NUMBER) VALUES('UUM_USERGROUP',5.0);
-- UUM_FUNCTION[uum];
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(11.0,0.0,'运维管理','img=systemmanage.png',0.0,'系统管理',0.0,9.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(115 AS Numeric(15, 0)), CAST(11 AS Numeric(15, 0)), '数据字典管理', 'jips/jipssystemweb/datadictionary.htm?width=screen.width&height=screen.height&img=dataclassmgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(2 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(114 AS Numeric(15, 0)), CAST(11 AS Numeric(15, 0)), '数据分类管理', 'jips/jipssystemweb/ctrlclass.htm?width=screen.width&height=screen.height&img=dataclassmgr.png', CAST(0 AS Numeric(2, 0)), '数据分类管理', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(111.0,11.0,'日志管理','img=logmanage.png',0.0,'日志管理',0.0,111.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(112.0,0.0,'统一用户管理','img=usermanage.png',0.0,'统一用户管理',0.0,112.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(113.0,11.0,'系统配置管理','img=configmanage.png',0.0,'系统配置管理',0.0,113.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(11350000 AS Numeric(15, 0)), CAST(113 AS Numeric(15, 0)), '数据源管理', 'jmtc/mtcsystemweb/sys/datasourcemanage.htm?width=800&height=600&img=sysparams.png', CAST(0 AS Numeric(2, 0)), '数据源管理', CAST(0 AS Numeric(2, 0)), CAST(1135 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.111E7,111.0,'登录日志管理','juum/jsystemmanageweb/loginlog.htm?img=loginlog.png',0.0,'登录日志管理',0.0,1111.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1110001E7,1.111E7,'导出','imp',0.0,'导出',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1110002E7,1.111E7,'查看','view',0.0,'查看',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.112E7,111.0,'操作日志管理','juum/jsystemmanageweb/operatorlog.htm?img=operatorlog.png',0.0,'操作日志管理',0.0,1112.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1120001E7,1.112E7,'导出','imp',0.0,'导出',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1120002E7,1.112E7,'查看','view',0.0,'查看',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.113E7,111.0,'系统日志管理','juum/jsystemmanageweb/errorlog.htm?img=errorlog.png',0.0,'系统日志管理',0.0,1113.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1130001E7,1.113E7,'导出','imp',0.0,'导出',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1130002E7,1.113E7,'查看','view',0.0,'查看',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.121E7,112.0,'用户管理','juum/juumsystemweb/user.htm?img=user.png',0.0,'用户管理',0.0,1121.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1210001E7,1.121E7,'编辑用户','edit?EditPassword',0.0,'编辑用户',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1210003E7,1.121E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1210004E7,1.121E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1210005E7,1.121E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.123E7,112.0,'分组管理','juum/juumsystemweb/usergroup.htm?img=usergroup.png',0.0,'分组管理',0.0,1123.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1230001E7,1.123E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1230002E7,1.123E7,'修改','edit',0.0,'修改',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1230003E7,1.123E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1230004E7,1.123E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.124E7,112.0,'角色管理','juum/juumsystemweb/userrole.htm?img=userrole.png',0.0,'用户管理系统',0.0,1124.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1240001E7,1.124E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1240002E7,1.124E7,'修改','edit',0.0,'修改',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1240003E7,1.124E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1240004E7,1.124E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.125E7,112.0,'功能管理','juum/juumsystemweb/function.htm?img=function.png',0.0,'系统功能管理',0.0,1125.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1250001E7,1.125E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1250002E7,1.125E7,'修改','edit',0.0,'修改',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1250003E7,1.125E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1250004E7,1.125E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.126E7,112.0,'在线用户','juum/juumsystemweb/onlineuser.htm?img=onlineuser.png&tip=new&tipcolor=red',0.0,'在线用户管理',0.0,1126.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1260001E7,1.126E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1260002E7,1.126E7,'修改','edit',0.0,'修改',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1260003E7,1.126E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1260004E7,1.126E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.131E7,113.0,'系统设置','juum/jsystemmanageweb/sysconfig.htm?img=sysconfig.png',0.0,'系统参数管理',0.0,1131.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1310001E7,1.131E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1310002E7,1.131E7,'修改','edit',0.0,'修改',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1310003E7,1.131E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1310004E7,1.131E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.132E7,113.0,'分类设置','juum/jsystemmanageweb/ctrlclass.htm?img=ctrlclass.png',0.0,'分类设置',0.0,1132.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1320001E7,1.132E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1320002E7,1.132E7,'修改','edit',0.0,'修改',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1320003E7,1.132E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1320004E7,1.132E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.133E7,113.0,'界面设置','juum/jsystemmanageweb/ctrlword.htm?img=ctrlword.png',0.0,'界面设置',0.0,1133.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1330001E7,1.133E7,'新增','append',0.0,'新增',1.0,1.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1330002E7,1.133E7,'修改','edit',0.0,'修改',1.0,2.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1330003E7,1.133E7,'删除','del',0.0,'删除',1.0,3.0,0.0,NULL,NULL,NULL,NULL);
INSERT INTO UUM_FUNCTION(ID,PARENT_ID,NAME,PARAM,STATE,DESCRIPTION,TYPE,VIEW_POS,VIEW_FLAG,IMAGES,OPEN_WIDTH,OPEN_HEIGHT,VTARGET) VALUES(1.1330004E7,1.133E7,'查看','view',0.0,'查看',1.0,4.0,0.0,NULL,NULL,NULL,NULL);
---- UUM_FUNCTION[mtc];
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(11340000 AS Numeric(15, 0)), CAST(113 AS Numeric(15, 0)), '系统配置', 'jmtc/mtcsystemweb/sys/systemmanage.htm?img=systemconfig.png', CAST(0 AS Numeric(2, 0)), '系统配置', CAST(0 AS Numeric(2, 0)), CAST(1134 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(11360000 AS Numeric(15, 0)), CAST(113 AS Numeric(15, 0)), '受控词设置', 'jmtc/mtcsystemweb/sys/ctrlword.htm?img=ctrlwordmanage.png&amp;syscode=22,23', CAST(0 AS Numeric(2, 0)), '受控词设置', CAST(0 AS Numeric(2, 0)), CAST(1134 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(14 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), '任务管理', '0011.png', CAST(0 AS Numeric(2, 0)), '指挥管理', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(142 AS Numeric(15, 0)), CAST(14 AS Numeric(15, 0)), '数据采集', 'jips/jipssystemweb/datacollection.htm?width=screen.width&height=screen.height&img=datacollection.png', CAST(0 AS Numeric(2, 0)), '数据采集', CAST(0 AS Numeric(2, 0)), CAST(142 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(141 AS Numeric(15, 0)), CAST(14 AS Numeric(15, 0)), '工作管理', 'jips/jipssystemweb/receivetask.htm?width=screen.width&height=screen.height&img=receivetask.png', CAST(0 AS Numeric(2, 0)), '领受任务', CAST(0 AS Numeric(2, 0)), CAST(141 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(143 AS Numeric(15, 0)), CAST(14 AS Numeric(15, 0)), '数据处理', 'jips/jipssystemweb/dataprocess.htm?width=screen.width&height=screen.height&img=dataprocess.png', CAST(0 AS Numeric(2, 0)), '数据处理', CAST(0 AS Numeric(2, 0)), CAST(143 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(144 AS Numeric(15, 0)), CAST(14 AS Numeric(15, 0)), '我的任务', 'jips/jipssystemweb/mytask.htm?width=screen.width&height=screen.height&img=mytask.png', CAST(0 AS Numeric(2, 0)), '我的任务', CAST(0 AS Numeric(2, 0)), CAST(144 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(16 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), '服务管理', '0011.png', CAST(0 AS Numeric(2, 0)), '服务管理', CAST(0 AS Numeric(2, 0)), CAST(3 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(164 AS Numeric(15, 0)), CAST(16 AS Numeric(15, 0)), '服务日志', 'jdma/jdmasystemweb/servicemonitor.htm?width=screen.width&height=screen.height&img=collectionsysmgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(164 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(161 AS Numeric(15, 0)), CAST(16 AS Numeric(15, 0)), '采集系统管理', 'jips/jipssystemweb/collecmanage.htm?width=screen.width&height=screen.height&img=collectionsysmgr.png', CAST(0 AS Numeric(2, 0)), '采集系统管理', CAST(0 AS Numeric(2, 0)), CAST(161 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(162 AS Numeric(15, 0)), CAST(16 AS Numeric(15, 0)), '能力系统管理', 'jdma/jdmasystemweb/listappsystem.htm?width=screen.width&height=screen.height&img=collectionsysmgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(162 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(163 AS Numeric(15, 0)), CAST(16 AS Numeric(15, 0)), '服务管理', 'jdma/jdmasystemweb/listwebservice.htm?width=screen.width&height=screen.height&img=collectionsysmgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(163 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(16301 AS Numeric(15, 0)), CAST(163 AS Numeric(15, 0)), 'WEB服务管理', 'jdma/jdmasystemweb/viewwebservice.htm?width=screen.width&height=screen.height&img=collectionsysmgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(1 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(15 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), '数据管理', '0011.png', CAST(0 AS Numeric(2, 0)), '数据管理', CAST(0 AS Numeric(2, 0)), CAST(2 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(151 AS Numeric(15, 0)), CAST(15 AS Numeric(15, 0)), '数据源管理', 'jips/jipssystemweb/datasourcemanage.htm?width=screen.width&height=screen.height&img=datasourcemgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(152 AS Numeric(15, 0)), CAST(15 AS Numeric(15, 0)), '消息订阅', 'jips/jipssystemweb/ordermanage.htm?width=screen.width&height=screen.height&img=datasourcemgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(2 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(153 AS Numeric(15, 0)), CAST(15 AS Numeric(15, 0)), '口令下载数据查看', 'jips/jipssystemweb/passDown.htm?width=screen.width&height=screen.height&img=datasourcemgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(3 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(154 AS Numeric(15, 0)), CAST(15 AS Numeric(15, 0)), '身份认证数据查看', 'jips/jipssystemweb/identification.htm?width=screen.width&height=screen.height&img=datasourcemgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(4 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(155 AS Numeric(15, 0)), CAST(15 AS Numeric(15, 0)), '告警联系人', 'jips/jipssystemweb/alarmcontact.htm?width=screen.width&height=screen.height&img=datasourcemgr.png', CAST(0 AS Numeric(2, 0)), '', CAST(0 AS Numeric(2, 0)), CAST(2 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(20 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), '内容管理', '', CAST(0 AS Numeric(2, 0)), '内容管理', CAST(0 AS Numeric(2, 0)), CAST(8 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(20001 AS Numeric(15, 0)), CAST(20 AS Numeric(15, 0)), '管理中心', '', CAST(0 AS Numeric(2, 0)), '管理中心', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(2000101 AS Numeric(15, 0)), CAST(20001 AS Numeric(15, 0)), '内容对象设计', '../jcmp-2.0/portal/design/cmpdbdesign.htm?img=mtcinfo.png', CAST(0 AS Numeric(2, 0)), '内容对象设计', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(2000102 AS Numeric(15, 0)), CAST(20001 AS Numeric(15, 0)), '视图设计', '../jcmp-2.0/portal/design/adddataview.htm?img=worker.png', CAST(0 AS Numeric(2, 0)), '视图设计', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(2000103 AS Numeric(15, 0)), CAST(20001 AS Numeric(15, 0)), '受控词管理', '../jcmp-2.0/portal/sys/ctrlword.htm?img=mtctaskmanager.png', CAST(0 AS Numeric(2, 0)), '受控词管理', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(2000104 AS Numeric(15, 0)), CAST(20001 AS Numeric(15, 0)), '分类管理', '../jcmp-2.0/portal/sys/ctrlclass.htm', CAST(0 AS Numeric(2, 0)), '分类管理', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(20002 AS Numeric(15, 0)), CAST(20 AS Numeric(15, 0)), '数据中心', '', CAST(0 AS Numeric(2, 0)), '数据中心', CAST(0 AS Numeric(2, 0)), CAST(2 AS Numeric(15, 0)), NULL, NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(2000201 AS Numeric(15, 0)), CAST(20002 AS Numeric(15, 0)), '检索、编目配置页', '../jcmp-2.0/portal/content/metapagecfg.htm', CAST(0 AS Numeric(2, 0)), '检索、编目配置页', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(2000202 AS Numeric(15, 0)), CAST(20002 AS Numeric(15, 0)), '元数据检索页', '../jcmp-2.0/portal/content/metasearch.htm', CAST(0 AS Numeric(2, 0)), '元数据检索页', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(2000203 AS Numeric(15, 0)), CAST(20002 AS Numeric(15, 0)), '元数据编目页', '../jcmp-2.0/portal/content/metacatalog.htm', CAST(0 AS Numeric(2, 0)), '元数据编目页', CAST(0 AS Numeric(2, 0)), CAST(1 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);

---- UUM_FUNCTION[mtc];
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(13 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), '调度管理', '0011.png', CAST(0 AS Numeric(2, 0)), '调度中心', CAST(0 AS Numeric(2, 0)), CAST(7 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(134 AS Numeric(15, 0)), CAST(13 AS Numeric(15, 0)), '任务管理', 'jmtc/mtcsystemweb/mtc/taskmanage.htm?img=mtctaskmanager.png', CAST(0 AS Numeric(2, 0)), '任务管理', CAST(0 AS Numeric(2, 0)), CAST(134 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(131 AS Numeric(15, 0)), CAST(13 AS Numeric(15, 0)), '总体概况', 'jmtc/mtcsystemweb/index.htm?img=mtcinfo.png', CAST(0 AS Numeric(2, 0)), '总体概况', CAST(0 AS Numeric(2, 0)), CAST(131 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(132 AS Numeric(15, 0)), CAST(13 AS Numeric(15, 0)), '执行器管理', 'jmtc/mtcsystemweb/mtc/worker.htm?img=worker.png', CAST(0 AS Numeric(2, 0)), '执行器管理', CAST(0 AS Numeric(2, 0)), CAST(132 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(136 AS Numeric(15, 0)), CAST(13 AS Numeric(15, 0)), '调度日志', 'jmtc/mtcsystemweb/systemlog.htm?img=syslog.png&amp;syscode=23', CAST(0 AS Numeric(2, 0)), '调度日志', CAST(0 AS Numeric(2, 0)), CAST(136 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(12 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), '工作流管理', '0011.png', CAST(0 AS Numeric(2, 0)), '工作流管理', CAST(0 AS Numeric(2, 0)), CAST(8 AS Numeric(15, 0)), CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(121 AS Numeric(15, 0)), CAST(12 AS Numeric(15, 0)), '流程配置', 'jmtc/mtcsystemweb/wfm/wfmconfig.htm?img=wfmconfig.png', CAST(0 AS Numeric(2, 0)), '流程配置', CAST(0 AS Numeric(2, 0)), CAST(121 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(122 AS Numeric(15, 0)), CAST(12 AS Numeric(15, 0)), '流程设计', 'jmtc/mtcsystemweb/wfm/wfmdesigner.htm?img=wfmdesigner.png', CAST(0 AS Numeric(2, 0)), '流程设计', CAST(0 AS Numeric(2, 0)), CAST(122 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(123 AS Numeric(15, 0)), CAST(12 AS Numeric(15, 0)), '流程监控', 'jmtc/mtcsystemweb/wfm/wfmmanage.htm?img=wfmmanage.png', CAST(0 AS Numeric(2, 0)), '流程监控', CAST(0 AS Numeric(2, 0)), CAST(123 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(124 AS Numeric(15, 0)), CAST(12 AS Numeric(15, 0)), '任务监控', 'jmtc/mtcsystemweb/wfm/taskmanage.htm?img=wfmtaskmanager.png', CAST(0 AS Numeric(2, 0)), '任务管理', CAST(0 AS Numeric(2, 0)), CAST(124 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES (CAST(126 AS Numeric(15, 0)), CAST(12 AS Numeric(15, 0)), '流程日志', 'jmtc/mtcsystemweb/systemlog.htm?img=syslog.png&amp;syscode=22', CAST(0 AS Numeric(2, 0)), '流程日志', CAST(0 AS Numeric(2, 0)), CAST(126 AS Numeric(15, 0)), NULL, NULL, 'screen.width', 'screen.width', NULL);


INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200, 0, '业务管理', '0011.png', 0, '业务管理', 0, 200, 0, NULL, NULL, NULL, NULL);

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200010, 200, '个人首页', 'jbds/person.html', 0, '', 0, 10, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200020, 200, '投稿情况查询', 'jbds/reportSearch2.html', 0, 'jbds/reportSearch.html', 0, 20, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200030, 200, '论文浏览', '', 0, '嵌第三方页面', 0, 30, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200040, 200, '消息发布', 'jbds/msgPublish.html', 0, '', 0, 40, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200050, 200, '最新论文标题', '', 0, '', 0, 50, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200060, 200, '个人首页', 'jbds/personChu.html', 0, '处领导个人首页', 0, 60, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200070, 200, '投稿情况查询', 'jbds/reportSearchNew.html', 0, '处领导投稿查询', 0, 70, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200080, 200, '个人首页', 'jbds/personJu.html', 0, '局领导个人首页', 0, 80, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200090, 200, '数据资源', 'jbds/reportSearchNew.html', 0, '局领导投稿情况查询', 0, 90, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200100, 200, '指挥', 'jbds/zhChu.html', 0, '处领导指挥', 0, 100, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200110, 200, '指挥', 'jbds/zhJu.html', 0, '局领导指挥', 0, 110, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200120, 200, '线路查询', 'jbds/lineSearchChu.html', 0, '处/局 领导线路查询', 0, 120, NULL, NULL, 'screen.width', 'screen.width', NULL);

-- UUM_ROLEAUTHORITY[uum];
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(12 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(13 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(14 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(15 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(16 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(20 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(111 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(112 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(113 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(114 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(115 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(121 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(122 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(123 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(124 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(126 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(131 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(132 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(134 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(136 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(141 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(142 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(143 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(144 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(151 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(152 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(153 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(154 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(161 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(162 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(163 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(164 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(16301 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(20001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(20002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11110000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11110001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11110002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11120000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11120001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11120002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11130000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11130001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11130002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11210000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11210001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11210003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11210004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11230000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11230001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11230002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11230003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11230004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11240000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11240001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11240002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11240003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11240004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11250000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11250001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11250002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11250003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11250004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11260000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11260001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11260002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11260003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11260004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11310000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11310001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11310002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11310003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11310004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11320000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11320001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11320002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11320003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11320004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11330000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11330001 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11330002 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11330003 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11330004 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11340000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11350000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(11360000 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(2000101 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(2000102 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(2000103 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(2000104 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(2000201 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(2000202 AS Numeric(15, 0)));
INSERT INTO UUM_ROLEAUTHORITY (ROLE_ID, FUNCTION_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(2000203 AS Numeric(15, 0)));
 -- UUM_ROLE[uum];
INSERT INTO UUM_ROLE (ID, NAME, DESCRIPTION, TYPE) VALUES (CAST(1 AS Numeric(15, 0)), '系统管理员', '系统管理员', CAST(0 AS Numeric(15, 0)));
INSERT INTO UUM_ROLE (ID, NAME, DESCRIPTION, TYPE) VALUES (CAST(2 AS Numeric(15, 0)), '普通用户', '普通用户', CAST(0 AS Numeric(15, 0)));

-- UUM_USERTOGROUP[uum];
INSERT INTO UUM_USERTOGROUP (USER_ID, GROUP_ID, USAGE_TYPE) VALUES (CAST(1 AS Numeric(15, 0)), CAST(1 AS Numeric(15, 0)), NULL);
INSERT INTO UUM_USERTOGROUP (USER_ID, GROUP_ID, USAGE_TYPE) VALUES (CAST(2 AS Numeric(15, 0)), CAST(2 AS Numeric(15, 0)), NULL);

-- UUM_USERTOROLE[uum];
INSERT INTO UUM_USERTOROLE (ROLE_ID, USER_ID) VALUES (CAST(1 AS Numeric(15, 0)), CAST(1 AS Numeric(15, 0)));
INSERT INTO UUM_USERTOROLE (ROLE_ID, USER_ID) VALUES (CAST(2 AS Numeric(15, 0)), CAST(2 AS Numeric(15, 0)));

-- UUM_USERGROUP[uum];
INSERT INTO UUM_USERGROUP(ID,PARENT_ID,NAME,TYPE,GROUP_CODE,DESCRIPTION,FOLDER_PATH,QUOTA_SIZE,QUOTA_USED,APP_PARAM,FIELD_1,FIELD_2) VALUES(1.0,0.0,'用户分组1',2.0,'用户分组1','用户分组1',NULL,NULL,NULL,NULL,'1101',NULL);
INSERT INTO UUM_USERGROUP(ID,PARENT_ID,NAME,TYPE,GROUP_CODE,DESCRIPTION,FOLDER_PATH,QUOTA_SIZE,QUOTA_USED,APP_PARAM,FIELD_1,FIELD_2) VALUES(2.0,0.0,'用户分组2',2.0,'用户分组2','用户分组2',NULL,NULL,NULL,NULL,'1101',NULL);
INSERT INTO UUM_USERGROUP(ID,PARENT_ID,NAME,TYPE,GROUP_CODE,DESCRIPTION,FOLDER_PATH,QUOTA_SIZE,QUOTA_USED,APP_PARAM,FIELD_1,FIELD_2) VALUES(3.0,0.0,'外部人员',2.0,'外部人员','外部人员',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO UUM_USERGROUP(ID,PARENT_ID,NAME,TYPE,GROUP_CODE,DESCRIPTION,FOLDER_PATH,QUOTA_SIZE,QUOTA_USED,APP_PARAM,FIELD_1,FIELD_2) VALUES(4.0,0.0,'内部人员',2.0,'内部人员','内部人员',NULL,NULL,NULL,NULL,NULL,NULL);

-- UUM_USER[uum];
INSERT INTO UUM_USER (ID, LOGIN_NAME, USER_NAME, PASSWORD, PERSON_ID, USER_TYPE, USER_CARD, RIGHT_LEVEL, HOME_PATH, EMAIL, SEX, ADDRESS, BIRTHDAY, OFFICE_PHONE, HOME_PHONE, MOBILE_PHONE, DUTY_TITLE, QUOTA_SIZE, QUOTA_USED, APP_PARAM, PHOTO_PATH, DESCRIPTION, STATE, FIELD_1, FIELD_2) VALUES (CAST(1 AS Numeric(15, 0)), 'admin', 'admin', 'C4CA4238A0B923820DCC509A6F75849B', NULL, NULL, NULL, CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<Param><PageTheme>blue</PageTheme><PageStyle>default</PageStyle></Param>', NULL, NULL, CAST(0 AS Numeric(2, 0)), NULL, NULL);
INSERT INTO UUM_USER (ID, LOGIN_NAME, USER_NAME, PASSWORD, PERSON_ID, USER_TYPE, USER_CARD, RIGHT_LEVEL, HOME_PATH, EMAIL, SEX, ADDRESS, BIRTHDAY, OFFICE_PHONE, HOME_PHONE, MOBILE_PHONE, DUTY_TITLE, QUOTA_SIZE, QUOTA_USED, APP_PARAM, PHOTO_PATH, DESCRIPTION, STATE, FIELD_1, FIELD_2) VALUES (CAST(2 AS Numeric(15, 0)), 'jetsennet', 'jetsennet', 'C4CA4238A0B923820DCC509A6F75849B', NULL, NULL, NULL, CAST(0 AS Numeric(15, 0)), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '<Param><PageTheme>blue</PageTheme><PageStyle>default</PageStyle></Param>', NULL, '捷成网络普通用户', CAST(0 AS Numeric(2, 0)), NULL, NULL);

-- IPS_CTRLCLASS[ips];
INSERT INTO IPS_CTRLCLASS (CLASS_ID, PARENT_ID, OBJ_TYPE, CLASS_TYPE, CLASS_NAME, CLASS_LAYER, CLASS_DESC, VIEW_NAME, SUB_CLASSID, CREATE_USER, STR_1) VALUES ('1', '0', 10, 10, '数据源分类', '-1', '123', NULL, NULL, NULL, NULL);
INSERT INTO IPS_CTRLCLASS (CLASS_ID, PARENT_ID, OBJ_TYPE, CLASS_TYPE, CLASS_NAME, CLASS_LAYER, CLASS_DESC, VIEW_NAME, SUB_CLASSID, CREATE_USER, STR_1) VALUES ('2', '0', 20, 20, '采集系统分类', '-1', NULL, NULL, NULL, NULL, NULL);

-- CMP_OBJTYPE[ips];
INSERT INTO CMP_OBJTYPE (CMOBJ_TYPE, TYPE_NAME, TYPE_DESC, SCHEMA_NAME, HAS_FILE, BASE_TABLE, CREATE_USER, CREATE_USERID, CREATE_TIME) VALUES (1, 'CM1', 'CM1', 'CM1', 0, 'CM1_OBJECT', 'ADMI', 1, NULL);
INSERT INTO CMP_OBJTYPE (CMOBJ_TYPE, TYPE_NAME, TYPE_DESC, SCHEMA_NAME, HAS_FILE, BASE_TABLE, CREATE_USER, CREATE_USERID, CREATE_TIME) VALUES (2, 'CM2', 'CM2', 'CM2', 0, 'CM2_OBJECT', 'ADMI', 1, NULL);

-- NET_CTRLWORD[ips];
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (3, 22, -1, '对象编号', '12', '内容管理对象');

INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (1306, 22, 12, '邮件', 'CM801', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (1307, 22, 12, '口令', 'CM802', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (1308, 22, 12, '认证', 'CM803', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (1309, 22, 12, '文件', 'CM810', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (1311, 22, 12, '文本', 'CM812', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (1201, 22, 12, 'CM1', 'CM1', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC) VALUES (1202, 22, 12, 'CM2', 'CM2', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC) VALUES (1312, 22, 12, '话音', 'CM808', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC) VALUES (1313, 22, 12, '传真', 'CM811', '');
INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC) VALUES (1314, 22, 12, 'IP', 'CM815', '');

--INSERT INTO NET_CTRLWORD (CW_ID,CW_SYS,CW_TYPE,CW_NAME,CW_CODE,CW_DESC)VALUES (10000, 22, -1, '数据权限', '10000', '数据权限类型');
--ALTER TABLE CM801_OBJTASK ADD FAIL_COUNT INT NOT NULL DEFAULT 0
