/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.jdma.schema.DmaWebservice.java
 * 日 期：Fri Dec 19 10:01:21 CST 2014
 */
package jetsennet.jdma.schema;

import java.io.Serializable;
import java.sql.Timestamp;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * DMA_WEBSERVICE
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "DMA_WEBSERVICE", keyGenerator = "guid")
public class DmaWebservice implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_INT_1 = "INT_1";
	public static String PROP_SERVICE_CODE = "SERVICE_CODE";
	public static String PROP_SERVICE_DESC = "SERVICE_DESC";
	public static String PROP_SERVICE_ID = "SERVICE_ID";
	public static String PROP_SERVICE_NAME = "SERVICE_NAME";
	public static String PROP_SERVICE_URL = "SERVICE_URL";
	public static String PROP_STATE = "STATE";
	public static String PROP_SYS_ID = "SYS_ID";
	public static String PROP_WSDL_PATH = "WSDL_PATH";
	
	/**
	 * primary key field of serviceId
	 */
	@FieldMapping(columnName = "SERVICE_ID", columnType = 12, primary = true)
	private String serviceId;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Timestamp createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "INT_1", columnType = 4)
	private Integer int1;
	@FieldMapping(columnName = "SERVICE_CODE", columnType = 12)
	private String serviceCode;
	@FieldMapping(columnName = "SERVICE_DESC", columnType = 12)
	private String serviceDesc;
	@FieldMapping(columnName = "SERVICE_NAME", columnType = 12)
	private String serviceName;
	@FieldMapping(columnName = "SERVICE_URL", columnType = 12)
	private String serviceUrl;
	@FieldMapping(columnName = "STATE", columnType = 4)
	private Integer state;
	@FieldMapping(columnName = "SYS_ID", columnType = 12)
	private String sysId;
	@FieldMapping(columnName = "WSDL_PATH", columnType = 12)
	private String wsdlPath;
	
	public DmaWebservice() {
		super();
	}

	public DmaWebservice(String serviceId) {
		this.serviceId = serviceId;
	}

	public DmaWebservice(Timestamp createTime, String sysId) {
		this.createTime = createTime;
		this.sysId = sysId;
	}

	/**
	 * @return the createTime
	 */
	public Timestamp getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the int1
	 */
	public Integer getInt1() {
		return this.int1;
	}
	
	/**
	 * @param int1 the int1 to set
	 */
	public void setInt1(Integer int1) {
		this.int1 = int1;
	}

	/**
	 * @return the serviceCode
	 */
	public String getServiceCode() {
		return this.serviceCode;
	}
	
	/**
	 * @param serviceCode the serviceCode to set
	 */
	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	/**
	 * @return the serviceDesc
	 */
	public String getServiceDesc() {
		return this.serviceDesc;
	}
	
	/**
	 * @param serviceDesc the serviceDesc to set
	 */
	public void setServiceDesc(String serviceDesc) {
		this.serviceDesc = serviceDesc;
	}

	/**
	 * @return the serviceId
	 */
	public String getServiceId() {
		return this.serviceId;
	}
	
	/**
	 * @param serviceId the serviceId to set
	 */
	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	/**
	 * @return the serviceName
	 */
	public String getServiceName() {
		return this.serviceName;
	}
	
	/**
	 * @param serviceName the serviceName to set
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	/**
	 * @return the serviceUrl
	 */
	public String getServiceUrl() {
		return this.serviceUrl;
	}
	
	/**
	 * @param serviceUrl the serviceUrl to set
	 */
	public void setServiceUrl(String serviceUrl) {
		this.serviceUrl = serviceUrl;
	}

	/**
	 * @return the state
	 */
	public Integer getState() {
		return this.state;
	}
	
	/**
	 * @param state the state to set
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * @return the sysId
	 */
	public String getSysId() {
		return this.sysId;
	}
	
	/**
	 * @param sysId the sysId to set
	 */
	public void setSysId(String sysId) {
		this.sysId = sysId;
	}

	/**
	 * @return the wsdlPath
	 */
	public String getWsdlPath() {
		return this.wsdlPath;
	}
	
	/**
	 * @param wsdlPath the wsdlPath to set
	 */
	public void setWsdlPath(String wsdlPath) {
		this.wsdlPath = wsdlPath;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof DmaWebservice)) {
			return false;
		}
		DmaWebservice other = (DmaWebservice)o;
		if (null == this.serviceId) {
			if (other.serviceId != null)
				return false;
		} else if (!this.serviceId.equals(other.serviceId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((serviceId == null) ? 0 : serviceId.hashCode());
		return result;
	}
	
}