var videoAudiosParamArray = [
		{"name":"视频检测","value":"Video","id":"0","type":"1","parentId":"-1"},  
		{"name":"黑场","value":"BlackFrame","id":"1","type":"1","parentId":"0","param":["YBit8","YBit10","Percent","Duration"]},  //1是视频  2是音频
		{"name":"彩帧","value":"ColorFrame","id":"2","type":"1","parentId":"0","param":["Percent","Duration"]},
		{"name":"彩条","value":"ColorBar","id":"12","type":"1","parentId":"0","param":["Duration"]},
		{"name":"静帧","value":"StaticFrame","id":"3","type":"1","parentId":"0","param":["DiffBit8","DiffBit10","Percent","Duration"]},
		{"name":"幅型","value":"Aspect","id":"4","type":"1","parentId":"0","param":["YBit8","YBit10","Percent","Duration"]},
		{"name":"YUV","value":"YUV","id":"5","type":"1","parentId":"0","param":["Y_Bit8","UV_Bit8","Y_Bit10","UV_Bit10","Percent","Duration"]},
		{"name":"RGB","value":"RGB","id":"6","type":"1","parentId":"0","param":["RGB_Bit8","RGB_Bit10","Percent","Duration"]},
		{"name":"电平","value":"Level","id":"7","type":"1","parentId":"0"},
		{"name":"白电平","value":"WhiteLevel","id":"8","type":"1","parentId":"7","param":["Y","Percent","Duration"]},
		{"name":"底电平","value":"BlackLevel","id":"9","type":"1","parentId":"7","param":["Y","Percent","Duration"]},
		{"name":"夹帧","value":"MixFrame","id":"10","type":"1","parentId":"0","param":["Duration"]},
		{"name":"花屏","value":"Mess","id":"11","type":"1","parentId":"0","param":["Block","Edge","Duration"]},
		
		{"name":"音频检测","value":"Audio","id":"100","type":"2","parentId":"-1"},
		{"name":"静音","value":"Silence","id":"113","type":"2","parentId":"100","param":["Level","Duration"]},
		{"name":"峰值","value":"PeakLevel","id":"101","type":"2","parentId":"100","param":["Level","Duration"]},
		{"name":"真峰值","value":"TruePeakLevel","id":"102","type":"2","parentId":"100","param":["Level","Duration"]},
		{"name":"响度","value":"Loudness","id":"103","type":"2","parentId":"100"},
		{"name":"平均响度","value":"AvgLoudness","id":"104","type":"2","parentId":"103","param":["AvgLoudness"]},
		{"name":"短时响度","value":"ShtLoudness","id":"105","type":"2","parentId":"103","param":["Level","Duration"]},
		{"name":"瞬时响度","value":"MomLoudness","id":"114","type":"2","parentId":"103","param":["Level","Duration"]},
		{"name":"立体声相位","value":"StereoCorrelation","id":"106","type":"2","parentId":"100"},
		{"name":"完全反向","value":"InvertPhase","id":"107","type":"2","parentId":"106","param":["Duration"]},
		{"name":"完全同向","value":"SamePhase","id":"108","type":"2","parentId":"106","param":["Percent"]},
		{"name":"左右声道相关性","value":"StereoRelation","id":"109","type":"2","parentId":"100"},
		{"name":"负相关","value":"NegRelation","id":"110","type":"2","parentId":"109","param":["Threshold","Duration"]},
		{"name":"正相关","value":"PosRelation","id":"111","type":"2","parentId":"109","param":["Threshold","Duration"]},
		{"name":"不相关","value":"UnRelation","id":"112","type":"2","parentId":"109","param":["UnRelation","Duration"]}                       
	];


var videoAudiosIdParamArray = [{"name":"YBit8","showName":"亮度阀值_8bit","defaultValue":"18","type":"input","maxValue":"20","minValue":"16"},
                               {"name":"YBit10","showName":"亮度阀值_10bit","defaultValue":"72","type":"input","maxValue":"84","minValue":"60"},
                               {"name":"DiffBit8","showName":"亮度阀值_8bit","defaultValue":"6","type":"input","maxValue":"8","minValue":"4"},
                               {"name":"DiffBit10","showName":"亮度阀值_10bit","defaultValue":"24","type":"input","maxValue":"30","minValue":"18"},
                               {"name":"Percent","showName":"比例","defaultValue":"99.7","type":"input","maxValue":"100","minValue":"99.5"},
                               {"name":"Duration","showName":"时长","defaultValue":"1","type":"input","unit":"帧","maxValue":"100","minValue":"1"},
                               {"name":"Y_Bit8","showName":"Y_8bit","defaultValue":"13,242","type":"range"},
                               {"name":"UV_Bit8","showName":"UV_8bit","defaultValue":"16,240","type":"range"},
                               {"name":"Y_Bit10","showName":"Y_10bit","defaultValue":"52,968","type":"range"},
                               {"name":"UV_Bit10","showName":"UV_10bit","defaultValue":"64,960","type":"range"},
                               {"name":"RGB_Bit8","showName":"RGB_8bit","unit":"mv","defaultValue":"0,255","type":"range"},
                               {"name":"RGB_Bit10","showName":"RGB_10bit","unit":"mv","defaultValue":"0,1023","type":"range"},
                               {"name":"Y","showName":"阀值","defaultValue":"50","unit":"mv","type":"input"},
                               {"name":"Block","showName":"马赛克数量","defaultValue":"2","type":"input","maxValue":"1000","minValue":"1"},
                               {"name":"Edge","showName":"马赛克大小","defaultValue":"8","type":"input","maxValue":"128","minValue":"8"},
                               {"name":"Level","showName":"幅度阀值","defaultValue":"-60","unit":"dBFS","type":"input","maxValue":"-60","minValue":"-80"},
                               {"name":"AvgLoudness","showName":"响度范围","defaultValue":"-26,-22","unit":"LKFS","type":"range","maxValue":"-22","minValue":"-26"},
                               {"name":"Threshold","showName":"反向阈值","defaultValue":"-0","type":"input"},
                               {"name":"UnRelation","showName":"不相关范围","defaultValue":"-0.1,0.1","type":"range","maxValue":"1","minValue":"-1"},
                              ];


var mxfParamArray = [{"name":"文件封装检测","value":"FileFormatCheck","id":"0","type":"10","parentId":"-1"},  
                     		{"name":"Run In检测","value":"RunIn","id":"1","type":"10","parentId":"0","param":[],"enable":"enable"},  //10 文件封装 11 DNxHD检测 12AVC Intra 13 Mpeg2 LongGop
                     		{"name":"KLV结构检测","value":"KLVStruct","id":"2","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"KLV序列连续性","value":"KLVStruct1","id":"3","type":"10","parentId":"2","param":[],"enable":"enable"},
                     		{"name":"KLV数据结构的完整性","value":"KLVStruct2","id":"4","type":"10","parentId":"2","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Fill Item检测","value":"FileItem","id":"5","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Fill Item版本检测","value":"FileItem1","id":"6","type":"10","parentId":"5","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"多个相邻的Fill Item序列检测","value":"FileItem2","id":"7","type":"10","parentId":"5","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Partition结构检测","value":"PartitionStruct","id":"8","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Partition位置检测","value":"PartitionStruct1","id":"9","type":"10","parentId":"8","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Partition个数检测","value":"PartitionStruct2","id":"10","type":"10","parentId":"8","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Header Partition状态检测","value":"PartitionStruct3","id":"11","type":"10","parentId":"8","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Footer Partition状态检测","value":"PartitionStruct4","id":"12","type":"10","parentId":"8","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"操作模式(Operational Pattern)检测","value":"OperationalPattern","id":"13","type":"10","parentId":"0","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"OP1a Essence Container Label值检测","value":"EssenceContainerLabel","id":"14","type":"10","parentId":"0","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Partition Pack属性值检测","value":"PartitionPack","id":"15","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"KAGSize","value":"PartitionPack1","id":"16","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Major Version存在性检测","value":"PartitionPack2","id":"17","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Major Version值检测","value":"PartitionPack3","id":"18","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Minor Version存在性检测","value":"PartitionPack4","id":"19","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Minor Version值检测","value":"PartitionPack5","id":"20","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"ThisPartition","value":"PartitionPack6","id":"21","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"PreviousPartition","value":"PartitionPack7","id":"22","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"FooterPartition","value":"PartitionPack8","id":"23","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"HeaderByteCount","value":"PartitionPack9","id":"24","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"IndexByteCount","value":"PartitionPack10","id":"25","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"IndexSID","value":"PartitionPack11","id":"26","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"BodyOffset","value":"PartitionPack12","id":"27","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"BodySID","value":"PartitionPack13","id":"28","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Operational Pattern","value":"PartitionPack14","id":"29","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"EssenceContainers","value":"PartitionPack15","id":"30","type":"10","parentId":"15","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Random Index Pack检测","value":"RandomIndexPack","id":"31","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Random Index Pack位置检测","value":"RandomIndexPack1","id":"32","type":"10","parentId":"31","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Random Index Pack内容检测","value":"RandomIndexPack2","id":"33","type":"10","parentId":"31","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"EssenceContainer位置检测","value":"EssenceContainerPos","id":"34","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"HeaderMetaData位置检测","value":"HeaderMetaData","id":"35","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Header Meta Set的Instance UID唯一性检测","value":"HeaderMetaSet","id":"37","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"各个Header Meta Set间的引用关系检测","value":"HeaderMetaSet1","id":"38","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Primer Pack：位置检测","value":"PrimerPack","id":"39","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Primer Pack：Local Tag存在性检测","value":"PrimerPack1","id":"40","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Primer Pack：Local Tag唯一性检测","value":"PrimerPack2","id":"41","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：Instance UID(Required)","value":"PrefaceSet","id":"42","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：Last Modified Date(Required)","value":"PrefaceSet1","id":"43","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：Version (Required)存在性检测","value":"PrefaceSet2","id":"44","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：Version (Required)值检测","value":"PrefaceSet3","id":"45","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：Identifications(Encoder required)","value":"PrefaceSet4","id":"46","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：Content Storage(Required)","value":"PrefaceSet5","id":"47","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：Operational Pattern(Requried)","value":"PrefaceSet6","id":"48","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：EssenceContainers(Requried)","value":"PrefaceSet7","id":"49","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Preface Set：DM Schemes(Requried)","value":"PrefaceSet8","id":"50","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Identification：InstanceUID(Required)","value":"Identification","id":"51","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Identification：This Generation UID(Required)","value":"Identification1","id":"52","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Identification：Company Name(Required)","value":"Identification2","id":"53","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Identification：Product Name(Required)","value":"Identification3","id":"54","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Identification：Version String(Required)","value":"Identification4","id":"55","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Identification：Product UID(Required)","value":"Identification5","id":"56","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Identification：Modification Date(Required)","value":"Identification6","id":"57","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Content Storage Set：Instance UID(Required)","value":"ContentStorage","id":"58","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Content Storage Set：Packages(Required)","value":"ContentStorage1","id":"59","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Content Storage Set：EssenceContainer Data(Optional)","value":"ContentStorage2","id":"60","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Essence Container Data Set：Instance UID(Required)","value":"EssenceContainerDataSet","id":"61","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Essence Container Data Set：Linked Package UID(Requried)","value":"EssenceContainerDataSet1","id":"62","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Essence Container Data Set：BodySID(Required)","value":"EssenceContainerDataSet2","id":"63","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Material Package Set：Instance UID(Requried)","value":"MaterialPackageSet","id":"64","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Material Package Set：Package UID(Required)","value":"MaterialPackageSet1","id":"65","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Material Package Set：Package Creation Date(Required)","value":"MaterialPackageSet2","id":"66","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Material Package Set：Package Modified Date(Required)","value":"MaterialPackageSet3","id":"67","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Material Package Set：Tracks(Required)","value":"MaterialPackageSet4","id":"68","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"File Package Set：Instance UID(Requried)","value":"FilePackageSet","id":"69","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"File Package Set：Package UID(Required)","value":"FilePackageSet1","id":"70","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"File Package Set：Package Creation Date(Required)","value":"FilePackageSet2","id":"71","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"File Package Set：Package Modified Date(Required)","value":"FilePackageSet3","id":"72","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"File Package Set：Tracks(Required)","value":"FilePackageSet4","id":"73","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"File Package Set：Descriptor(Requried)","value":"FilePackageSet5","id":"74","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Track Set：Instance UID(Required)","value":"TrackSet","id":"75","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Track Set：Track ID(Required)","value":"TrackSet1","id":"76","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Track Set：Track Number(Requried)","value":"TrackSet2","id":"77","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Track Set：Edit Rate(Requried)","value":"TrackSet3","id":"78","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Track Set：Origin(Required)","value":"TrackSet4","id":"79","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Track Set：Sequence(Required)","value":"TrackSet5","id":"80","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sequence Set：Instance UID(Required)","value":"SequenceSet","id":"81","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sequence Set：Data Definition(Required)","value":"SequenceSet1","id":"82","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sequence Set：Duration(Best Effort)","value":"SequenceSet2","id":"83","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sequence Set：Components(Required)","value":"SequenceSet3","id":"84","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Source Clip Set：Instance UID(Required)","value":"SourceClipSet","id":"85","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Source Clip Set：Data Definition(Required)","value":"SourceClipSet1","id":"86","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Source Clip Set：Duration(Best.Effort)","value":"SourceClipSet2","id":"87","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Source Clip Set：Start Position(Required)","value":"SourceClipSet3","id":"88","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Source Clip Set：Source Package ID(Required)","value":"SourceClipSet4","id":"89","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Source Clip Set：Source Track ID(Required)","value":"SourceClipSet5","id":"90","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Timecode Component Set：Instance UID(Required)","value":"TimecodeComponentSet","id":"91","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Timecode Component Set：Data Definition(Required)","value":"TimecodeComponentSet1","id":"92","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Timecode Component Set：Duration(B.Effort)","value":"TimecodeComponentSet2","id":"93","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Timecode Component Set：Start Timecode(Required)","value":"TimecodeComponentSet3","id":"94","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Timecode Component Set：Rounded Timecode Base(Required)","value":"TimecodeComponentSet4","id":"95","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Timecode Component Set：Drop Frame(Required)","value":"TimecodeComponentSet5","id":"96","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Picture Essence Descriptor Set：Instance UID(Required)","value":"PictureEssenceDescriptorSet","id":"97","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Sample Rate(Required)","value":"PictureEssenceDescriptorSet1","id":"98","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Container Duration(Optional)","value":"PictureEssenceDescriptorSet2","id":"99","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Essence Container(Required)","value":"PictureEssenceDescriptorSet3","id":"100","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Frame Layout(Best.Effort)","value":"PictureEssenceDescriptorSet4","id":"101","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Stored Width(Best.Effort)","value":"PictureEssenceDescriptorSet5","id":"102","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Stored Height(Best.Effort)","value":"PictureEssenceDescriptorSet6","id":"103","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Aspect Ratio(Best.Effort)","value":"PictureEssenceDescriptorSet7","id":"104","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Video Line Map(Best.Effort)","value":"PictureEssenceDescriptorSet8","id":"105","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Picture Essence Coding(Decoder/required)","value":"PictureEssenceDescriptorSet9","id":"106","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Component Depth(Best.Effort)","value":"PictureEssenceDescriptorSet10","id":"107","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Horizontal Subsampling(Best.Effort)","value":"PictureEssenceDescriptorSet11","id":"108","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：Vertical Subsampling(Optional)","value":"PictureEssenceDescriptorSet12","id":"109","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Essence Descriptor Set：ActiveFormatDescriptor(Optional)","value":"PictureEssenceDescriptorSet13","id":"110","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Mpeg2 Descriptor：ProfileAndLevel(Optional)","value":"Mpeg2Descriptor","id":"111","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Mpeg2 Descriptor：MaxGOP(Optional)","value":"Mpeg2Descriptor1","id":"112","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Mpeg2 Descriptor：BPictureCount(Optional)","value":"Mpeg2Descriptor2","id":"113","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Mpeg2 Descriptor：BitRate(Optional)","value":"Mpeg2Descriptor3","id":"114","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Sound Essence Descriptor Set：Instance UID(Required)","value":"SoundEssenceDescriptorSet","id":"115","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：DialNorm(Optional)","value":"SoundEssenceDescriptorSet1","id":"116","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：Sample Rate(Required)","value":"SoundEssenceDescriptorSet2","id":"117","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：Container Duration(Optional)","value":"SoundEssenceDescriptorSet3","id":"118","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：Essence Container(Required)","value":"SoundEssenceDescriptorSet4","id":"119","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：AudioSamplingRate(Best.Effort)","value":"SoundEssenceDescriptorSet5","id":"120","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：Locked/Unlocked(D.Required)","value":"SoundEssenceDescriptorSet6","id":"121","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：ChannelCount(Best.Effort)","value":"SoundEssenceDescriptorSet7","id":"122","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：Quantization bits(Best.Effort)","value":"SoundEssenceDescriptorSet8","id":"123","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：BlockAlign(Required)","value":"SoundEssenceDescriptorSet9","id":"124","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：AvgBps(Required)","value":"SoundEssenceDescriptorSet10","id":"125","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Essence Descriptor Set：Sound Essence Coding(Decoder required)","value":"SoundEssenceDescriptorSet11","id":"126","type":"10","parentId":"36","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Multiple Descriptor Set：Instance UID(Required)","value":"MultipleDescriptorSet","id":"127","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Multiple Descriptor Set：Sample Rate(Required)","value":"MultipleDescriptorSet1","id":"128","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Multiple Descriptor Set：Essence Container(Required)","value":"MultipleDescriptorSet2","id":"129","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"Multiple Descriptor Set：Sub Descriptor UIDs(Required)","value":"MultipleDescriptorSet3","id":"129","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"ANC Data Descriptor Set：Instance UID(Required)","value":"ANCDataDescriptorSet","id":"129","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"ANC Data Descriptor Set：Sample Rate(Required)","value":"ANCDataDescriptorSet1","id":"129","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"ANC Data Descriptor Set：Essence Container(Required)","value":"ANCDataDescriptorSet2","id":"129","type":"10","parentId":"36","param":["Y","Percent","Duration"]},
                     		{"name":"结构性Header MetaData Set属性缺失检测、属性值正确性检测","value":"HeaderMetaDataSet","id":"36","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Index Table结构检测","value":"IndexTableStruct","id":"130","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Index Table的位置检测","value":"IndexTableStruct1","id":"131","type":"10","parentId":"130","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Table分段要求和完整性检测","value":"IndexTableStruct2","id":"132","type":"10","parentId":"130","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Tabel 属性值检测","value":"IndexTableAttribute","id":"133","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Index Tabel:Instance UID","value":"IndexTableAttribute1","id":"134","type":"10","parentId":"133","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Tabel:Index Edit Rate","value":"IndexTableAttribute2","id":"135","type":"10","parentId":"133","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Tabel:Index Start Position","value":"IndexTableAttribute3","id":"136","type":"10","parentId":"133","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Tabel:Index Duration","value":"IndexTableAttribute4","id":"137","type":"10","parentId":"133","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Tabel:Index SID","value":"IndexTableAttribute5","id":"138","type":"10","parentId":"133","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Tabel:Body SID","value":"IndexTableAttribute6","id":"139","type":"10","parentId":"133","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Tabel:Slice Count","value":"IndexTableAttribute7","id":"140","type":"10","parentId":"133","param":["Y","Percent","Duration"]},
                     		{"name":"Index Tabel:Delta Entry Array(Required)","value":"IndexTableAttribute8","id":"141","type":"10","parentId":"133","param":["Y","Percent","Duration"]},
                     		{"name":"Index Tabel:Index Entry Array(Required)","value":"IndexTableAttribute9","id":"142","type":"10","parentId":"133","param":["Y","Percent","Duration"]},
                     		{"name":"Delta Entry检测","value":"DeltaEntry","id":"143","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Delta Entry:PosTableIndex","value":"DeltaEntry1","id":"144","type":"10","parentId":"143","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Delta Entry:Slice","value":"DeltaEntry2","id":"145","type":"10","parentId":"143","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Delta Entry:Element Delta","value":"DeltaEntry3","id":"146","type":"10","parentId":"143","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Entry检测","value":"IndexEntry","id":"147","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Index Entry:Temporal Offset","value":"IndexEntry1","id":"148","type":"10","parentId":"147","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Entry:Key-Frame Offset","value":"IndexEntry2","id":"149","type":"10","parentId":"147","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Entry:Flags","value":"IndexEntry3","id":"150","type":"10","parentId":"147","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Entry:Stream Offset","value":"IndexEntry4","id":"151","type":"10","parentId":"147","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Entry:SliceOffset","value":"IndexEntry5","id":"152","type":"10","parentId":"147","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Index Entry:PosTable","value":"IndexEntry6","id":"153","type":"10","parentId":"147","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Element Set Key检测","value":"ElementSetKey","id":"154","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"System Item Key","value":"ElementSetKey1","id":"155","type":"10","parentId":"154","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Picture Item Key","value":"ElementSetKey2","id":"156","type":"10","parentId":"154","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Sound Item Key","value":"ElementSetKey3","id":"157","type":"10","parentId":"154","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"Data Item Key","value":"ElementSetKey4","id":"158","type":"10","parentId":"154","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"System Item LTC数据检测","value":"SystemItem","id":"159","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Data Item 逐帧AFD值检测","value":"DataItemAFD","id":"160","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"AFD值综合检测","value":"GlobalAFD","id":"161","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Body Partition长度检测","value":"BodyPartitionLength","id":"162","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"音频的XDCAM兼容性检测","value":"AudioXDCAMCompatibility","id":"163","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"音频轨个数与XDCAM的兼容性检测","value":"AudioXDCAMCompatibility1","id":"164","type":"10","parentId":"163","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"音频打包方式与XDCAM的兼容性检测","value":"AudioXDCAMCompatibility2","id":"165","type":"10","parentId":"163","param":["Y","Percent","Duration"],"enable":"enable"},
                     		{"name":"EditUnit中Item的存在性和有序性检测","value":"EditUnitItem","id":"166","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"Element Length编码格式检测","value":"ElementLengthCodec","id":"167","type":"10","parentId":"0","enable":"enable"},
                     		{"name":"MP和FP中的Duration一致性检测","value":"MPAndFPDuration","id":"168","type":"10","parentId":"0","enable":"enable"},
                     		
                     		{"name":"编码检测","value":"CodecCheck","id":"1000","type":"11","parentId":"-1","enable":"enable"},
                     		{"name":"DNxHD检测项","value":"DNxHD","id":"200","type":"11","parentId":"1000","enable":"enable"},
                     		{"name":"帧大小","value":"FrameSize","id":"201","type":"11","parentId":"200","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"帧同步头","value":"HeaderPrefix","id":"202","type":"11","parentId":"200","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"Coding Control A编码控制段A[20]Sec.7.1.2","value":"CodingControlA","id":"203","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Coding Control A：帧场计数","value":"CodingControlA1","id":"204","type":"11","parentId":"203","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"Coding Control A：CRC标签","value":"CodingControlA2","id":"205","type":"11","parentId":"203","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"Coding Control A：其它比特位","value":"CodingControlA3","id":"206","type":"11","parentId":"203","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"保留字段4","value":"Reserved4","id":"207","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Image Geometry图像二维属性[20]Sec.7.1.3","value":"ImageGeometry","id":"208","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Image Geometry：ALPF","value":"ImageGeometry1","id":"209","type":"11","parentId":"208","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"Image Geometry：SPL","value":"ImageGeometry2","id":"210","type":"11","parentId":"208","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"Image Geometry：NAL","value":"ImageGeometry3","id":"211","type":"11","parentId":"208","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"Image Geometry：SBD","value":"ImageGeometry4","id":"212","type":"11","parentId":"208","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"Image Geometry：SST","value":"ImageGeometry5","id":"213","type":"11","parentId":"208","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"Image Geometry：其它比特位","value":"ImageGeometry6","id":"214","type":"11","parentId":"208","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"保留字段6","value":"Reserved6","id":"215","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"压缩类型","value":"CompressionID","id":"216","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Coding Control B编码控制段B[20]Sec.7.1.5","value":"CodingControlB","id":"217","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Coding Control B：帧场压缩方式","value":"CodingControlB1","id":"218","type":"11","parentId":"217","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"Coding Control B：其它比特位","value":"CodingControlB2","id":"219","type":"11","parentId":"217","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"保留字段9","value":"Reserved9","id":"220","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Time Control Code 时码","value":"TimeControlCode","id":"221","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Time Control Code：时码标签","value":"TimeControlCode1","id":"222","type":"11","parentId":"221","param":["Level","Duration"],"enable":"enable"},
                     		{"name":"Time Control Code：时码","value":"TimeControlCode2","id":"223","type":"11","parentId":"221","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"Time Control Code：其它比特位","value":"TimeControlCode3","id":"224","type":"11","parentId":"221","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"保留字段11","value":"Reserved11","id":"225","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"User Data Field","value":"UserDataField","id":"226","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"User Data Field：用户数据标签","value":"UserDataField1","id":"227","type":"11","parentId":"226","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"User Data Field：用户数据","value":"UserDataField2","id":"228","type":"11","parentId":"226","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"User Data Field：其它比特位","value":"UserDataField3","id":"228","type":"11","parentId":"226","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"保留字段13","value":"Reserved13","id":"229","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Macroblock Scan Indices Control宏块扫描索引控制[20]Sec.7.1.10 ","value":"MacroBlockScanIndicesControl","id":"230","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Macroblock Scan Indices Control：MSIPS的大小","value":"MacroBlockScanIndicesControl1","id":"231","type":"11","parentId":"230","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"Macroblock Scan Indices Control：宏块扫描索引个数","value":"MacroBlockScanIndicesControl2","id":"232","type":"11","parentId":"230","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"Macroblock Scan Indices Control：其它比特位","value":"MacroBlockScanIndicesControl3","id":"233","type":"11","parentId":"230","param":["AvgLoudness"],"enable":"enable"},
                     		{"name":"Macroblock Scan Indices PayLoad宏块扫描索引表","value":"MacroBlockScanIndicesPayLoad","id":"234","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"EOF","value":"EOF","id":"235","type":"11","parentId":"200","enable":"enable"},
                     		{"name":"Compressed Data","value":"CompressedData","id":"236","type":"11","parentId":"200","enable":"enable"},
                     		
                     		{"name":"AVC Intra检测项","value":"AVCIntra","id":"300","type":"12","parentId":"1000","enable":"enable"},
                     		{"name":"NAL结构存在性","value":"NALStruct","id":"301","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"AUD头存在性","value":"AUDHeader","id":"302","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"Slice数量","value":"SliceCount","id":"303","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"Slice数据长度","value":"SliceLength","id":"304","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"SPS内容","value":"SPSContent","id":"305","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"SPS：profile_idc","value":"SPSContent1","id":"306","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：constraint_set0_flag","value":"SPSContent2","id":"307","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：constraint_set1_flag","value":"SPSContent3","id":"308","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：constraint_set2_flag","value":"SPSContent4","id":"309","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：constraint_set3_flag","value":"SPSContent5","id":"310","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：reserved_zero_4bits","value":"SPSContent6","id":"311","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：level_idc","value":"SPSContent7","id":"312","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_parameter_set_id","value":"SPSContent8","id":"313","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：chroma_format_idc","value":"SPSContent9","id":"314","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：bit_depth_luma_minus8","value":"SPSContent10","id":"315","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：bit_depth_chroma_minus8","value":"SPSContent11","id":"316","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：qpprime_y_zero_transform_bypass_flag","value":"SPSContent12","id":"317","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：Seq_scaling_matrix_present_flag","value":"SPSContent13","id":"318","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[0]","value":"SPSContent14","id":"319","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[1]","value":"SPSContent15","id":"320","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：ScalingList4x4[1]","value":"SPSContent16","id":"321","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[2]","value":"SPSContent17","id":"322","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：ScalingList4x4[2]","value":"SPSContent18","id":"323","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[3]","value":"SPSContent19","id":"324","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[4]","value":"SPSContent20","id":"325","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[5]","value":"SPSContent21","id":"326","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[6]","value":"SPSContent22","id":"327","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：ScalingList8x8[0]","value":"SPSContent23","id":"328","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：seq_scaling_list_present_flag[7]","value":"SPSContent24","id":"329","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：log2_max_frame_num_minus4","value":"SPSContent25","id":"330","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：pic_order_cnt_type","value":"SPSContent26","id":"331","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：log2_max_pic_order_cnt_lsb_minus4","value":"SPSContent27","id":"332","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：num_ref_frames","value":"SPSContent28","id":"333","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：gaps_in_frame_num_value_allowed_flag","value":"SPSContent29","id":"334","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：pic_width_in_mbs_minus1","value":"SPSContent30","id":"335","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：pic_height_in_map_units_minus1","value":"SPSContent31","id":"336","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：frame_mbs_only_flag","value":"SPSContent32","id":"337","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：mb_adaptive_frame_field_flag","value":"SPSContent33","id":"338","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：direct_8x8_inference_flag","value":"SPSContent34","id":"339","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：frame_cropping_flag","value":"SPSContent35","id":"340","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：frame_crop_left_offset","value":"SPSContent36","id":"341","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：frame_crop_right_offset","value":"SPSContent37","id":"342","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：frame_crop_top_offset","value":"SPSContent38","id":"343","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：frame_crop_bottom_offset","value":"SPSContent39","id":"344","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"SPS：vui_parameters_present_flag","value":"SPSContent40","id":"345","type":"12","parentId":"305","enable":"enable"},
                     		{"name":"PPS内容","value":"PPSContent","id":"346","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"PPS：pic_parameter_set_id","value":"PPSContent1","id":"347","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：seq_parameter_set_id","value":"PPSContent2","id":"348","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：entropy_coding_mode_flag","value":"PPSContent3","id":"349","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：pic_order_present_flag","value":"PPSContent4","id":"350","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：num_slice_groups_minus1","value":"PPSContent5","id":"351","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：num_ref_idx_l0_active_minus1","value":"PPSContent6","id":"352","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：num_ref_idx_l1_active_minus1","value":"PPSContent7","id":"353","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：weighted_pred_flag","value":"PPSContent8","id":"354","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：weighted_bipred_idc","value":"PPSContent9","id":"355","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：pic_init_qp_minus26","value":"PPSContent10","id":"356","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：pic_init_qs_minus26","value":"PPSContent11","id":"357","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：chroma_qp_index_offset","value":"PPSContent12","id":"358","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：deblocking_filter_control_present_flag","value":"PPSContent13","id":"359","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：constrained_intra_pred_flag","value":"PPSContent14","id":"360","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：redundant_pic_cnt_present_flag","value":"PPSContent15","id":"361","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：transform_8x8_mode_flag","value":"PPSContent16","id":"362","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：pic_scaling_matrix_present_flag","value":"PPSContent17","id":"363","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"PPS：second_chroma_qp_index_offset","value":"PPSContent18","id":"364","type":"12","parentId":"346","enable":"enable"},
                     		{"name":"SLICE HEADER内容","value":"SliceHeaderContent","id":"365","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"SLICE HEADER：first_mb_in_slice","value":"SliceHeaderContent1","id":"366","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：slice_type","value":"SliceHeaderContent2","id":"367","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：pic_parameter_set_id","value":"SliceHeaderContent3","id":"368","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：frame_num","value":"SliceHeaderContent4","id":"369","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：field_pic_flag","value":"SliceHeaderContent5","id":"370","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：idr_pic_id","value":"SliceHeaderContent6","id":"371","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：pic_order_cnt_lsb","value":"SliceHeaderContent7","id":"372","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：slice_qp_delta","value":"SliceHeaderContent8","id":"373","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"SLICE HEADER：disable_deblocking_filter_idc","value":"SliceHeaderContent9","id":"374","type":"12","parentId":"365","enable":"enable"},
                     		{"name":"VUI内容检测","value":"VUIContent","id":"375","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"VUI：aspect_ratio_info_present_flag","value":"VUIContent1","id":"376","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：aspect_ratio_idc","value":"VUIContent2","id":"377","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：overscan_info_present_flag","value":"VUIContent3","id":"378","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：overscan_appropriate_flag","value":"VUIContent4","id":"379","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：video_signal_type_present_flag","value":"VUIContent5","id":"380","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：video_format","value":"VUIContent6","id":"381","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：video_full_range_flag","value":"VUIContent7","id":"382","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：colour_description_present_flag","value":"VUIContent8","id":"383","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：colour_primaries","value":"VUIContent9","id":"384","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：transfer_characteristics","value":"VUIContent10","id":"385","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：matrix_coefficients","value":"VUIContent11","id":"386","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：chroma_loc_info_present_flag","value":"VUIContent12","id":"387","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：timing_info_present_flag","value":"VUIContent13","id":"388","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：num_units_in_tick","value":"VUIContent14","id":"389","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：time_scale","value":"VUIContent15","id":"390","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：fixed_frame_rate_flag","value":"VUIContent16","id":"391","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：nal_hrd_parameters_present_flag","value":"VUIContent17","id":"392","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：vcl_hrd_parameters_present_flag","value":"VUIContent18","id":"393","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：pic_struct_present_flag","value":"VUIContent19","id":"394","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"VUI：bitstream_restriction_flag","value":"VUIContent20","id":"395","type":"12","parentId":"375","enable":"enable"},
                     		{"name":"SEI内容检测","value":"SEIContent","id":"396","type":"12","parentId":"300","enable":"enable"},
                     		{"name":"SEI的位置和长度","value":"SEIContent1","id":"397","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：uuid_iso_iec_11578","value":"SEIContent2","id":"398","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：type_indicator","value":"SEIContent3","id":"399","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：LTC","value":"SEIContent4","id":"400","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：LTC UB","value":"SEIContent5","id":"401","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：VAUX SOURCE","value":"SEIContent6","id":"402","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：VITC","value":"SEIContent7","id":"403","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：VITC UB","value":"SEIContent8","id":"404","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：REC DATE","value":"SEIContent9","id":"405","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：REC TIME","value":"SEIContent10","id":"406","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"SEI：其它保留或填充数据","value":"SEIContent11","id":"407","type":"12","parentId":"396","enable":"enable"},
                     		{"name":"宏块数据检测","value":"MacroBlockData","id":"408","type":"12","parentId":"300","enable":"enable"},
                     		
                     		{"name":"Mpeg2 LongGop检测项","value":"Mpeg2LongGop","id":"500","type":"13","parentId":"1000","enable":"enable"},
                     		{"name":"Start Code","value":"StartCode","id":"501","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"Start Code：sequence_start_code","value":"StartCode1","id":"502","type":"13","parentId":"501","enable":"enable"},
                     		{"name":"Start Code：extension_start_code","value":"StartCode2","id":"503","type":"13","parentId":"501","enable":"enable"},
                     		{"name":"Start Code：extension_start_code_identifier","value":"StartCode3","id":"504","type":"13","parentId":"501","enable":"enable"},
                     		{"name":"Start Code：GOP_start_code","value":"StartCode4","id":"505","type":"13","parentId":"501","enable":"enable"},
                     		{"name":"Start Code：picture_start_code","value":"StartCode5","id":"506","type":"13","parentId":"501","enable":"enable"},
                     		{"name":"Start Code：sequence_end_code","value":"StartCode6","id":"507","type":"13","parentId":"501","enable":"enable"},
                     		{"name":"sequence 结构检测","value":"SequenceStruct","id":"508","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"sequence_header","value":"SequenceStruct1","id":"521","type":"13","parentId":"508","enable":"enable"},
                     		{"name":"sequence_header：horizontal_size_value","value":"SequenceStruct2","id":"509","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：vertical_size_value","value":"SequenceStruct3","id":"510","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：aspect_ratio_information","value":"SequenceStruct4","id":"511","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：frame_rate_code","value":"SequenceStruct5","id":"512","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：bit_rate_value","value":"SequenceStruct6","id":"513","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：marker_bit","value":"SequenceStruct7","id":"514","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：vbv_buffer_size_value","value":"SequenceStruct8","id":"515","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：constrained_parameters_flag","value":"SequenceStruct9","id":"516","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：load_intra_quantiser_matrix","value":"SequenceStruct10","id":"517","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：intra_quantiser_matrix[64]","value":"SequenceStruct11","id":"518","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：load_non_intra_quantiser_matrix","value":"SequenceStruct12","id":"519","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_header：non_intra_quantiser_matrix[64]","value":"SequenceStruct13","id":"520","type":"13","parentId":"521","enable":"enable"},
                     		{"name":"sequence_extention","value":"SequenceStruct14","id":"522","type":"13","parentId":"508","enable":"enable"},
                     		{"name":"sequence_extention：profile_and_level_indication","value":"SequenceStruct15","id":"523","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"sequence_extention：chroma_format","value":"SequenceStruct16","id":"524","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"sequence_extention：marker_bit","value":"SequenceStruct17","id":"525","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"sequence_extention：frame_rate_extension_n","value":"SequenceStruct18","id":"526","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"sequence_extention：frame_rate_extension_d","value":"SequenceStruct19","id":"527","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"sequence_extention：low_delay","value":"SequenceStruct20","id":"528","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"sequence_extention：bit_rate_extention","value":"SequenceStruct21","id":"529","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"sequence_extention：vbv_buffer_size_extention","value":"SequenceStruct22","id":"530","type":"13","parentId":"522","enable":"enable"},
                     		{"name":"Sequence display extention","value":"SequenceStruct23","id":"531","type":"13","parentId":"508","enable":"enable"},
                     		{"name":"Sequence display extention：video_format","value":"SequenceStruct24","id":"532","type":"13","parentId":"531","enable":"enable"},
                     		{"name":"Sequence display extention：color_primaries","value":"SequenceStruct25","id":"533","type":"13","parentId":"531","enable":"enable"},
                     		{"name":"Sequence display extention：transfer_characteristics","value":"SequenceStruct26","id":"534","type":"13","parentId":"531","enable":"enable"},
                     		{"name":"Sequence display extention：matrix_coefficients","value":"SequenceStruct27","id":"535","type":"13","parentId":"531","enable":"enable"},
                     		{"name":"Sequence display extention：marker_bit","value":"SequenceStruct28","id":"536","type":"13","parentId":"531","enable":"enable"},
                     		{"name":"GOP","value":"GOP","id":"537","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"GOP：time_code_hours","value":"GOP1","id":"538","type":"13","parentId":"537","enable":"enable"},
                     		{"name":"GOP：time_code_minutes","value":"GOP2","id":"539","type":"13","parentId":"537","enable":"enable"},
                     		{"name":"GOP：time_code_seconds","value":"GOP3","id":"540","type":"13","parentId":"537","enable":"enable"},
                     		{"name":"GOP：time_code_pictures","value":"GOP4","id":"541","type":"13","parentId":"537","enable":"enable"},
                     		{"name":"GOP：closed_gop","value":"GOP5","id":"542","type":"13","parentId":"537","enable":"enable"},
                     		{"name":"GOP：broken_link","value":"GOP6","id":"543","type":"13","parentId":"537","enable":"enable"},
                     		{"name":"pitcure 结构检测","value":"PictureStruct","id":"544","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"picture_header","value":"PictureStruct1","id":"545","type":"13","parentId":"544","enable":"enable"},
                     		{"name":"picture_header：temporal_reference","value":"PictureStruct2","id":"546","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header：picture_coding_type","value":"PictureStruct3","id":"547","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header：vbv_delay","value":"PictureStruct4","id":"548","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header：full_pel_forward_vector","value":"PictureStruct5","id":"549","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header：forward_f_code","value":"PictureStruct6","id":"550","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header：full_pel_backward_vector","value":"PictureStruct7","id":"551","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header：backward_f_code","value":"PictureStruct8","id":"552","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header：extra_bit_picture","value":"PictureStruct9","id":"553","type":"13","parentId":"545","enable":"enable"},
                     		{"name":"picture_header_extention","value":"PictureStruct10","id":"554","type":"13","parentId":"544","enable":"enable"},
                     		{"name":"picture_header_extention：f_code[0][0](forward horizontal)","value":"PictureStruct11","id":"555","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：f_code[0][1](forward vertical)","value":"PictureStruct12","id":"556","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：f_code[1][0](backward horizontal)","value":"PictureStruct13","id":"557","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：f_code[1][1](backward vertical)","value":"PictureStruct14","id":"558","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：top_field_first","value":"PictureStruct15","id":"559","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：picture_structure","value":"PictureStruct16","id":"560","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：frame_pred_frame_dct","value":"PictureStruct17","id":"561","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：repeat_first_field","value":"PictureStruct18","id":"562","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"picture_header_extention：chroma_420_type","value":"PictureStruct19","id":"563","type":"13","parentId":"554","enable":"enable"},
                     		{"name":"slice layer检测结构检测","value":"SliceLayerStruct","id":"564","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"slice：Slice Start Code","value":"SliceLayerStruct1","id":"565","type":"13","parentId":"564","enable":"enable"},
                     		{"name":"slice：quantiser_scale_code","value":"SliceLayerStruct2","id":"566","type":"13","parentId":"564","enable":"enable"},
                     		{"name":"slice：extra_bit_slice","value":"SliceLayerStruct3","id":"567","type":"13","parentId":"564","enable":"enable"},
                     		{"name":"slice：Slice_vertical_position","value":"SliceLayerStruct4","id":"568","type":"13","parentId":"564","enable":"enable"},
                     		{"name":"slice：First and Last Macroblock of Slice","value":"SliceLayerStruct5","id":"569","type":"13","parentId":"564","enable":"enable"},
                     		{"name":"slice：Macroblock number","value":"SliceLayerStruct6","id":"570","type":"13","parentId":"564","enable":"enable"},
                     		{"name":"macroblock layer检测","value":"MacroblockLayer","id":"571","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"macroblock：macroblock_address_increment","value":"MacroblockLayer1","id":"572","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"macroblock：macroblock_type","value":"MacroblockLayer2","id":"573","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"macroblock：field_motion_type","value":"MacroblockLayer3","id":"574","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"macroblock：frame_motion_type ","value":"MacroblockLayer4","id":"575","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"macroblock：Bad VLC for motion_code","value":"MacroblockLayer5","id":"576","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"macroblock：Bad VLC for motion_residual","value":"MacroblockLayer6","id":"577","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"macroblock：Bad VLC for coded_block_pattern","value":"MacroblockLayer7","id":"578","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"macroblock：Motion vector out of range","value":"MacroblockLayer8","id":"579","type":"13","parentId":"571","enable":"enable"},
                     		{"name":"block 检测","value":"Block","id":"580","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"block：Bad VLC Found in Intra Block","value":"Block1","id":"581","type":"13","parentId":"580","enable":"enable"},
                     		{"name":"block：Bad VLC Found in Non_Intra Block","value":"Block2","id":"582","type":"13","parentId":"580","enable":"enable"},
                     		{"name":"block：DCT coefficient index out of bounds","value":"Block3","id":"583","type":"13","parentId":"580","enable":"enable"},
                     		{"name":"profile-level参数检测","value":"ProfileLevelSetting","id":"584","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"profile-level：f_code[0][0] (forward horizontal)","value":"ProfileLevelSetting1","id":"585","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：f_code[0][1] (forward vertical)","value":"ProfileLevelSetting2","id":"586","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：f_code[1][0](backward horizontal)","value":"ProfileLevelSetting3","id":"587","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：f_code[1][1](backward vertical)","value":"ProfileLevelSetting4","id":"588","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：chroma_format","value":"ProfileLevelSetting5","id":"589","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：Frame size","value":"ProfileLevelSetting6","id":"590","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：Frame rate","value":"ProfileLevelSetting7","id":"591","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：luminance sample rate","value":"ProfileLevelSetting8","id":"592","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：Bit rate","value":"ProfileLevelSetting9","id":"593","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"profile-level：VBV Buffer size requirements","value":"ProfileLevelSetting10","id":"594","type":"13","parentId":"584","enable":"enable"},
                     		{"name":"各数据结构的位置、顺序、大小、一致性检测","value":"DataCorrectness","id":"595","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"Data present after end of video sequence","value":"DataCorrectness1","id":"596","type":"13","parentId":"595","enable":"enable"},
                     		{"name":"Premature end of picture","value":"DataCorrectness2","id":"597","type":"13","parentId":"595","enable":"enable"},
                     		{"name":"Repeated header differs from previous header","value":"DataCorrectness3","id":"598","type":"13","parentId":"595","enable":"enable"},
                     		{"name":"Bad placement of MPEG-2 GOP headers","value":"DataCorrectness4","id":"599","type":"13","parentId":"595","enable":"enable"},
                     		{"name":"An MPEG-2 GOP header should have been closed,but was not","value":"DataCorrectness5","id":"600","type":"13","parentId":"595","enable":"enable"},
                     		{"name":"GOP结构","value":"GOPStruct","id":"601","type":"13","parentId":"500","enable":"enable"},
                     		{"name":"I picture expected after GOP header","value":"GOPStruct1","id":"602","type":"13","parentId":"601","enable":"enable"},
                     		{"name":"Gop 长度","value":"GOPStruct2","id":"603","type":"13","parentId":"601","enable":"enable"},
                     		{"name":"连续B帧数量","value":"GOPStruct3","id":"604","type":"13","parentId":"601","enable":"enable"}
                     	];
