/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Activity.java
 * 日 期：Thu Oct 09 15:08:55 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * WFM_ACTIVITY
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "WFM_ACTIVITY", keyGenerator = "increment")
public class Activity implements Serializable
{

    private static final long serialVersionUID = 1L;

    public static String PROP_ACT_CLASS = "ACT_CLASS";
    public static String PROP_ACT_DESC = "ACT_DESC";
    public static String PROP_ACT_ICON = "ACT_ICON";
    public static String PROP_ACT_ID = "ACT_ID";
    public static String PROP_ACTION = "ACTION";
    public static String PROP_ACT_NAME = "ACT_NAME";
    public static String PROP_ACT_TYPE = "ACT_TYPE";
    public static String PROP_CONCURRENT_NUM = "CONCURRENT_NUM";
    public static String PROP_CREATE_TIME = "CREATE_TIME";
    public static String PROP_FIELD_1 = "FIELD_1";
    public static String PROP_TIME_LIMIT = "TIME_LIMIT";

    /**
     * primary key field of actId
     */
    @FieldMapping(columnName = "ACT_ID", columnType = 4, primary = true)
    private Integer actId;
    @FieldMapping(columnName = "ACT_CLASS", columnType = 4)
    private Integer actClass;
    @FieldMapping(columnName = "ACT_DESC", columnType = 12)
    private String actDesc;
    @FieldMapping(columnName = "ACT_ICON", columnType = 12)
    private String actIcon;
    @FieldMapping(columnName = "ACTION", columnType = 12)
    private String action;
    @FieldMapping(columnName = "ACT_NAME", columnType = 12)
    private String actName;
    @FieldMapping(columnName = "ACT_TYPE", columnType = 4)
    private Integer actType;
    @FieldMapping(columnName = "CONCURRENT_NUM", columnType = 4)
    private Integer concurrentNum;
    @FieldMapping(columnName = "CREATE_TIME", columnType = 93)
    private Date createTime;
    @FieldMapping(columnName = "FIELD_1", columnType = 12)
    private String field1;
    @FieldMapping(columnName = "TIME_LIMIT", columnType = 4)
    private Integer timeLimit;

    public Activity()
    {
        super();
    }

    public Activity(Integer actId)
    {
        this.actId = actId;
    }

    public Activity(String actName, Integer actType, Date createTime)
    {
        this.actName = actName;
        this.actType = actType;
        this.createTime = createTime;
    }

    /**
     * @return the actClass
     */
    public Integer getActClass()
    {
        return this.actClass;
    }

    /**
     * @param actClass the actClass to set
     */
    public void setActClass(Integer actClass)
    {
        this.actClass = actClass;
    }

    /**
     * @return the actDesc
     */
    public String getActDesc()
    {
        return this.actDesc;
    }

    /**
     * @param actDesc the actDesc to set
     */
    public void setActDesc(String actDesc)
    {
        this.actDesc = actDesc;
    }

    /**
     * @return the actIcon
     */
    public String getActIcon()
    {
        return this.actIcon;
    }

    /**
     * @param actIcon the actIcon to set
     */
    public void setActIcon(String actIcon)
    {
        this.actIcon = actIcon;
    }

    /**
     * @return the actId
     */
    public Integer getActId()
    {
        return this.actId;
    }

    /**
     * @param actId the actId to set
     */
    public void setActId(Integer actId)
    {
        this.actId = actId;
    }

    /**
     * @return the action
     */
    public String getAction()
    {
        return this.action;
    }

    /**
     * @param action the action to set
     */
    public void setAction(String action)
    {
        this.action = action;
    }

    /**
     * @return the actName
     */
    public String getActName()
    {
        return this.actName;
    }

    /**
     * @param actName the actName to set
     */
    public void setActName(String actName)
    {
        this.actName = actName;
    }

    /**
     * @return the actType
     */
    public Integer getActType()
    {
        return this.actType;
    }

    /**
     * @param actType the actType to set
     */
    public void setActType(Integer actType)
    {
        this.actType = actType;
    }

    /**
     * @return the concurrentNum
     */
    public Integer getConcurrentNum()
    {
        return this.concurrentNum;
    }

    /**
     * @param concurrentNum the concurrentNum to set
     */
    public void setConcurrentNum(Integer concurrentNum)
    {
        this.concurrentNum = concurrentNum;
    }

    /**
     * @return the createTime
     */
    public Date getCreateTime()
    {
        return this.createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(Date createTime)
    {
        this.createTime = createTime;
    }

    /**
     * @return the field1
     */
    public String getField1()
    {
        return this.field1;
    }

    /**
     * @param field1 the field1 to set
     */
    public void setField1(String field1)
    {
        this.field1 = field1;
    }

    /**
     * @return the timeLimit
     */
    public Integer getTimeLimit()
    {
        return this.timeLimit;
    }

    /**
     * @param timeLimit the timeLimit to set
     */
    public void setTimeLimit(Integer timeLimit)
    {
        this.timeLimit = timeLimit;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object o)
    {
        if ((o == null) || !(o instanceof Activity))
        {
            return false;
        }
        Activity other = (Activity) o;
        if (null == this.actId)
        {
            if (other.actId != null)
                return false;
        }
        else if (!this.actId.equals(other.actId))
            return false;
        return true;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((actId == null) ? 0 : actId.hashCode());
        return result;
    }

}
