/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Actparam.java
 * 日 期：Thu Oct 09 15:08:56 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * WFM_ACTPARAM
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "WFM_ACTPARAM", keyGenerator = "jetsennet.orm.executor.keygen.KeyGenerationNetSequence")
public class Actparam implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_PARAM_DATA = "PARAM_DATA";
	public static String PROP_PARAM_ID = "PARAM_ID";
	public static String PROP_PARAM_MD5 = "PARAM_MD5";
	public static String PROP_PARAM_TYPE = "PARAM_TYPE";
	public static String PROP_PROCACT_ID = "PROCACT_ID";
	public static String PROP_TEMPLATE_NAME = "TEMPLATE_NAME";
	
	/**
	 * primary key field of paramId
	 */
	@FieldMapping(columnName = "PARAM_ID", columnType = 4, primary = true)
	private Integer paramId;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "PARAM_DATA", columnType = 2005)
	private String paramData;
	@FieldMapping(columnName = "PARAM_MD5", columnType = 12)
	private String paramMd5;
	@FieldMapping(columnName = "PARAM_TYPE", columnType = 4)
	private Integer paramType;
	@FieldMapping(columnName = "PROCACT_ID", columnType = 4)
	private Integer procactId;
	@FieldMapping(columnName = "TEMPLATE_NAME", columnType = 12)
	private String templateName;
	
	public Actparam() {
		super();
	}

	public Actparam(Integer paramId) {
		this.paramId = paramId;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the paramData
	 */
	public String getParamData() {
		return this.paramData;
	}
	
	/**
	 * @param paramData the paramData to set
	 */
	public void setParamData(String paramData) {
		this.paramData = paramData;
	}

	/**
	 * @return the paramId
	 */
	public Integer getParamId() {
		return this.paramId;
	}
	
	/**
	 * @param paramId the paramId to set
	 */
	public void setParamId(Integer paramId) {
		this.paramId = paramId;
	}

	/**
	 * @return the paramMd5
	 */
	public String getParamMd5() {
		return this.paramMd5;
	}
	
	/**
	 * @param paramMd5 the paramMd5 to set
	 */
	public void setParamMd5(String paramMd5) {
		this.paramMd5 = paramMd5;
	}

	/**
	 * @return the paramType
	 */
	public Integer getParamType() {
		return this.paramType;
	}
	
	/**
	 * @param paramType the paramType to set
	 */
	public void setParamType(Integer paramType) {
		this.paramType = paramType;
	}

	/**
	 * @return the procactId
	 */
	public Integer getProcactId() {
		return this.procactId;
	}
	
	/**
	 * @param procactId the procactId to set
	 */
	public void setProcactId(Integer procactId) {
		this.procactId = procactId;
	}

	/**
	 * @return the templateName
	 */
	public String getTemplateName() {
		return this.templateName;
	}
	
	/**
	 * @param templateName the templateName to set
	 */
	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Actparam)) {
			return false;
		}
		Actparam other = (Actparam)o;
		if (null == this.paramId) {
			if (other.paramId != null)
				return false;
		} else if (!this.paramId.equals(other.paramId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((paramId == null) ? 0 : paramId.hashCode());
		return result;
	}
	
}