/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Assignrule.java
 * 日 期：Thu Oct 09 15:08:56 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * WFM_ASSIGNRULE
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "WFM_ASSIGNRULE", keyGenerator = "increment")
public class Assignrule implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_ASSIGN_OBJID = "ASSIGN_OBJID";
	public static String PROP_ASSIGN_PARAM = "ASSIGN_PARAM";
	public static String PROP_ASSIGN_TYPE = "ASSIGN_TYPE";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_PROCACT_ID = "PROCACT_ID";
	
	/**
	 * primary key field of procactId
	 * foreign key field of WFM_PROCACT.PROCACT_ID
	 */
	@FieldMapping(columnName = "PROCACT_ID", columnType = 4, primary = true)
	private Integer procactId;
	@FieldMapping(columnName = "ASSIGN_OBJID", columnType = 12)
	private String assignObjid;
	@FieldMapping(columnName = "ASSIGN_PARAM", columnType = 12)
	private String assignParam;
	@FieldMapping(columnName = "ASSIGN_TYPE", columnType = 4)
	private Integer assignType;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	
	public Assignrule() {
		super();
	}

	public Assignrule(Integer procactId) {
		this.procactId = procactId;
	}

	/**
	 * @return the assignObjid
	 */
	public String getAssignObjid() {
		return this.assignObjid;
	}
	
	/**
	 * @param assignObjid the assignObjid to set
	 */
	public void setAssignObjid(String assignObjid) {
		this.assignObjid = assignObjid;
	}

	/**
	 * @return the assignParam
	 */
	public String getAssignParam() {
		return this.assignParam;
	}
	
	/**
	 * @param assignParam the assignParam to set
	 */
	public void setAssignParam(String assignParam) {
		this.assignParam = assignParam;
	}

	/**
	 * @return the assignType
	 */
	public Integer getAssignType() {
		return this.assignType;
	}
	
	/**
	 * @param assignType the assignType to set
	 */
	public void setAssignType(Integer assignType) {
		this.assignType = assignType;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the procactId
	 */
	public Integer getProcactId() {
		return this.procactId;
	}
	
	/**
	 * @param procactId the procactId to set
	 */
	public void setProcactId(Integer procactId) {
		this.procactId = procactId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Assignrule)) {
			return false;
		}
		Assignrule other = (Assignrule)o;
		if (null == this.procactId) {
			if (other.procactId != null)
				return false;
		} else if (!this.procactId.equals(other.procactId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((procactId == null) ? 0 : procactId.hashCode());
		return result;
	}
	
}