/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Ctrlword.java
 * 日 期：Thu Oct 09 15:08:56 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * NET_CTRLWORD
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "NET_CTRLWORD", keyGenerator = "jetsennet.orm.executor.keygen.KeyGenerationNetSequence")
public class Ctrlword implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_CW_CODE = "CW_CODE";
	public static String PROP_CW_DESC = "CW_DESC";
	public static String PROP_CW_ID = "CW_ID";
	public static String PROP_CW_NAME = "CW_NAME";
	public static String PROP_CW_TYPE = "CW_TYPE";
	public static String PROP_CW_SYS = "CW_SYS";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_FIELD_2 = "FIELD_2";
	
	/**
	 * primary key field of cwId
	 */
	@FieldMapping(columnName = "CW_ID", columnType = 4, primary = true)
	private Integer cwId;
	@FieldMapping(columnName = "CW_CODE", columnType = 12)
	private String cwCode;
	@FieldMapping(columnName = "CW_DESC", columnType = 12)
	private String cwDesc;
	@FieldMapping(columnName = "CW_NAME", columnType = 12)
	private String cwName;
	@FieldMapping(columnName = "CW_TYPE", columnType = 4)
	private Integer cwType;
	@FieldMapping(columnName = "CW_SYS", columnType = 4)
	private Integer cwSys;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	
	public Ctrlword() {
		super();
	}

	public Ctrlword(Integer cwId) {
		this.cwId = cwId;
	}

	public Ctrlword(Integer cwType, Integer cwSys) {
		this.cwType = cwType;
		this.cwSys = cwSys;
	}

	
	/**
	 * @return the cwCode
	 */
	public String getCwCode() {
		return this.cwCode;
	}
	
	/**
	 * @param cwCode the cwCode to set
	 */
	public void setCwCode(String cwCode) {
		this.cwCode = cwCode;
	}

	/**
	 * @return the cwDesc
	 */
	public String getCwDesc() {
		return this.cwDesc;
	}
	
	/**
	 * @param cwDesc the cwDesc to set
	 */
	public void setCwDesc(String cwDesc) {
		this.cwDesc = cwDesc;
	}

	/**
	 * @return the cwId
	 */
	public Integer getCwId() {
		return this.cwId;
	}
	
	/**
	 * @param cwId the cwId to set
	 */
	public void setCwId(Integer cwId) {
		this.cwId = cwId;
	}

	/**
	 * @return the cwName
	 */
	public String getCwName() {
		return this.cwName;
	}
	
	/**
	 * @param cwName the cwName to set
	 */
	public void setCwName(String cwName) {
		this.cwName = cwName;
	}

	/**
	 * @return the cwType
	 */
	public Integer getCwType() {
		return this.cwType;
	}
	
	/**
	 * @param cwType the cwType to set
	 */
	public void setCwType(Integer cwType) {
		this.cwType = cwType;
	}

	
	public Integer getCwSys()
    {
        return cwSys;
    }

    public void setCwSys(Integer cwSys)
    {
        this.cwSys = cwSys;
    }

    public String getField1()
    {
        return field1;
    }

    public void setField1(String field1)
    {
        this.field1 = field1;
    }

    public String getField2()
    {
        return field2;
    }

    public void setField2(String field2)
    {
        this.field2 = field2;
    }

    /* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Ctrlword)) {
			return false;
		}
		Ctrlword other = (Ctrlword)o;
		if (null == this.cwId) {
			if (other.cwId != null)
				return false;
		} else if (!this.cwId.equals(other.cwId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cwId == null) ? 0 : cwId.hashCode());
		return result;
	}
	
}