/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Process.java
 * 日 期：Thu Oct 09 15:08:57 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import java.util.Date;

import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * WFM_PROCESS
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "WFM_PROCESS", keyGenerator = "increment")
public class Process implements Serializable
{

    private static final long serialVersionUID = 1L;

    public static String PROP_CREATE_TIME = "CREATE_TIME";
    public static String PROP_FIELD_1 = "FIELD_1";
    public static String PROP_FLOW_TYPE = "FLOW_TYPE";
    public static String PROP_PROC_DESC = "PROC_DESC";
    public static String PROP_PROC_ID = "PROC_ID";
    public static String PROP_PROC_NAME = "PROC_NAME";
    public static String PROP_PROC_STATE = "PROC_STATE";
    public static String PROP_PROC_TYPE = "PROC_TYPE";
    public static String PROP_OBJ_TYPE = "OBJ_TYPE";

    /**
     * primary key field of procId
     */
    @FieldMapping(columnName = "PROC_ID", columnType = 4, primary = true)
    private Integer procId;
    @FieldMapping(columnName = "CREATE_TIME", columnType = 93)
    private Date createTime;
    @FieldMapping(columnName = "FIELD_1", columnType = 12)
    private String field1;
    @FieldMapping(columnName = "FLOW_TYPE", columnType = 4)
    private Integer flowType;
    @FieldMapping(columnName = "PROC_DESC", columnType = 12)
    private String procDesc;
    @FieldMapping(columnName = "PROC_NAME", columnType = 12)
    private String procName;
    @FieldMapping(columnName = "PROC_STATE", columnType = 4)
    private Integer procState;
    @FieldMapping(columnName = "PROC_TYPE", columnType = 4)
    private Integer procType;
    @FieldMapping(columnName = "OBJ_TYPE", columnType = 12)
    private Integer objType;

    public Process()
    {
        super();
        this.createTime = new Date();
    }

    public Process(Integer procId)
    {
        this.procId = procId;
        this.createTime = new Date();
    }

    public Process(Date createTime, Integer flowType, String procName, Integer procType)
    {
        this.createTime = createTime;
        this.flowType = flowType;
        this.procName = procName;
        this.procType = procType;
    }

    /**
     * @return the createTime
     */
    public Date getCreateTime()
    {
        return this.createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(Date createTime)
    {
        this.createTime = createTime;
    }

    /**
     * @return the field1
     */
    public String getField1()
    {
        return this.field1;
    }

    /**
     * @param field1 the field1 to set
     */
    public void setField1(String field1)
    {
        this.field1 = field1;
    }

    /**
     * @return the flowType
     */
    public Integer getFlowType()
    {
        return this.flowType;
    }

    /**
     * @param flowType the flowType to set
     */
    public void setFlowType(Integer flowType)
    {
        this.flowType = flowType;
    }

    /**
     * @return the procDesc
     */
    public String getProcDesc()
    {
        return this.procDesc;
    }

    /**
     * @param procDesc the procDesc to set
     */
    public void setProcDesc(String procDesc)
    {
        this.procDesc = procDesc;
    }

    /**
     * @return the procId
     */
    public Integer getProcId()
    {
        return this.procId;
    }

    /**
     * @param procId the procId to set
     */
    public void setProcId(Integer procId)
    {
        this.procId = procId;
    }

    /**
     * @return the procName
     */
    public String getProcName()
    {
        return this.procName;
    }

    /**
     * @param procName the procName to set
     */
    public void setProcName(String procName)
    {
        this.procName = procName;
    }

    /**
     * @return the procState
     */
    public Integer getProcState()
    {
        return this.procState;
    }

    /**
     * @param procState the procState to set
     */
    public void setProcState(Integer procState)
    {
        this.procState = procState;
    }

    /**
     * @return the procType
     */
    public Integer getProcType()
    {
        return this.procType;
    }

    /**
     * @param objType the objType to set
     */
    public void setObjType(Integer objType)
    {
        this.objType = objType;
    }

    /**
     * @return the objType
     */
    public Integer getObjType()
    {
        return objType;
    }

    /**
     * @param procType the procType to set
     */
    public void setProcType(Integer procType)
    {
        this.procType = procType;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object o)
    {
        if ((o == null) || !(o instanceof Process))
        {
            return false;
        }
        Process other = (Process) o;
        if (null == this.procId)
        {
            if (other.procId != null)
                return false;
        }
        else if (!this.procId.equals(other.procId))
            return false;
        return true;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((procId == null) ? 0 : procId.hashCode());
        return result;
    }

}
