/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Procact.java
 * 日 期：Thu Oct 09 15:08:57 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * WFM_PROCACT
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "WFM_PROCACT", keyGenerator = "jetsennet.orm.executor.keygen.KeyGenerationNetSequence")
public class Procact implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_ACT_ID = "ACT_ID";
	public static String PROP_ACT_PARAM = "ACT_PARAM";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_PARENT_ID = "PARENT_ID";
	public static String PROP_PROCACT_ID = "PROCACT_ID";
	public static String PROP_PROCACT_NAME = "PROCACT_NAME";
	public static String PROP_PROC_ID = "PROC_ID";
	public static String PROP_PROC_VER = "PROC_VER";
	/**
	 * primary key field of procactId
	 */
	@FieldMapping(columnName = "PROCACT_ID", columnType = 4, primary = true)
	private Integer procactId;
	/**
	 * foreign key field of WFM_ACTIVITY.ACT_ID
	 */
	@FieldMapping(columnName = "ACT_ID", columnType = 4)
	private Integer actId;
	@FieldMapping(columnName = "ACT_PARAM", columnType = 2005)
	private String actParam;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "PARENT_ID", columnType = 4)
	private Integer parentId;
	@FieldMapping(columnName = "PROCACT_NAME", columnType = 12)
	private String procactName;
	/**
	 * foreign key field of WFM_PROCESS.PROC_ID
	 */
	@FieldMapping(columnName = "PROC_ID", columnType = 4)
	private Integer procId;
	@FieldMapping(columnName = "PROC_VER", columnType = 4)
    private Integer procVer;
	
	public Procact() {
		super();
	}

	public Procact(Integer procactId) {
		this.procactId = procactId;
	}

	public Procact(Integer actId, Integer parentId, Integer procId) {
		this.actId = actId;
		this.parentId = parentId;
		this.procId = procId;
	}

	/**
	 * @return the actId
	 */
	public Integer getActId() {
		return this.actId;
	}
	
	/**
	 * @param actId the actId to set
	 */
	public void setActId(Integer actId) {
		this.actId = actId;
	}

	/**
	 * @return the actParam
	 */
	public String getActParam() {
		return this.actParam;
	}
	
	/**
	 * @param actParam the actParam to set
	 */
	public void setActParam(String actParam) {
		this.actParam = actParam;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the parentId
	 */
	public Integer getParentId() {
		return this.parentId;
	}
	
	/**
	 * @param parentId the parentId to set
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * @return the procactId
	 */
	public Integer getProcactId() {
		return this.procactId;
	}
	
	/**
	 * @param procactId the procactId to set
	 */
	public void setProcactId(Integer procactId) {
		this.procactId = procactId;
	}

	/**
	 * @return the procactName
	 */
	public String getProcactName() {
		return this.procactName;
	}
	
	/**
	 * @param procactName the procactName to set
	 */
	public void setProcactName(String procactName) {
		this.procactName = procactName;
	}

	/**
	 * @return the procId
	 */
	public Integer getProcId() {
		return this.procId;
	}
	
	/**
     * @return the procVer
     */
    public Integer getProcVer() {
        return this.procVer;
    }
    
    /**
     * @param procVer the procVer to set
     */
    public void setProcVer(Integer procVer) {
        this.procVer = procVer;
    }
	
	/**
	 * @param procId the procId to set
	 */
	public void setProcId(Integer procId) {
		this.procId = procId;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Procact)) {
			return false;
		}
		Procact other = (Procact)o;
		if (null == this.procactId) {
			if (other.procactId != null)
				return false;
		} else if (!this.procactId.equals(other.procactId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((procactId == null) ? 0 : procactId.hashCode());
		return result;
	}
	
}