/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Sysconfig.java
 * 日 期：Thu Oct 09 15:08:58 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * WFM_SYSCONFIG
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "WFM_SYSCONFIG", keyGenerator = "java.util.UUID")
public class Sysconfig implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_DATA = "DATA";
	public static String PROP_DESCRIPTION = "DESCRIPTION";
	public static String PROP_NAME = "NAME";
	public static String PROP_TYPE = "TYPE";
	public static String PROP_VIEW_POS = "VIEW_POS";
	
	/**
	 * primary key field of name
	 */
	@FieldMapping(columnName = "NAME", columnType = 12, primary = true)
	private String name;
	@FieldMapping(columnName = "DATA", columnType = 12)
	private String data;
	@FieldMapping(columnName = "DESCRIPTION", columnType = 12)
	private String description;
	@FieldMapping(columnName = "TYPE", columnType = 4)
	private Integer type;
	@FieldMapping(columnName = "VIEW_POS", columnType = 4)
	private Integer viewPos;
	
	public Sysconfig() {
		super();
	}

	public Sysconfig(String name) {
		this.name = name;
	}

	/**
	 * @return the data
	 */
	public String getData() {
		return this.data;
	}
	
	/**
	 * @param data the data to set
	 */
	public void setData(String data) {
		this.data = data;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return this.description;
	}
	
	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return this.name;
	}
	
	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the type
	 */
	public Integer getType() {
		return this.type;
	}
	
	/**
	 * @param type the type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * @return the viewPos
	 */
	public Integer getViewPos() {
		return this.viewPos;
	}
	
	/**
	 * @param viewPos the viewPos to set
	 */
	public void setViewPos(Integer viewPos) {
		this.viewPos = viewPos;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Sysconfig)) {
			return false;
		}
		Sysconfig other = (Sysconfig)o;
		if (null == this.name) {
			if (other.name != null)
				return false;
		} else if (!this.name.equals(other.name))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}
	
}