/*
 * Copyright 2010-2016 the original author or authors.
 * 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 文件：jetsennet.wfm.schema.Tasklog.java
 * 日 期：Thu Oct 09 15:08:59 CST 2014
 */
package jetsennet.wfm.schema;

import java.io.Serializable;
import java.util.Date;
import org.uorm.orm.annotation.ClassMapping;
import org.uorm.orm.annotation.FieldMapping;

/**
 *
 * WFM_TASKLOG
 * this file is generated by the uorm pojo tools.
 *
 * @author <a href="mailto:xunchangguo@gmail.com">郭训常</a>
 * @version 1.0.0
 */
@ClassMapping(tableName = "WFM_TASKLOG", keyGenerator = "java.util.UUID")
public class Tasklog implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	public static String PROP_ACT_ID = "ACT_ID";
	public static String PROP_BACK_TIMES = "BACK_TIMES";
	public static String PROP_CREATE_TIME = "CREATE_TIME";
	public static String PROP_CREATE_USER = "CREATE_USER";
	public static String PROP_END_TIME = "END_TIME";
	public static String PROP_EXECUTE_USER = "EXECUTE_USER";
	public static String PROP_EXECUTE_USERID = "EXECUTE_USERID";
	public static String PROP_EXT_STATE = "EXT_STATE";
	public static String PROP_EXT_SYSID = "EXT_SYSID";
	public static String PROP_EXT_TASKID = "EXT_TASKID";
	public static String PROP_FIELD_1 = "FIELD_1";
	public static String PROP_FIELD_2 = "FIELD_2";
	public static String PROP_NEXT_STATE = "NEXT_STATE";
	public static String PROP_NEXT_TASKID = "NEXT_TASKID";
	public static String PROP_OBJ_ID = "OBJ_ID";
	public static String PROP_PROCACT_ID = "PROCACT_ID";
	public static String PROP_PROCEXEC_ID = "PROCEXEC_ID";
	public static String PROP_PROC_TYPE = "PROC_TYPE";
	public static String PROP_START_TIME = "START_TIME";
	public static String PROP_TASK_DESC = "TASK_DESC";
	public static String PROP_TASK_ID = "TASK_ID";
	public static String PROP_TASK_PARAM = "TASK_PARAM";
	public static String PROP_TASK_PERCENT = "TASK_PERCENT";
	public static String PROP_TASK_STATE = "TASK_STATE";
	
	/**
	 * primary key field of taskId
	 */
	@FieldMapping(columnName = "TASK_ID", columnType = 12, primary = true)
	private String taskId;
	@FieldMapping(columnName = "ACT_ID", columnType = 4)
	private Integer actId;
	@FieldMapping(columnName = "BACK_TIMES", columnType = 4)
	private Integer backTimes;
	@FieldMapping(columnName = "CREATE_TIME", columnType = 93)
	private Date createTime;
	@FieldMapping(columnName = "CREATE_USER", columnType = 12)
	private String createUser;
	@FieldMapping(columnName = "END_TIME", columnType = 93)
	private Date endTime;
	@FieldMapping(columnName = "EXECUTE_USER", columnType = 12)
	private String executeUser;
	@FieldMapping(columnName = "EXECUTE_USERID", columnType = 12)
	private String executeUserid;
	@FieldMapping(columnName = "EXT_STATE", columnType = 4)
	private Integer extState;
	@FieldMapping(columnName = "EXT_SYSID", columnType = 4)
	private Integer extSysid;
	@FieldMapping(columnName = "EXT_TASKID", columnType = 12)
	private String extTaskid;
	@FieldMapping(columnName = "FIELD_1", columnType = 12)
	private String field1;
	@FieldMapping(columnName = "FIELD_2", columnType = 12)
	private String field2;
	@FieldMapping(columnName = "NEXT_STATE", columnType = 4)
	private Integer nextState;
	@FieldMapping(columnName = "NEXT_TASKID", columnType = 12)
	private String nextTaskid;
	@FieldMapping(columnName = "OBJ_ID", columnType = 12)
	private String objId;
	@FieldMapping(columnName = "PROCACT_ID", columnType = 4)
	private Integer procactId;
	@FieldMapping(columnName = "PROCEXEC_ID", columnType = 12)
	private String procexecId;
	@FieldMapping(columnName = "PROC_TYPE", columnType = 4)
	private Integer procType;
	@FieldMapping(columnName = "START_TIME", columnType = 93)
	private Date startTime;
	@FieldMapping(columnName = "TASK_DESC", columnType = 12)
	private String taskDesc;
	@FieldMapping(columnName = "TASK_PARAM", columnType = 12)
	private String taskParam;
	@FieldMapping(columnName = "TASK_PERCENT", columnType = 4)
	private Integer taskPercent;
	@FieldMapping(columnName = "TASK_STATE", columnType = 4)
	private Integer taskState;
	
	public Tasklog() {
		super();
	}

	public Tasklog(String taskId) {
		this.taskId = taskId;
	}

	public Tasklog(Integer actId, Date createTime, Date endTime, String objId, Integer procactId, String procexecId, Integer procType, Date startTime) {
		this.actId = actId;
		this.createTime = createTime;
		this.endTime = endTime;
		this.objId = objId;
		this.procactId = procactId;
		this.procexecId = procexecId;
		this.procType = procType;
		this.startTime = startTime;
	}

	/**
	 * @return the actId
	 */
	public Integer getActId() {
		return this.actId;
	}
	
	/**
	 * @param actId the actId to set
	 */
	public void setActId(Integer actId) {
		this.actId = actId;
	}

	/**
	 * @return the backTimes
	 */
	public Integer getBackTimes() {
		return this.backTimes;
	}
	
	/**
	 * @param backTimes the backTimes to set
	 */
	public void setBackTimes(Integer backTimes) {
		this.backTimes = backTimes;
	}

	/**
	 * @return the createTime
	 */
	public Date getCreateTime() {
		return this.createTime;
	}
	
	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return this.createUser;
	}
	
	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the endTime
	 */
	public Date getEndTime() {
		return this.endTime;
	}
	
	/**
	 * @param endTime the endTime to set
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * @return the executeUser
	 */
	public String getExecuteUser() {
		return this.executeUser;
	}
	
	/**
	 * @param executeUser the executeUser to set
	 */
	public void setExecuteUser(String executeUser) {
		this.executeUser = executeUser;
	}

	/**
	 * @return the executeUserid
	 */
	public String getExecuteUserid() {
		return this.executeUserid;
	}
	
	/**
	 * @param executeUserid the executeUserid to set
	 */
	public void setExecuteUserid(String executeUserid) {
		this.executeUserid = executeUserid;
	}

	/**
	 * @return the extState
	 */
	public Integer getExtState() {
		return this.extState;
	}
	
	/**
	 * @param extState the extState to set
	 */
	public void setExtState(Integer extState) {
		this.extState = extState;
	}

	/**
	 * @return the extSysid
	 */
	public Integer getExtSysid() {
		return this.extSysid;
	}
	
	/**
	 * @param extSysid the extSysid to set
	 */
	public void setExtSysid(Integer extSysid) {
		this.extSysid = extSysid;
	}

	/**
	 * @return the extTaskid
	 */
	public String getExtTaskid() {
		return this.extTaskid;
	}
	
	/**
	 * @param extTaskid the extTaskid to set
	 */
	public void setExtTaskid(String extTaskid) {
		this.extTaskid = extTaskid;
	}

	/**
	 * @return the field1
	 */
	public String getField1() {
		return this.field1;
	}
	
	/**
	 * @param field1 the field1 to set
	 */
	public void setField1(String field1) {
		this.field1 = field1;
	}

	/**
	 * @return the field2
	 */
	public String getField2() {
		return this.field2;
	}
	
	/**
	 * @param field2 the field2 to set
	 */
	public void setField2(String field2) {
		this.field2 = field2;
	}

	/**
	 * @return the nextState
	 */
	public Integer getNextState() {
		return this.nextState;
	}
	
	/**
	 * @param nextState the nextState to set
	 */
	public void setNextState(Integer nextState) {
		this.nextState = nextState;
	}

	/**
	 * @return the nextTaskid
	 */
	public String getNextTaskid() {
		return this.nextTaskid;
	}
	
	/**
	 * @param nextTaskid the nextTaskid to set
	 */
	public void setNextTaskid(String nextTaskid) {
		this.nextTaskid = nextTaskid;
	}

	/**
	 * @return the objId
	 */
	public String getObjId() {
		return this.objId;
	}
	
	/**
	 * @param objId the objId to set
	 */
	public void setObjId(String objId) {
		this.objId = objId;
	}

	/**
	 * @return the procactId
	 */
	public Integer getProcactId() {
		return this.procactId;
	}
	
	/**
	 * @param procactId the procactId to set
	 */
	public void setProcactId(Integer procactId) {
		this.procactId = procactId;
	}

	/**
	 * @return the procexecId
	 */
	public String getProcexecId() {
		return this.procexecId;
	}
	
	/**
	 * @param procexecId the procexecId to set
	 */
	public void setProcexecId(String procexecId) {
		this.procexecId = procexecId;
	}

	/**
	 * @return the procType
	 */
	public Integer getProcType() {
		return this.procType;
	}
	
	/**
	 * @param procType the procType to set
	 */
	public void setProcType(Integer procType) {
		this.procType = procType;
	}

	/**
	 * @return the startTime
	 */
	public Date getStartTime() {
		return this.startTime;
	}
	
	/**
	 * @param startTime the startTime to set
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * @return the taskDesc
	 */
	public String getTaskDesc() {
		return this.taskDesc;
	}
	
	/**
	 * @param taskDesc the taskDesc to set
	 */
	public void setTaskDesc(String taskDesc) {
		this.taskDesc = taskDesc;
	}

	/**
	 * @return the taskId
	 */
	public String getTaskId() {
		return this.taskId;
	}
	
	/**
	 * @param taskId the taskId to set
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	/**
	 * @return the taskParam
	 */
	public String getTaskParam() {
		return this.taskParam;
	}
	
	/**
	 * @param taskParam the taskParam to set
	 */
	public void setTaskParam(String taskParam) {
		this.taskParam = taskParam;
	}

	/**
	 * @return the taskPercent
	 */
	public Integer getTaskPercent() {
		return this.taskPercent;
	}
	
	/**
	 * @param taskPercent the taskPercent to set
	 */
	public void setTaskPercent(Integer taskPercent) {
		this.taskPercent = taskPercent;
	}

	/**
	 * @return the taskState
	 */
	public Integer getTaskState() {
		return this.taskState;
	}
	
	/**
	 * @param taskState the taskState to set
	 */
	public void setTaskState(Integer taskState) {
		this.taskState = taskState;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof Tasklog)) {
			return false;
		}
		Tasklog other = (Tasklog)o;
		if (null == this.taskId) {
			if (other.taskId != null)
				return false;
		} else if (!this.taskId.equals(other.taskId))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		return result;
	}
	
}