
--======================================================================
--CMP_OBJTYPE
--======================================================================
CREATE TABLE CMP_OBJTYPE
(
	CMOBJ_TYPE	INT NOT NULL,
	TYPE_NAME	NVARCHAR(50) NOT NULL,
	TYPE_DESC	NVARCHAR(100),
	SCHEMA_NAME	NVARCHAR(10) NOT NULL,
	HAS_FILE	INT NOT NULL,
	BASE_TABLE  NVARCHAR(30) NOT NULL,
	CREATE_USER	NVARCHAR(50),
	CREATE_USERID	INT,
	CREATE_TIME	DATETIME DEFAULT GETDATE(),			
	CONSTRAINT P_CMP_OBJTYPE PRIMARY KEY (CMOBJ_TYPE) 
);


CREATE TABLE CMP_DATATABLE
(
	TABLE_NAME	NVARCHAR(30) NOT NULL,
	VIEW_NAME	NVARCHAR(30) NOT NULL,
	CMOBJ_TYPE  INT NOT NULL,
	TABLE_DESC  NVARCHAR(100),
	POSITION    INT NOT NULL,
	TABLE_TYPE  INT NOT NULL,
	CONSTRAINT P_CMP_DATATABLE PRIMARY KEY (TABLE_NAME) 
);

CREATE TABLE CMP_DATAFIELD
(
	FIELD_NAME	NVARCHAR(30) NOT NULL,
	VIEW_NAME	NVARCHAR(30) NOT NULL,
	TABLE_NAME	NVARCHAR(30) NOT NULL,
	DATA_TYPE	NVARCHAR(30) NOT NULL,
	DATA_LENGTH	INT NOT NULL,
	IS_KEY	INT NOT NULL,
	NULLABLE 	INT NOT NULL,
	IS_INDEX   INT NOT NULL,
	CMOBJ_TYPE  INT NOT NULL,
	FIELD_DESC  NVARCHAR(30),
	POSITION   INT NOT NULL,
	FIELD_TYPE INT NOT NULL,
	CONSTRAINT P_CMP_DATAFIELD PRIMARY KEY (TABLE_NAME, FIELD_NAME) 
);

CREATE TABLE CMP_DATAMAP
(
	TABLE_NAME	NVARCHAR(30) NOT NULL,	
	FIELD_NAME	NVARCHAR(30) NOT NULL,
	CMOBJ_TYPE  INT NOT NULL,
	MAP_TYPE INT,
	MAP_TABLE	NVARCHAR(30) NOT NULL,	
	MAP_FIELD	NVARCHAR(30) NOT NULL,
	CONSTRAINT P_CMP_DATAMAP PRIMARY KEY (TABLE_NAME, MAP_TABLE)	
);

CREATE TABLE CMP_UIVIEW
(
	VIEW_NAME NVARCHAR(20) NOT NULL,
	VIEW_TYPE INT NOT NULL,		
	CMOBJ_TYPE  INT NOT NULL,
	VIEW_DESC	NVARCHAR(100) ,
	VIEW_CONTENT 	TEXT,
	CONSTRAINT P_CMP_UIVIEW PRIMARY KEY (VIEW_NAME) 
);


--======================================================================
--CMP_CTRLWORD
--======================================================================
CREATE TABLE CMP_CTRLWORD
(
	ID	NVARCHAR(36) NOT NULL,
	CMOBJ_TYPE	INT,
	CW_LEVEL INT,
	CW_TYPE	INT NOT NULL,
	CW_NAME	NVARCHAR(100),
	CW_CODE NVARCHAR(30),
	CW_DESC	NVARCHAR(200),
	CW_POS INT,	
	CREATE_USER NVARCHAR(50),
	CREATE_USERID	INT,
	CREATE_TIME DATETIME DEFAULT GETDATE(),	
	CONSTRAINT P_CMP_CTRLWORD PRIMARY KEY (ID) 
);
--======================================================================
--CMP_CTRLCLASS
--======================================================================
CREATE TABLE CMP_CTRLCLASS
(
	ID	NVARCHAR(36) NOT NULL,	
	PARENT_ID	NVARCHAR(36),
	CMOBJ_TYPE	INT NOT NULL,
	CLASS_TYPE	INT NOT NULL,
	CLASS_NAME	NVARCHAR(100) NOT NULL,		
	CLASS_LAYER NVARCHAR(30),
	CLASS_DESC	NVARCHAR(100),
	VIEW_NAME	NVARCHAR(300),		
	SUB_CLASSID	NVARCHAR(36),
	CREATE_USER NVARCHAR(50),
	CREATE_USERID	INT,
	CREATE_TIME DATETIME DEFAULT GETDATE(),			
	CONSTRAINT P_CMP_CTRLCLASS PRIMARY KEY (ID) 
);

--======================================================================
--CMP_SUBCLASS
--======================================================================
CREATE TABLE CMP_SUBCLASS
(
	ID	NVARCHAR(36) NOT NULL,	
	TYPE	INT NOT NULL,
	PARENT_ID	NVARCHAR(36),	
	LAYER INT NOT NULL,
	NAME	NVARCHAR(100) NOT NULL,	
	DESCRIPTION	NVARCHAR(200),
	VIEW_NAME	NVARCHAR(200),			
	CONSTRAINT P_SUBCLASS PRIMARY KEY (ID) 
);
-----------------------------------------------------------------------
--============= 测试数据

--======================================================================
--CM1_OBJECT
--======================================================================
CREATE TABLE CM1_OBJECT
(
	CMOBJ_ID varchar(50) NOT NULL,	
	PARENT_ID varchar(50),	
	ROOT_ID varchar(50),
	NAME NVARCHAR(300) NOT NULL,
	CMOBJ_TYPE INT,
	KEY_WORDS NVARCHAR(500),
	CONTENT NVARCHAR(2000),
	DURATION INT,
	IN_POINT INT,
	ICON_PATH NVARCHAR(500),
	STATE INT NOT NULL,		
	CREATE_USER NVARCHAR(50) NOT NULL, 
	CREATE_USERID NVARCHAR(50),
	CREATE_TIME DATETIME DEFAULT GETDATE() NOT NULL,
	UPDATE_USER NVARCHAR(50) NOT NULL, 
	UPDATE_USERID NVARCHAR(50),
	UPDATE_TIME DATETIME DEFAULT GETDATE() NOT NULL,
	STR_1		NVARCHAR(500),
	STR_2		NVARCHAR(500),
	STR_3		NVARCHAR(500),
	STR_4		NVARCHAR(500),
	STR_5		NVARCHAR(500),
	INT_1		INT,
	INT_2		INT,	
	NUM_1		NUMERIC,
	NUM_2		NUMERIC,
	TIME_1		DATETIME,
	TIME_2		DATETIME,
	TIME_3		DATETIME,
	STR_6		NVARCHAR(500),
	STR_7		NVARCHAR(500),
	STR_8		NVARCHAR(500),
	STR_9		NVARCHAR(500),
	STR_10		NVARCHAR(500),
	STR_11		NVARCHAR(1000),
	STR_12		NVARCHAR(1000),
	STR_13		NVARCHAR(1000),
	STR_14		NVARCHAR(1000),
	STR_15		NVARCHAR(1000),
	INT_3		INT,
	INT_4		INT,	
	INT_5		INT,
	NUM_3		NUMERIC,
	NUM_4		NUMERIC,	
	NUM_5		NUMERIC,
	TIME_4		DATETIME,
	TIME_5		DATETIME
);
ALTER TABLE CM1_OBJECT ADD  CONSTRAINT P_CM1_OBJECT PRIMARY KEY CLUSTERED 
(
	CMOBJ_ID DESC
);

--======================================================================
--CM1_FILEGROUP
--======================================================================
CREATE TABLE CM1_FILEGROUP
(
	GROUP_ID	varchar(50) NOT NULL,
	CMOBJ_ID	varchar(50),
	GROUP_TYPE	INT,	
	IS_ONLINE	INT,
	IS_ARCHIVE  INT,
	CREATE_TIME DATETIME,
	CREATE_USER NVARCHAR(50),
	CREATE_USERID  INT,
	STR_1		NVARCHAR(500),
	STR_2		NVARCHAR(500),
	STR_3		NVARCHAR(500),
	STR_4		NVARCHAR(500),
	STR_5		NVARCHAR(500),
	INT_1		INT,
	INT_2		INT,	
	NUM_1		NUMERIC,
	NUM_2		NUMERIC,	
	STR_6		NVARCHAR(500),
	STR_7		NVARCHAR(500),
	STR_8		NVARCHAR(500),
	STR_9		NVARCHAR(500),
	STR_10		NVARCHAR(500),
	STR_11		NVARCHAR(1000),
	STR_12		NVARCHAR(1000),
	STR_13		NVARCHAR(1000),
	STR_14		NVARCHAR(1000),
	STR_15		NVARCHAR(1000),	
	INT_3		INT,
	INT_4		INT,	
	INT_5		INT,
	NUM_3		NUMERIC,
	NUM_4		NUMERIC,	
	NUM_5		NUMERIC,
	STR_16		NVARCHAR(1000),
	STR_17		NVARCHAR(1000),
	STR_18		NVARCHAR(1000),
	STR_19		NVARCHAR(1000),
	STR_20		NVARCHAR(1000),
	CONSTRAINT P_CM1_FILEGROUP PRIMARY KEY (GROUP_ID) 
);
--======================================================================
--CM1_FILEITEM
--======================================================================
CREATE TABLE CM1_FILEITEM
(
	FILE_ID		varchar(50) NOT NULL,
	GROUP_ID	varchar(50),
	CMOBJ_ID	varchar(50),
	FILE_TYPE INT,
	SOURCE_PATH NVARCHAR(500),
	SOURCE_FILENAME NVARCHAR(500),
	DEST_PATH NVARCHAR(500),
	DEST_FILENAME NVARCHAR(500),
	FILE_SIZE NVARCHAR(50),
	FILE_MD5 NVARCHAR(200),	
	STR_1 NVARCHAR(500),
	STR_2 NVARCHAR(500),
	CONSTRAINT P_CM1_FILEITEM PRIMARY KEY (FILE_ID)
);

--======================================================================
--CM1_QCSEQUENCE
--======================================================================
CREATE TABLE CM1_QCSEQUENCE
(
	ID varchar(50) NOT NULL,
	CMOBJ_ID varchar(50) NOT NULL,
	GROUP_TYPE	INT,	
	IN_POINT INT,
	OUT_POINT INT,
	QC_TYPE NVARCHAR(50),
	CHANNEL INT,
	DESCRIPTION NVARCHAR(200),
	TYPE INT,
	STR_1 NVARCHAR(500),
	STR_2 NVARCHAR(500),
	CONSTRAINT P_CM1_QCSEQUENCE PRIMARY KEY (ID)
);

CREATE INDEX INDEX_CM1_QCSEQUENCE ON CM1_QCSEQUENCE (CMOBJ_ID ASC);

INSERT INTO CMP_OBJTYPE(CMOBJ_TYPE,TYPE_NAME,TYPE_DESC,SCHEMA_NAME,HAS_FILE,BASE_TABLE,CREATE_USER,CREATE_USERID) VALUES ( 0 , '视频' , '视频节目' , 'CM1' , 0 , 'CM1_OBJECT' , '管理员' , 1 );

-----------------------------------------------------------------------