---UUM_FUNCTION

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200, 0, '业务管理', '0011.png', 0, '业务管理', 0, 200, 0, NULL, NULL, NULL, NULL);

INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200010, 200, '个人首页', 'jbds/person.html', 0, '', 0, 10, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200020, 200, '投稿情况查询', 'jbds/reportSearch2.html', 0, 'jbds/reportSearch.html', 0, 20, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200030, 200, '论文浏览', '', 0, '嵌第三方页面', 0, 30, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200040, 200, '消息发布', 'jbds/msgPublish.html', 0, '', 0, 40, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200050, 200, '最新论文标题', '', 0, '', 0, 50, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200060, 200, '个人首页', 'jbds/personChu.html', 0, '处领导个人首页', 0, 60, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200070, 200, '投稿情况查询', 'jbds/reportSearchNew.html', 0, '处领导投稿查询', 0, 70, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200080, 200, '个人首页', 'jbds/personJu.html', 0, '局领导个人首页', 0, 80, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200090, 200, '数据资源', 'jbds/reportSearchNew.html', 0, '局领导投稿情况查询', 0, 90, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200100, 200, '指挥', 'jbds/zhChu.html', 0, '处领导指挥', 0, 100, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200110, 200, '指挥', 'jbds/zhJu.html', 0, '局领导指挥', 0, 110, NULL, NULL, 'screen.width', 'screen.width', NULL);
INSERT INTO UUM_FUNCTION (ID, PARENT_ID, NAME, PARAM, STATE, DESCRIPTION, TYPE, VIEW_POS, VIEW_FLAG, IMAGES, OPEN_WIDTH, OPEN_HEIGHT, VTARGET) VALUES 
(200120, 200, '线路查询', 'jbds/lineSearchChu.html', 0, '处/局 领导线路查询', 0, 120, NULL, NULL, 'screen.width', 'screen.width', NULL);
